<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>A Cars II – Sustainable Energy — Without the Hot Air</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/chapB.html" rel="next">
<link href="../chapters/chap32.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-8af8f98213e2c1b30ec54438e312c198.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Pageview counting, same GoatCounter account as the elmix site. No cookies,
     no cross-site identifiers, nothing that needs a consent banner.
     Pinned to the versioned file with an SRI hash: count.js is a mutable URL
     and this runs in <head> on every page. -->
<script data-goatcounter="https://oluies.goatcounter.com/count" async="" src="https://gc.zgo.at/count.v4.js" integrity="sha384-nRw6qfbWyJha9LhsOtSb2YJDyZdKvvCFh0fJYlkquSFjUxp9FVNugbfy8q1jdxI+" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chapA.html">Part III · Technical chapters</a></li><li class="breadcrumb-item"><a href="../chapters/chapA.html"><span class="chapter-title">A Cars II</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Sustainable Energy — Without the Hot Air</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About this edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I · Numbers, not adjectives</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap01.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1 Motivations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap02.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2 The balance sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap03.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3 Cars</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap04.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4 Wind</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap05.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5 Planes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap06.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6 Solar</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap07.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7 Heating and cooling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap08.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8 Hydroelectricity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap09.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">9 Light</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap10.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10 Offshore wind</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap11.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11 Gadgets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap11a.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11a The machines behind the screen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap12.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12 Wave</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap13.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13 Food and farming</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap14.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14 Tide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap15.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15 Stuff</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap16.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">16 Geothermal</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap17.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17 Public services</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap18.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18 Can we live on renewables?</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II · Making a difference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap19.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19 Every BIG helps</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap20.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20 Better transport</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap21.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">21 Smarter heating</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap22.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">22 Efficient electricity use</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap23.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">23 Sustainable fossil fuels?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap24.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">24 Nuclear?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap25.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">25 Living on other countries’ renewables?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap26.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">26 Fluctuations and storage</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap27.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">27 Five energy plans for Britain</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap28.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">28 Putting costs in perspective</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap-value-of-renewables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">28a The value of renewable energy as it scales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap29.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">29 What to do now</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap30.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">30 Energy plans for Europe, America, and the World</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap31.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">31 The last thing we should talk about</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap32.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">32 Saying yes</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III · Technical chapters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapA.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">A Cars II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapB.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">B Wind II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapC.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">C Planes II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapD.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">D Solar II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapE.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">E Heating II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapF.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">F Waves II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapG.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">G Tide II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapH.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">H Stuff II</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV · Useful data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapI.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">I Quick reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapJ.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">J Populations and areas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapK.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">K UK energy history</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapL.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">L The world in 2025</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapM.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">M Energy return on investment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapN.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">N Peak oil, peak gas, peak uranium</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapO.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">O The hydrogen ladder</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/charts.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Charts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/bibliography.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bibliography</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/author.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The author</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/acknowledgments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Acknowledgments</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#bicycles-and-the-scaling-trick" id="toc-bicycles-and-the-scaling-trick" class="nav-link active" data-scroll-target="#bicycles-and-the-scaling-trick">Bicycles and the scaling trick</a></li>
  <li><a href="#what-about-rolling-resistance" id="toc-what-about-rolling-resistance" class="nav-link" data-scroll-target="#what-about-rolling-resistance">What about rolling resistance?</a></li>
  <li><a href="#dependence-of-power-on-speed" id="toc-dependence-of-power-on-speed" class="nav-link" data-scroll-target="#dependence-of-power-on-speed">Dependence of power on speed</a></li>
  <li><a href="#electric-cars-is-range-a-problem" id="toc-electric-cars-is-range-a-problem" class="nav-link" data-scroll-target="#electric-cars-is-range-a-problem">Electric cars: is range a problem?</a></li>
  <li><a href="#the-model-survived-the-cars-got-heavier" id="toc-the-model-survived-the-cars-got-heavier" class="nav-link" data-scroll-target="#the-model-survived-the-cars-got-heavier">The model survived; the cars got heavier</a></li>
  <li><a href="#notes-and-further-reading" id="toc-notes-and-further-reading" class="nav-link" data-scroll-target="#notes-and-further-reading">Notes and further reading</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chapA.html">Part III · Technical chapters</a></li><li class="breadcrumb-item"><a href="../chapters/chapA.html"><span class="chapter-title">A Cars II</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">A Cars II</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><em>(Figure omitted from this edition: third-party rights.)</em></p>
</blockquote>
<p><span class="figurenumber">Figure A.1.</span>A Peugot 206 has a drag coefficient of 0.33. Photo by Christopher Batt.</p>
<p>We estimated that a car driven 100 km uses about 80 kWh of energy.</p>
<p>Where does this energy go? How does it depend on properties of the car? Could we make cars that are 100 times more efficient? Let’s make a simple cartoon of car-driving, to describe where the energy goes. The energy in a typical fossil-fuel car goes to four main destinations, all of which we will explore:</p>
<ol type="1">
<li>speeding up then slowing down using the brakes;</li>
<li>air resistance;</li>
<li>rolling resistance;</li>
<li>heat – 75% of the energy is thrown away as heat, because the energy-conversion chain is inefficient.</li>
</ol>
<p>The key formula for most of the calculations in this book is:</p>
<p><span class="math display">\[
\text{kinetic\ energy} = \frac{1}{2}mv^{2}
\]</span></p>
<p>For example, a car of mass <em>m</em> = 1000 kg moving at 100 km per hour or <em>v</em> = 28 m/s has an energy of</p>
<p><span class="math display">\[
\frac{1}{2}mv^{2} \simeq \text{390~000~J} \simeq \text{0.1~kWh.}
\]</span></p>
<p><img src="img/without-hot-air/figure253.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure A.2.</span>Our cartoon: a car moves at speed <em>v</em> between stops separated by a distance <em>d</em>.</p>
<p>Initially our cartoon will ignore rolling resistance; we’ll add in this effect later in the chapter.</p>
<p>Assume the driver accelerates rapidly up to a cruising speed <em>v</em>, and maintains that speed for a distance <em>d</em>, which is the distance between traffic lights, stop signs, or congestion events. At this point, he slams on the brakes and turns all his kinetic energy into heat in the brakes. (This vehicle doesn’t have fancy regenerative braking.) Once he’s able to move again, he accelerates back up to his cruising speed, <em>v</em>. This acceleration gives the car kinetic energy; braking throws that kinetic energy away.</p>
<p>Energy goes not only into the brakes: while the car is moving, it makes air swirl around. A car leaves behind it a tube of swirling air, moving at a speed similar to <em>v</em>. Which of these two forms of energy is the bigger: kinetic energy of the swirling air, or heat in the brakes? Let’s work it out.</p>
<p>The car speeds up and slows down once in each duration <em>d/v</em>. The rate at which energy pours into the brakes is:</p>
<p><span class="math display">\[
\begin{matrix}
{\frac{\text{kinetic\ energy}}{\text{time\ between\ braking\ events}} = \frac{\frac{\text{1}}{\text{2}}m_{c}v^{2}}{d/v} = \frac{\frac{\text{1}}{\text{2}}m_{c}v^{3}}{d}} \\
\end{matrix}
\]</span></p>
<p>where <em>m<sub>c</sub></em> is the mass of the car.</p>
<p><img src="img/without-hot-air/figure251.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure A.3.</span>A car moving at speed <em>v</em> creates behind it a tube of swirling air; the cross-sectional area of the tube is similar to the frontal area of the car, and the speed at which air in the tube swirls is roughly <em>v</em>.</p>
<p>The tube of air created in a time <em>t</em> has a volume <em>Avt</em>, where <em>A</em> is the cross-sectional area of the tube, which is similar to the area of the front view of the car. (For a streamlined car, <em>A</em> is usually a little smaller than the frontal area <em>A</em><sub>car</sub>, and the ratio of the tube’s effective cross-sectional area to the car area is called the drag coefficient <em>c</em><sub>d</sub>. Throughout the following equations, <em>A</em> means the effective area of the car, <em>c</em><sub>d</sub><em>A</em><sub>car</sub>.) The tube has mass <em>m</em><sub>air</sub> = <em>ρAvt</em> (where <em>ρ</em> is the density of air) and swirls at speed <em>v</em>, so its kinetic energy is:</p>
<p>I’m using this formula: mass = density × volume</p>
<p>The symbol <em>ρ</em> (Greek letter ‘rho’) denotes the density.</p>
<p><span class="math display">\[
\frac{\text{1}}{\text{2}}m_{\text{air}}v^{2} = \frac{\text{1}}{\text{2}}\rho Avt\ v^{2}
\]</span></p>
<p>and the rate of generation of kinetic energy in swirling air is:</p>
<p><span class="math display">\[
\frac{\frac{\text{1}}{\text{2}}\rho Avt\ v^{2}}{t} = \frac{\text{1}}{\text{2}}\rho Av^{3}
\]</span></p>
<p><img src="img/without-hot-air/figure254.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure A.4.</span> To know whether energy consumption is braking-dominated or air-swirling-dominated, we compare the mass of the car with the mass of the tube of air between stop-signs.</p>
<p><img src="img/without-hot-air/figure255.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure A.5.</span> Power consumed by a car is proportional to its cross-sectional area, during motorway driving, and to its mass, during town driving. Guess which gets better mileage – the VW on the left, or the spaceship?</p>
<p>So the total rate of energy production by the car is:</p>
<p><span class="math display">\[
\begin{matrix}
{\text{power\ going\ into\ brakes} + \text{power\ going\ into\ swirling\ air}} \\
{= \frac{\text{1}}{\text{2}}{{m_{c}v^{3}}/d} + \frac{\text{1}}{\text{2}}\rho Av^{3}} \\
\end{matrix}
\]</span></p>
<p>Both forms of energy dissipation scale as <em>v</em><sup>3</sup>. So this cartoon predicts that a driver who halves his speed <em>v</em> makes his power consumption 8 times smaller. If he ends up driving the same total distance, his journey will take twice as long, but the total energy consumed by his journey will be four times smaller.</p>
<p>Which of the two forms of energy dissipation – brakes or air-swirling – is the bigger? It depends on the ratio of</p>
<p><span class="math display">\[
{\left( {m_{c}/d} \right)/\left( {\rho A} \right)}\text{.}
\]</span></p>
<p>If this ratio is much bigger than 1, then more power is going into brakes; if it is smaller, more power is going into swirling air. Rearranging this ratio, it is bigger than 1 if</p>
<p><span class="math display">\[
m_{c} &gt; \rho Ad\text{.}
\]</span></p>
<p>Now, <em>Ad</em> is the volume of the tube of air swept out from one stop sign to the next. And <em>ρAd</em> is the mass of that tube of air. So we have a very simple situation: energy dissipation is dominated by kinetic-energy-being-dumped-into-the-brakes if the mass of the car is <em>bigger</em> than the mass of the tube of air from one stop sign to the next; and energy dissipation is dominated by making-air-swirl if the mass of the car is <em>smaller</em> (figure A.4).</p>
<p>Let’s work out the special distance <em>d</em>* between stop signs, below which the dissipation is braking-dominated and above which it is air-swirling dominated (also known as drag-dominated). If the frontal area of the car is:</p>
<p><span class="math display">\[
A_{\text{car}} = \text{2\ m\ wide} \times \text{1.5\ m\ high} = \text{3\ m}^{\text{2}}
\]</span></p>
<p>and the drag coefficient is <span class="math inline">\(c_{\text{d}} = \frac{1}{3}\)</span> and the mass is <span class="math inline">\(m_{\text{c}} = 1000\text{~kg}\)</span> then the special distance is:</p>
<p><span class="math display">\[
d^{*} = \frac{m_{\text{c}}}{\rho c_{\text{d}}A_{\text{car}}} = \frac{\text{1000\ kg}}{\text{1.3~}{\text{kg}/{\text{m}^{\text{3}} \times \frac{\text{1}}{\text{3}} \times \text{3~}\text{m}^{\text{2}}}}} = \text{750\ m}
\]</span></p>
<p>So “city-driving” is dominated by kinetic energy and braking if the distance between stops is less than 750 m. Under these conditions, it’s a good idea, if you want to save energy:</p>
<ol type="1">
<li>to reduce the mass of your car;</li>
<li>to get a car with regenerative brakes (which roughly halve the energy lost in braking – see Chapter 20); <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> and</li>
<li>to drive more slowly.</li>
</ol>
<p>When the stops are significantly more than 750 m apart, energy dissipation is drag-dominated. Under these conditions, it doesn’t much matter what your car weighs. Energy dissipation will be much the same whether the car contains one person or six. Energy dissipation can be reduced:</p>
<ol type="1">
<li>by reducing the car’s drag coefficient;</li>
<li>by reducing its cross-sectional area; or</li>
<li>by driving more slowly.</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Vehicle</th>
<th></th>
<th>Energy per distance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Car at 110 km/h</td>
<td>↔︎</td>
<td>80 kWh/(100 km)</td>
</tr>
<tr class="even">
<td>Bicycle at 21 km/h</td>
<td>↔︎</td>
<td>2.4 kWh/(100 km)</td>
</tr>
<tr class="odd">
<td>Planes at 900 km/h</td>
<td>A380</td>
<td>27 kWh/100 seat-km</td>
</tr>
</tbody>
</table>
<p><span class="figurenumber">Table A.6.</span> Facts worth remembering: car energy consumption.</p>
<p>The actual energy consumption of the car will be the energy dissipation in equation (A.2), cranked up by a factor related to the inefficiency of the engine and the transmission. Typical petrol engines are about 25% efficient, <a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> so of the chemical energy that a car guzzles, three quarters is wasted in making the car’s engine and radiator hot, and just one quarter goes into “useful” energy:</p>
<p><span class="math display">\[
\text{total\ power\ of\ car} \simeq 4\left\lbrack {\frac{\text{1}}{\text{2}}m_{\text{c}}v^{3}/d + \frac{\text{1}}{\text{2}}\rho Av^{3}} \right\rbrack
\]</span></p>
<p>Let’s check this theory of cars by plugging in plausible numbers for motorway driving. Let <em>v</em> = 70 miles per hour = 110 km/h = 31 m/s and <span class="math inline">\({A = c_{\text{d}}A_{\text{car}} = \text{1\ m}^{2}}\text{.}\)</span> The power consumed by the engine is estimated to be <span id="chA-80kW">roughly</span></p>
<p><span class="math display">\[
4 \times \frac{\text{1}}{\text{2}}\rho Av^{3} = 2 \times 1.3{\text{~kg}/\text{m}}^{\text{3}} \times \text{1}\text{~m}^{\text{2}} \times \left( 31\text{~m}/\text{s} \right)^{\text{3}} = 80\text{~kW}
\]</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Drag coefficient, <em>c</em><sub>d</sub></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Cars</strong></td>
<td></td>
</tr>
<tr class="even">
<td>Honda Insight</td>
<td>0.25</td>
</tr>
<tr class="odd">
<td>Prius</td>
<td>0.26</td>
</tr>
<tr class="even">
<td>Renault 25</td>
<td>0.28</td>
</tr>
<tr class="odd">
<td>Honda Civic (2006)</td>
<td>0.31</td>
</tr>
<tr class="even">
<td>VW Polo GTi</td>
<td>0.32</td>
</tr>
<tr class="odd">
<td>Peugeot 206</td>
<td>0.33</td>
</tr>
<tr class="even">
<td>Ford Sierra</td>
<td>0.34</td>
</tr>
<tr class="odd">
<td>Audi TT</td>
<td>0.35</td>
</tr>
<tr class="even">
<td>Honda Civic (2001)</td>
<td>0.36</td>
</tr>
<tr class="odd">
<td>Citroën 2CV</td>
<td>0.51</td>
</tr>
<tr class="even">
<td><strong>Other</strong></td>
<td></td>
</tr>
<tr class="odd">
<td>Cyclist</td>
<td>0.9</td>
</tr>
<tr class="even">
<td>Long-distance coach</td>
<td>0.425</td>
</tr>
<tr class="odd">
<td><strong>Planes</strong></td>
<td></td>
</tr>
<tr class="even">
<td>Cessna</td>
<td>0.027</td>
</tr>
<tr class="odd">
<td>Learjet</td>
<td>0.022</td>
</tr>
<tr class="even">
<td>Boeing 747</td>
<td>0.031</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Drag area, <em>c</em><sub>d</sub><em>A</em><sub>car</sub> (m<sup>2</sup>)</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Land Rover Discovery</td>
<td>1.6</td>
</tr>
<tr class="even">
<td>Volvo 740</td>
<td>0.81</td>
</tr>
<tr class="odd">
<td><strong>Typical car</strong></td>
<td><strong>0.8</strong></td>
</tr>
<tr class="even">
<td>Honda Civic</td>
<td>0.68</td>
</tr>
<tr class="odd">
<td>VW Polo GTi</td>
<td>0.65</td>
</tr>
<tr class="even">
<td>Honda Insight</td>
<td>0.47</td>
</tr>
</tbody>
</table>
<p><span class="figurenumber">Table A.7.</span> Drag coefficients and drag areas. The two panels measure different things: the coefficient is dimensionless and describes the shape alone, while the drag area multiplies it by the frontal area and so is what actually enters the power calculation above. A typical car’s 0.8 m<sup>2</sup> is the figure rounded to 1 m<sup>2</sup> in the worked example.</p>
<p>If you drive the car at this speed for one hour every day, then you travel 110 km and use <span class="red">80 kWh</span> of energy per day. If you drove at half this speed for two hours per day instead, you would travel the same distance and use up <span class="red">20 kWh</span> of energy. This simple theory seems consistent with the mileage figures for cars quoted in Chapter 3. Moreover, the theory gives insight into how the energy consumed by your car could be reduced. The theory has a couple of flaws which we’ll explore in a moment.</p>
<p>Could we make a new car that consumes 100 times less energy and still goes at 70mph? <strong>No</strong>. Not if the car has the same shape. On the motorway at 70mph, the energy is going mainly into making air swirl. Changing the materials the car is made from makes no difference to that. A miraculous improvement to the fossil-fuel engine could perhaps boost its efficiency from 25% to 50%, bringing the energy consumption of a fossil-fuelled car down to roughly 40 kWh per 100 km.</p>
<p>Electric vehicles have some wins: while the weight of the energy store, per useful kWh stored, is about 25 times bigger than that of petrol, the weight of an electric engine can be about 8 times smaller. <a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> And the energy-chain in an electric car is much more efficient: electric motors can be 90% efficient.</p>
<p>We’ll come back to electric cars in more detail towards the end of this chapter.</p>
<section id="bicycles-and-the-scaling-trick" class="level3">
<h3 class="anchored" data-anchor-id="bicycles-and-the-scaling-trick">Bicycles and the scaling trick</h3>
<p>Here’s a fun question: what’s the energy consumption of a bicycle, in kWh per 100 km? Pushing yourself along on a bicycle requires energy for the same reason as a car: you’re making air swirl around. Now, we could do all the calculations from scratch, replacing car-numbers by bike-numbers. But there’s a simple trick we can use to get the answer for the bike from the answer for the car. The energy consumed by a car, per distance travelled, is the power-consumption associated with air-swirling,</p>
<p><span class="math display">\[
4 \times \frac{\text{1}}{\text{2}}\rho Av^{3}
\]</span></p>
<p>divided by the speed, <em>v</em>; that is,</p>
<p><span class="math display">\[
\text{energy\ per\ distance} = 4 \times \frac{\text{1}}{\text{2}}\rho Av^{2}
\]</span></p>
<p>The “4” came from engine inefficiency; <em>ρ</em> is the density of air; the area <span class="math inline">\(A = c_{\text{d}}A_{\text{car}}\)</span> is the effective frontal area of a car; and <em>v</em> is its speed. Now, we can compare a bicycle with a car by dividing <span class="math inline">\(4 \times \frac{\text{1}}{\text{2}}\rho Av^{2}\)</span> for the bicycle by <span class="math inline">\(4 \times \frac{\text{1}}{\text{2}}\rho Av^{2}\)</span> for the car. All the fractions and <em>ρ</em> cancel, if the efficiency of the carbon-powered bicyclist’s engine is similar to the efficiency of the carbon-powered car engine (which it is). The ratio is:</p>
<p><span class="math display">\[
\frac{\text{energy\ per\ distance\ of\ bike}}{\text{energy\ per\ distance\ of\ car}} = \frac{c_{\text{d}}^{\text{bike}}A_{\text{bike}}v_{\text{bike}}^{2}}{c_{\text{d}}^{\text{car}}A_{\text{car}}v_{\text{car}}^{2}}
\]</span></p>
<p>The trick we are using is called “scaling.” If we know how energy consumption scales with speed and area, then we can predict energy consumption of objects with completely different speeds and areas. Specifically, let’s assume that the area ratio is</p>
<p><span class="math display">\[
\frac{A_{\text{bike}}}{A_{\text{car}}} = \frac{1}{4}
\]</span></p>
<p>(Four cyclists can sit shoulder to shoulder in the width of one car.) Let’s assume the bike is not very well streamlined:</p>
<p><span class="math display">\[
\frac{c_{\text{d}}^{\text{bike}}}{c_{\text{d}}^{\text{car}}} = \frac{1}{\frac{\text{1}}{\text{3}}}
\]</span></p>
<p>And let’s assume the speed of the bike is 21 km/h (13 miles per hour), so</p>
<p><span class="math display">\[
\frac{v_{\text{bike}}}{v_{\text{car}}} = \frac{1}{5}
\]</span></p>
<p>Then</p>
<p><span class="math display">\[
\begin{matrix}
\\
{= \left( {\frac{c_{\text{d}}^{\text{bike}}}{c_{\text{d}}^{\text{car}}}\frac{A_{\text{bike}}}{A_{\text{car}}}} \right)\left( \frac{v_{\text{bike}}}{v_{\text{car}}} \right)^{2}} \\
{= \left( \frac{3}{4} \right) \times \left( \frac{1}{5} \right)^{2}} \\
{= \frac{3}{100}} \\
\end{matrix}
\]</span></p>
<p>So a cyclist at 21 km/h consumes about 3% of the energy per kilometre of a lone car-driver on the motorway – about <strong>2.4 kWh per 100 km</strong>.</p>
<p>If you would like a vehicle whose fuel efficiency is 30 times better than a car’s, it’s simple: ride a bike.</p>
</section>
<section id="what-about-rolling-resistance" class="level3">
<h3 class="anchored" data-anchor-id="what-about-rolling-resistance">What about rolling resistance?</h3>
<p>Some things we’ve completely ignored so far are the energy consumed in the tyres and bearings of the car, the energy that goes into the noise of wheels against asphalt, the energy that goes into grinding rubber off the tyres, and the energy that vehicles put into shaking the ground. Collectively, these forms of energy consumption are called <em>rolling resistance</em>. The standard model of rolling resistance asserts that the force of rolling resistance is simply proportional to the weight of the vehicle, independent of the speed. The constant of proportionality is called the coefficient of rolling resistance, <em>C</em><span class="smallfont1"><sub>rr</sub></span>. Table A.8 gives some typical values.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>wheel</th>
<th><em>C</em><sub>rr</sub></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>train (steel on steel)</td>
<td>0.002</td>
</tr>
<tr class="even">
<td>bicycle tyre</td>
<td>0.005</td>
</tr>
<tr class="odd">
<td>truck rubber tyres</td>
<td>0.007</td>
</tr>
<tr class="even">
<td>car rubber tyres</td>
<td>0.010</td>
</tr>
</tbody>
</table>
<p><span class="figurenumber">Table A.8.</span> The rolling resistance is equal to the weight multiplied by the coefficient of rolling resistance, <em>C</em><sub>rr</sub>. The rolling resistance includes the force due to wheel flex, friction losses in the wheel bearings, shaking and vibration of both the roadbed and the vehicle (including energy absorbed by the vehicle’s shock absorbers), and sliding of the wheels on the road or rail. The coefficient varies with the quality of the road, with the material the wheel is made from, and with temperature. The numbers given here assume smooth roads. [<a href="http://tinyurl.com/2bhu35"><span class="websitetitle">2bhu35</span></a>]</p>
<section id="cars" class="level5">
<h5 class="anchored" data-anchor-id="cars"><em>Cars</em></h5>
<p>The coefficient of rolling resistance for a car is about 0.01. The effect of rolling resistance is just like perpetually driving up a hill with a slope of one in a hundred. So rolling friction is about 100 newtons per ton, independent of speed. You can confirm this by pushing a typical one-ton car along a flat road. Once you’ve got it moving, you’ll find you can keep it moving with one hand. (100 newtons is the weight of 100 apples.) So at a speed of 31 m/s (70 mph), the power required to overcome rolling resistance, for a one-ton vehicle, is</p>
<p><span class="math display">\[
\text{force} \times \text{velocity} = \left( \text{100\ newtons} \right) \times \left( \text{31\ m/s} \right) = \text{3100\ W;}
\]</span></p>
<p>which, allowing for an engine efficiency of 25%, requires 12 kW of power to go into the engine; whereas the power required to overcome drag was estimated above to be 80 kW. So, at high speed, about 15% of the power is required for rolling resistance.</p>
<p><img src="img/without-hot-air/figure321.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure A.9.</span> Simple theory of car fuel consumption (energy per distance) when driving at steady speed. Assumptions: the car’s engine uses energy with an efficiency of 0.25, whatever the speed; <em>c</em><span class="smallsub1"><sub>d</sub></span><em>A</em><span class="smallsub1"><sub>car</sub></span> = 1 m<sup>2</sup>; <em>m</em><span class="smallsub1"><sub>car</sub></span> = 1000 kg; and <em>C</em><span class="smallsub1"><sub>rr</sub></span> = 0.01.</p>
<p><img src="img/without-hot-air/figure322.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure A.10.</span> Simple theory of bike fuel consumption (energy per distance). Vertical axis is energy consumption in kWh per 100 km. Assumptions: the bike’s engine (that’s you!) uses energy with an efficiency of 0.25; <a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> the drag-area of the cyclist is 0.75 m<sup>2</sup>; the cyclist+bike’s mass is 90 kg; and <em>C</em><sub>rr</sub> = 0.005.</p>
<p><span class="figurenumber">Figure A.11.</span>Simple theory of train energy consumption, per passenger, for an eight-carriage train carrying 584 passengers. Vertical axis is energy consumption in kWh per 100 p-km. Assumptions: the train’s engine uses energy with an efficiency of 0.90; <em>c</em><sub>d</sub><em>A</em><sub>train</sub> = 11 m<sup>2</sup>; <em>m</em><span class="smallfont1"><sub>train</sub></span> = 400 000 kg; and <em>C</em><sub>rr</sub> = 0.002.</p>
<p><img src="img/without-hot-air/figure323.gif" class="img-fluid"></p>
<p>Figure A.9 shows the theory of fuel consumption (energy per unit distance) as a function of steady speed, when we add together the air resistance and rolling resistance.</p>
<p>The speed at which a car’s rolling resistance is equal to air resistance is given by</p>
<p><span class="math display">\[
C_{\text{rr}}m_{\text{c}}g = \frac{1}{2}\rho c_{\text{d}}Av^{2}
\]</span></p>
<p>that is,</p>
<p><span class="math display">\[
v = \sqrt{2\frac{C_{\text{rr}}m_{\text{c}}g}{\rho c_{\text{d}}A}} = \text{7\ m/s} = \text{16\ miles\ per\ hour.}
\]</span></p>
<p><img src="img/without-hot-air/figure257.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure A.13.</span> Powers of cars (kW) versus their top speeds (km/h). Both scales are logarithmic. The power increases as the third power of the speed. To go twice as fast requires eight times as much engine power. From Tennekes (1997).</p>
<p><img src="img/without-hot-air/figure256.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure A.12.</span> Current cars’ fuel consumptions do not vary as speed squared. Prius data from B.Z. Wilson; BMW data from Phil C. Stuart. The smooth curve shows what a speed-squared curve would look like, assuming a drag-area of 0.6 m<sup>2</sup>. <a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
</section>
<section id="bicycles" class="level5">
<h5 class="anchored" data-anchor-id="bicycles"><em>Bicycles</em></h5>
<p>For a bicycle (<em>m</em> = 90 kg, <em>A</em>= 0.75 m<sup>2</sup>), the transition from rolling-resistance-dominated cycling to air-resistance-dominated cycling takes place at a speed of about 12 km/h. At a steady speed of 20 km/h, cycling costs about <span class="mauve">2.2 kWh per 100 km</span>. By adopting an aerodynamic posture, you can reduce your drag area and cut the energy consumption down to about 1.6 kWh per 100 km.</p>
</section>
<section id="trains" class="level5">
<h5 class="anchored" data-anchor-id="trains"><em>Trains</em></h5>
<p>For an eight-carriage train as depicted in figure 20.4 (<em>m</em> = 400 000 kg, <em>A</em> = 11 m<sup>2</sup>), the speed above which air resistance is greater than rolling resistance is</p>
<p><span class="math display">\[
v = 33\text{~m/s} = \text{74\ miles\ per\ hour.}
\]</span></p>
<p>For a single-carriage train (<em>m</em> = 50 000 kg, <em>A</em> = 11 m<sup>2</sup>) , the speed above which air resistance is greater than rolling resistance is</p>
<p><span class="math display">\[
v = 12\text{~m/s} = \text{26\ miles\ per\ hour.}
\]</span></p>
</section>
</section>
<section id="dependence-of-power-on-speed" class="level3">
<h3 class="anchored" data-anchor-id="dependence-of-power-on-speed">Dependence of power on speed</h3>
<p>When I say that halving your driving speed should reduce fuel consumption (in miles per gallon) to <em>one quarter</em> of current levels, some people feel sceptical. They have a point: most cars’ engines have an optimum revolution rate, and the choice of gears of the car determines a range of speeds at which the optimum engine efficiency can be delivered. If my suggested experiment of halving the car’s speed takes the car out of this designed range of speeds, the consumption might not fall by as much as four-fold. My tacit assumption that the engine’s efficiency is the same at all speeds and all loads led to the conclusion that it’s always good (in terms of miles per gallon) to travel slower; but if the engine’s efficiency drops off at low speeds, then the most fuel-efficient speed might be at an intermediate speed that makes a compromise between going slow and keeping the engine efficient. For the BMW 318ti in figure A.12, for example, the optimum speed is about 60 km/h. But if society were to decide that car speeds should be reduced, there is nothing to stop engines and gears being redesigned so that the peak engine efficiency was found at the right speed. As further evidence that the power a car requires really does increase as the cube of speed, figure A.13 shows the engine power versus the top speeds of a range of cars. The line shows the relationship “power proportional to <em>v</em><sup>3</sup>.”</p>
</section>
<section id="electric-cars-is-range-a-problem" class="level3">
<h3 class="anchored" data-anchor-id="electric-cars-is-range-a-problem">Electric cars: is range a problem?</h3>
<p>People often say that the range of electric cars is not big enough. Electric car advocates say “no problem, we can just put in more batteries” – and that’s true, but we need to work out what effect the extra batteries have on the energy consumption. The answer depends sensitively on what energy density we assume the batteries deliver: for an energy density of 40 Wh/kg (typical of lead-acid batteries), we’ll see that it’s hard to push the range beyond 200 or 300 km; but for an energy density of 120 Wh/kg (typical of various lithium-based batteries), a range of 500 km is easily achievable.</p>
<p><img src="img/without-hot-air/figure258.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure A.14.</span> Theory of electric car range (horizontal axis) and transport cost (vertical axis) as a function of battery mass, for two battery technologies. A car with 500 kg of old batteries, with an energy density of 40 Wh per kg, has a range of 180 km. With the same weight of modern batteries, delivering 120 Wh per kg, an electric car can have a range of more than 500 km. Both cars would have an energy cost of about 13 kWh per 100 km. These numbers allow for a battery charging efficiency of 85%.</p>
<p>Let’s assume that the mass of the car and occupants is 740 kg, <em>without</em> any batteries. In due course we’ll add 100 kg, 200 kg, 500 kg, or perhaps 1000 kg of batteries. Let’s assume a typical speed of 50 km/h (30 mph); a drag-area of 0.8 m<sup>2</sup>; a rolling resistance of 0.01; a distance between stops of 500 m; an engine efficiency of 85%; and that during stops and starts, regenerative braking recovers half of the kinetic energy of the car. Charging up the car from the mains is assumed to be 85% efficient. Figure A.14 shows the transport cost of the car versus its range, as we vary the amount of battery on board. The upper curve shows the result for a battery whose energy density is 40 Wh/kg (old-style lead-acid batteries). The range is limited by a wall at about 500 km. To get close to this maximum range, we have to take along comically large batteries: for a range of 400 km, for example, 2000 kg of batteries are required, and the transport cost is above 25 kWh per 100 km. If we are content with a range of 180 km, however, we can get by with 500 kg of batteries. Things get much better when we switch to lighter lithium-ion batteries. At an energy density of 120 Wh/kg, electric cars with 500 kg of batteries can easily deliver a range of 500 km. The transport cost is predicted to be about 13 kWh per 100 km.</p>
<p>It thus seems to me that the range problem has been solved by the advent of modern <span id="batteries">batteries</span>. It would be nice to have even better batteries, but an energy density of 120 Wh per kg is already good enough, as long as we’re happy for the batteries in a car to weigh up to 500 kg. In practice I imagine most people would be content to have a range of 300 km, which can be delivered by 250 kg of batteries. If these batteries were divided into ten 25 kg chunks, separately unpluggable, then a car user could keep just four of the ten chunks on board when he’s doing regular commuting (100 kg gives a range of 140 km); and collect an extra six chunks from a battery-recharging station when he wants to make longer-range trips. During long-range trips, he would exchange his batteries for a fresh set at a battery-exchange station every 300 km or so.</p>
</section>
<section id="the-model-survived-the-cars-got-heavier" class="level2">
<h2 class="anchored" data-anchor-id="the-model-survived-the-cars-got-heavier">The model survived; the cars got heavier</h2>
<p><em>A section added in the 2026 revision.</em> This chapter’s model has two terms — the energy to shove air out of the way, which scales with frontal area and the square of speed, and the energy to accelerate a mass repeatedly, which scales with weight. Neither has been revised and neither will be. What is worth recording is what the model predicted about the eighteen years since, because it predicted them rather well.</p>
<p><strong>The electric car did what the model says it should.</strong> MacKay’s petrol car throws away three-quarters of its fuel as heat before any of it reaches the road. Remove that and the same vehicle, on the same journey against the same air, should need roughly a quarter to a fifth as much energy. Chapter 20 records the measurement: <strong>21 kWh per 100 km</strong> as a real-world European average across 342 electric cars, against this chapter’s <strong>80 kWh per 100 km</strong> petrol baseline. A factor of <strong>3.8</strong> — squarely inside the range the model predicts, and arrived at by measurement rather than by hope.</p>
<p><strong>And the model equally predicts why the gain has been partly eaten.</strong> Both terms punish size: air resistance is proportional to frontal area, and the stop-start term to mass. Over the same period vehicles got taller and heavier — <strong>sport-utility vehicles passed half of world car sales</strong>, and the average new car in Europe gained something like two hundred kilograms. A model with area and mass in it says efficiency gains will be spent on size unless something stops them, and that is what happened.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<p><strong>One term this chapter does not have.</strong> An electric car carries three to five hundred kilograms of battery, which the model taxes through the mass term while the thermal saving is not in the model at all. On balance the trade is overwhelmingly favourable — that is what 21 against 80 says — but it is why a heavy electric car is not four times better than a light petrol one.</p>
<p>The chapter’s real lesson is unchanged, and worth restating in an edition full of revised numbers: <strong>the two terms are physics and the rest is choice.</strong> A vehicle that is smaller, lower and lighter uses less energy whatever is under the bonnet, and no drivetrain rescues a badly shaped one.</p>
</section>
<section id="notes-and-further-reading" class="level2">
<h2 class="anchored" data-anchor-id="notes-and-further-reading">Notes and further reading</h2>
<p><img src="img/without-hot-air/figure259.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure A.15.</span> The Wartsila-Sulzer RTA96-C 14-cylinder two-stroke diesel engine. 27 m long and 13.5 m high. <a href="http://www.wartsila.com/"><span class="websitetitle">www.wartsila.com</span></a></p>
<p>Further reading: Gabrielli and von Kármán (1950).</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p><em>Regenerative brakes roughly halve the energy lost in braking</em>. Source: E4tech (2007).<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><em>Typical petrol engines are about 25% efficient.</em> Encarta [<a href="http://tinyurl.com/6by8x"><span class="websitetitle">6by8x</span></a>] says “The efficiencies of good modern Otto-cycle engines range between 20 and 25%.” The petrol engine of a Toyota Prius, famously one of the most efficient car engines, uses the Atkinson cycle instead of the Otto cycle; it has a peak power output of 52 kW and has an efficiency of 34% when delivering 10 kW [<a href="http://tinyurl.com/348whs"><span class="websitetitle">348whs</span></a>]. The most efficient diesel engine in the world is 52%-efficient, but it’s not suitable for cars as it weighs 2300 tons: the Wartsila–Sulzer RTA96-C turbocharged diesel engine (figure A.15) is intended for container ships and has a power output of 80 MW.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><em>Electric engines can be about 8 times lighter than petrol engines</em>. A 4-stroke petrol engine has a power-to-mass ratio of roughly 0.75 kW/kg. The best electric motors have an efficiency of 90% and a power-to-mass ratio of 6 kW/kg. So replacing a 75 kW petrol engine with a 75 kW electric motor saves 85 kg in weight. Sadly, the power to weight ratio of batteries is about 1 kW per kg, so what the electric vehicle gained on the motor, it loses on the batteries.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><em><span id="bike">The bike’s engine</span> uses energy with an efficiency of 0.25</em>. This and the other assumptions about cycling are confirmed by di Prampero et al.&nbsp;(1979). The drag-area of a cyclist in racing posture is <em>c</em><span class="smallfont"><sub>d</sub></span><em>A</em> = 0.3 m<sup>2</sup>. The rolling resistance of a cyclist on a high-quality racing cycle (total weight 73 kg) is 3.2 N.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p><em>Figure A.12</em>. Prius data from B. Z. Wilson [<a href="http://home.hiwaay.net/~bzwilson/prius/"><span class="websitetitle">home.hiwaay.net/~bzwilson/prius/</span></a>]. BMW data from Phil C. Stuart [<a href="http://www.randomuseless.info/318ti/economy.html"><span class="websitetitle">www.randomuseless.info/318ti/economy.html</span></a>].<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>The share of sport-utility vehicles in world car sales passed 50% in the mid-2020s on the International Energy Agency’s classification, up from roughly a fifth in 2010; that classification is broad and includes crossovers not much larger than the saloons they replaced, so it overstates the change in frontal area. European new-car kerb mass has risen roughly 10–15% since 2008 on manufacturer-reported figures, part of it safety and emissions equipment rather than size, and part of the recent rise battery mass in electrified models. Both are indicative, and the point turns on neither, since the model’s dependence on area and mass is not in dispute.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/chap32.html" class="pagination-link" aria-label="32 Saying yes">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">32 Saying yes</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/chapB.html" class="pagination-link" aria-label="B Wind II">
        <span class="nav-page-text"><span class="chapter-title">B Wind II</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>