<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>N Peak oil, peak gas, peak uranium – Sustainable Energy — Without the Hot Air</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/charts.html" rel="next">
<link href="../chapters/chapM.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1b15cd7dfe5d645daabccee077c4b062.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chapI.html">Part IV · Useful data</a></li><li class="breadcrumb-item"><a href="../chapters/chapN.html"><span class="chapter-title">N Peak oil, peak gas, peak uranium</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Sustainable Energy — Without the Hot Air</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About this edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I · Numbers, not adjectives</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap01.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1 Motivations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap02.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2 The balance sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap03.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3 Cars</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap04.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4 Wind</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap05.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5 Planes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap06.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6 Solar</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap07.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7 Heating and cooling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap08.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8 Hydroelectricity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap09.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">9 Light</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap10.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10 Offshore wind</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap11.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11 Gadgets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap11a.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11a The machines behind the screen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap12.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12 Wave</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap13.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13 Food and farming</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap14.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14 Tide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap15.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15 Stuff</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap16.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">16 Geothermal</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap17.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17 Public services</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap18.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18 Can we live on renewables?</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II · Making a difference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap19.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19 Every BIG helps</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap20.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20 Better transport</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap21.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">21 Smarter heating</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap22.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">22 Efficient electricity use</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap23.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">23 Sustainable fossil fuels?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap24.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">24 Nuclear?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap25.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">25 Living on other countries’ renewables?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap26.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">26 Fluctuations and storage</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap27.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">27 Five energy plans for Britain</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap28.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">28 Putting costs in perspective</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap-value-of-renewables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">28a The value of renewable energy as it scales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap29.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">29 What to do now</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap30.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">30 Energy plans for Europe, America, and the World</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap31.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">31 The last thing we should talk about</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap32.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">32 Saying yes</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III · Technical chapters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapA.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">A Cars II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapB.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">B Wind II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapC.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">C Planes II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapD.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">D Solar II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapE.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">E Heating II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapF.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">F Waves II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapG.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">G Tide II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapH.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">H Stuff II</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV · Useful data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapI.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">I Quick reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapJ.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">J Populations and areas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapK.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">K UK energy history</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapL.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">L The world in 2025</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapM.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">M Energy return on investment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapN.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">N Peak oil, peak gas, peak uranium</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/charts.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Charts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/bibliography.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bibliography</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/author.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The author</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/acknowledgments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Acknowledgments</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#what-the-reserves-actually-say" id="toc-what-the-reserves-actually-say" class="nav-link active" data-scroll-target="#what-the-reserves-actually-say">What the reserves actually say</a></li>
  <li><a href="#uranium-which-is-a-different-case" id="toc-uranium-which-is-a-different-case" class="nav-link" data-scroll-target="#uranium-which-is-a-different-case">Uranium, which is a different case</a></li>
  <li><a href="#forecasts-and-what-happened-to-them" id="toc-forecasts-and-what-happened-to-them" class="nav-link" data-scroll-target="#forecasts-and-what-happened-to-them">Forecasts, and what happened to them</a></li>
  <li><a href="#most-of-the-world-has-already-peaked" id="toc-most-of-the-world-has-already-peaked" class="nav-link" data-scroll-target="#most-of-the-world-has-already-peaked">Most of the world has already peaked</a>
  <ul class="collapse">
  <li><a href="#so-why-does-the-world-total-keep-setting-records" id="toc-so-why-does-the-world-total-keep-setting-records" class="nav-link" data-scroll-target="#so-why-does-the-world-total-keep-setting-records">So why does the world total keep setting records?</a></li>
  <li><a href="#the-peak-arrived-as-a-price-not-as-a-shortage" id="toc-the-peak-arrived-as-a-price-not-as-a-shortage" class="nav-link" data-scroll-target="#the-peak-arrived-as-a-price-not-as-a-shortage">The peak arrived as a price, not as a shortage</a></li>
  </ul></li>
  <li><a href="#exports-fall-faster-than-production" id="toc-exports-fall-faster-than-production" class="nav-link" data-scroll-target="#exports-fall-faster-than-production">Exports fall faster than production</a></li>
  <li><a href="#the-constraint-that-actually-binds" id="toc-the-constraint-that-actually-binds" class="nav-link" data-scroll-target="#the-constraint-that-actually-binds">The constraint that actually binds</a>
  <ul class="collapse">
  <li><a href="#supplied-the-demonstration" id="toc-supplied-the-demonstration" class="nav-link" data-scroll-target="#supplied-the-demonstration">2026 supplied the demonstration</a></li>
  <li><a href="#the-cargoes-nobody-counts" id="toc-the-cargoes-nobody-counts" class="nav-link" data-scroll-target="#the-cargoes-nobody-counts">The cargoes nobody counts</a></li>
  <li><a href="#who-is-preparing-for-it" id="toc-who-is-preparing-for-it" class="nav-link" data-scroll-target="#who-is-preparing-for-it">Who is preparing for it</a></li>
  </ul></li>
  <li><a href="#the-shape-of-the-answer" id="toc-the-shape-of-the-answer" class="nav-link" data-scroll-target="#the-shape-of-the-answer">The shape of the answer</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chapI.html">Part IV · Useful data</a></li><li class="breadcrumb-item"><a href="../chapters/chapN.html"><span class="chapter-title">N Peak oil, peak gas, peak uranium</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">N Peak oil, peak gas, peak uranium</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>A chapter added in the 2026 revision.</em> Chapter 23 redoes Jevons’ calculation for coal and finds that the answer is no longer interesting, because coal will be abandoned long before it is exhausted. This chapter does the same for the other three, and reaches a similar destination by a different road.</p>
<section id="what-the-reserves-actually-say" class="level2">
<h2 class="anchored" data-anchor-id="what-the-reserves-actually-say">What the reserves actually say</h2>
<p>M. King Hubbert proposed in 1956 that the production of a finite resource follows a curve which rises, peaks and declines, and that the peak can be predicted from the resource base. Applied to United States oil, the prediction was strikingly good. Applied to world oil it has been made, and missed, repeatedly for fifty years.</p>
<p>The simplest number is the reserves-to-production ratio: proved reserves divided by the current rate of extraction. Computed at 2025 rates from the Energy Institute’s figures:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Resource</th>
<th>Proved reserves</th>
<th>Annual production</th>
<th>R/P at current rates</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Oil</td>
<td>1 732 thousand million barrels</td>
<td>100.6 million barrels/day</td>
<td><strong>47 years</strong></td>
</tr>
<tr class="even">
<td>Gas</td>
<td>188.1 trillion m<sup>3</sup></td>
<td>4 186 billion m<sup>3</sup></td>
<td><strong>45 years</strong></td>
</tr>
<tr class="odd">
<td>Coal</td>
<td>1 074 Gt</td>
<td>8.06 Gt</td>
<td><strong>133 years</strong></td>
</tr>
<tr class="even">
<td>Uranium</td>
<td>5.93 Mt (below $130/kg)</td>
<td>~67 000 t of demand</td>
<td><strong>~90 years</strong></td>
</tr>
</tbody>
</table>
<p>Two warnings about that table, and they point in opposite directions.</p>
<p><strong>R/P is not a countdown.</strong> It has hovered around forty to fifty years for oil for most of the last half-century, not because the estimate keeps being wrong but because “proved reserves” is an economic category rather than a geological one: it counts what is known, drilled and worth extracting at present prices. Higher prices and better technology convert resource into reserve, which is why the ratio keeps regenerating. The Energy Institute currently notes that its own reserves methodology is under review, and the figures above are still those assessed at end-2020.</p>
<p><strong>But regeneration is not free</strong>, and chapter M is where the cost shows. Each conversion of resource into reserve tends to bring in something harder to get: deeper water, tighter rock, poorer grade. The barrels do not run out; the cheap barrels do, and the EROI of the marginal barrel falls. That is the honest form of the peak-oil intuition, and it survives even though the specific date predictions did not.</p>
</section>
<section id="uranium-which-is-a-different-case" class="level2">
<h2 class="anchored" data-anchor-id="uranium-which-is-a-different-case">Uranium, which is a different case</h2>
<p>Uranium deserves separate treatment because the resource question is genuinely open in a way oil’s is not, and because the arithmetic is unusually sensitive to what one assumes about reactors.</p>
<p>World production reached <strong>60 213 tonnes of uranium in 2024</strong>, covering about 90% of reactor requirements — the balance coming from stockpiles and from reprocessed material. Identified resources recoverable below $130/kg stand at <strong>5.93 million tonnes</strong>, rising to 7.94 million tonnes if one accepts $260/kg. At present consumption that is roughly ninety years, which is a short number for an industry that plans in half-centuries.</p>
<p>Three considerations pull it in different directions.</p>
<p><strong>The resource figures are investment documents.</strong> The OECD Nuclear Energy Agency’s Red Book, which is the source everyone uses, reports resources by extraction cost and is aimed at least as much at investors as at scientists. Its categories descend from Reasonably Assured Resources through two grades of Estimated Additional Resources to Speculative Resources, and the totals move for administrative reasons — the estimate of one category fell by more than half in 2013 because the United States stopped reporting it.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> A ninety-year figure derived from such a series should not be read as a measurement of what is in the ground.</p>
<p><strong>Price changes the answer enormously.</strong> Uranium is a small fraction of the cost of nuclear electricity, perhaps a few per cent, so the fuel price can rise several-fold without making the electricity notably dearer. That is not true of oil, and it means the uranium resource base is far more elastic than the oil one. At the extreme, seawater contains about 3 parts per billion, which amounts to something like 4.5 billion tonnes; extraction has been demonstrated with adsorbent fabrics and the capacity of those materials has improved severalfold since 2011, though the cost remains far above mining.</p>
<p><strong>And breeding changes it beyond recognition.</strong> A fast breeder converts U-238, which is 99.3% of natural uranium and useless in a conventional reactor, into fissile plutonium. Doing so extracts perhaps fifty times more energy from the same ore, which turns ninety years into millennia and makes the resource question moot. The catch is that breeders have been fifteen years away for sixty years: the programmes have been dogged by cost, delay, sodium fires and closure. Thorium offers a comparable escape by a different route, with comparable uncertainty about delivery.</p>
<p>So the honest position on uranium is that the resource is adequate for the current fleet for about as long as anyone is planning, that it is inadequate for a very large expansion of conventional reactors on present resource estimates, and that both of those statements are dwarfed by the question of whether breeding ever works at scale.</p>
</section>
<section id="forecasts-and-what-happened-to-them" class="level2">
<h2 class="anchored" data-anchor-id="forecasts-and-what-happened-to-them">Forecasts, and what happened to them</h2>
<p>Uranium is unusually good ground for testing the peak method, because two quantitative forecasts were made with dates and error bars and both can now be checked.</p>
<p><strong>The IAEA’s, from 2001.</strong> <em>Analysis of Uranium Supply to 2050</em> projected that secondary supplies — military stockpiles, reprocessed material, inventory — which met about 42% of demand in 2000, would dwindle to a few per cent, and that mined production would therefore have to rise to cover <strong>86 to 92% of demand by 2025</strong>. In 2024 mining covered <strong>90%</strong>. A twenty-four-year-ahead projection landing inside its own range is a better result than this literature usually manages, and it is worth recording that the institutional forecast was the accurate one.</p>
<p><strong>Michael Dittmar’s, from 2013.</strong> “The end of cheap uranium” applied a depletion model — that only 50–70% of a deposit is ever recovered, and that modern mines work a deposit out in about ten years — to every operating and planned mine. It predicted a <strong>global peak of at most 58 ± 4 kt around 2015</strong>, a decline of at least 0.5 kt a year thereafter, <strong>at most 54 ± 5 kt by 2025</strong> and 41 ± 5 kt by 2030. Since demand was then about 68 kt, the paper concluded that shortages were unavoidable, recommended a worldwide nuclear phase-out, and warned that failing to organise one would bring “brownouts, blackouts, and worse”.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>Here is what production actually did:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th>Year</th>
<th>2015</th>
<th>2016</th>
<th>2017</th>
<th>2018</th>
<th>2019</th>
<th>2020</th>
<th>2021</th>
<th>2022</th>
<th>2023</th>
<th>2024</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>kt U</td>
<td>60.3</td>
<td><strong>63.2</strong></td>
<td>60.5</td>
<td>54.2</td>
<td>54.7</td>
<td><strong>47.7</strong></td>
<td>47.8</td>
<td>49.6</td>
<td>54.4</td>
<td><strong>60.2</strong></td>
</tr>
</tbody>
</table>
<p>He got the timing of the peak right: 2016, near enough to “around 2015”. He got the direction right too — production fell by a quarter over the following four years. And then it recovered by 26% and is now above the maximum he allowed for 2025.</p>
<p><strong>The reason he was wrong is the interesting part.</strong> The fall from 2016 to 2020 was not depletion. It was Kazatomprom and Cameco deliberately curtailing output because the post-Fukushima price collapse had made mining unprofitable — supply discipline, of the kind any commodity producer practises. When prices recovered, so did production, from mines his model had written off. A depletion model has no term for a company choosing to mine less this year and more later, and so it fitted an economic cycle and mistook it for geology.</p>
<p>The catastrophe did not arrive either. The gap he identified was real — mining covered only 74% of requirements in 2020 — but it was bridged by exactly the secondary supplies the IAEA had been tracking, rather than by blackouts.</p>
<p>This is the same lesson as chapter 23’s, arrived at from the other direction. Predicting when a resource peaks means predicting the behaviour of the people who own it, and that is a harder problem than estimating what is in the ground. Both papers did competent arithmetic. The one that was right about the numbers was the one that modelled the market rather than the rock.</p>
<p><strong>The same mistake was available on oil, and was made.</strong> In October 2021 the Swedish blog <em>Cornucopia?</em> asked whether peak oil had already happened in 2018 or 2019. The evidence was a monthly all-liquids series from the American EIA: a high of <strong>102.4 mb/d in October 2018</strong>, an almost identical 102.0 in November 2019, and no recovery to either level in the two years since. A French report was cited as also placing the peak in 2019. The conclusion drawn was a permanent energy and economic crisis — growth stalls without rising energy use, prices turn volatile, poor countries suffer first, and Sweden must choose between a large nuclear build and a managed decline.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p>Here is what production and consumption actually did:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Million barrels per day</th>
<th>2018</th>
<th>2019</th>
<th>2020</th>
<th>2021</th>
<th>2024</th>
<th>2025</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Oil production</td>
<td>95.0</td>
<td>95.1</td>
<td>88.9</td>
<td>90.3</td>
<td>97.2</td>
<td><strong>100.6</strong></td>
</tr>
<tr class="even">
<td>Total liquids consumption</td>
<td>101.0</td>
<td>101.4</td>
<td>92.4</td>
<td>97.8</td>
<td>105.1</td>
<td><strong>106.5</strong></td>
</tr>
</tbody>
</table>
<p>The two rows are on different bases, and the difference matters for the test. The EIA all-liquids series the blog used includes biofuels and refinery processing gain, which the Energy Institute’s “oil production” line excludes; total liquids consumption is the comparable measure. On that measure, the <strong>2025 annual average of 106.5 exceeds the blog’s monthly high-water mark by four million barrels a day</strong>, and 2024 had already passed it. On the narrower production basis, 2025 stands 5.5 mb/d above 2019.</p>
<p>The reason is again the interesting part, and it is the same reason. The trough the argument rested on was the pandemic together with the OPEC+ agreement of April 2020 to withdraw <strong>9.7 mb/d</strong> — the largest production cut ever agreed. The piece was written in October 2021 while those cuts were still being unwound on a published schedule. A cartel restoring barrels it had voluntarily withheld looks, in the monthly data, exactly like a resource failing to recover. Dittmar mistook Kazatomprom and Cameco for geology; this mistook OPEC+ for geology.</p>
<p>Two qualifications are owed. The piece hedged explicitly, allowing that it might be wrong, and it is a blog essay rather than a study. But the failure mode is worth naming because it is directional: <strong>both of the forecasts that missed were pessimistic about supply</strong>, and neither anticipated that within five years the binding constraint would be who controls a strait rather than what is left in the rock. That is the subject of the rest of this chapter.</p>
</section>
<section id="most-of-the-world-has-already-peaked" class="level2">
<h2 class="anchored" data-anchor-id="most-of-the-world-has-already-peaked">Most of the world has already peaked</h2>
<p>The argument so far has treated peak oil as a question about the future. For most of the world it is not. It is a matter of record, and the record is worth putting on the page, because it is both stronger evidence for the peak idea than anything its advocates usually cite and the reason the global forecast keeps failing.</p>
<p>Take every country the Energy Institute tracks, find the year each produced most oil, and ask what it produces now as a share of that maximum. <strong>Twenty-five of the thirty-four significant producers are past their own peak.</strong><a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/without-hot-air/fig-peak-oil-by-country.svg" class="img-fluid figure-img"></p>
<figcaption>Peak oil country by country: twenty-five of thirty-four significant producers are past their own maximum, from Venezuela at 29 percent of its 1970 peak and the United Kingdom at 23 percent of its 1999 peak, to eight countries still at their maximum in 2025.</figcaption>
</figure>
</div>
<p><span class="figurenumber">Figure N.1.</span> Peak oil, country by country. Each bar is 2025 production as a share of that country’s own record year, shown in brackets. Energy Institute <em>Statistical Review of World Energy</em> 2026.</p>
<p>Some of these are not gentle declines. <strong>Venezuela peaked in 1970 and produces 29% of what it did then. The United Kingdom peaked in 1999 and produces 23%</strong> — a three-quarters decline inside a working lifetime, in a wealthy country with full access to capital and technology. Indonesia peaked in 1977 at 36%, Libya in 1970 at 42%, Mexico in 2004 at 46%, Norway in 2001 at 60%. Kuwait peaked in 1972, Iran in 1974.</p>
<p>Gas tells the same story more quietly: <strong>25 of 44 producers are past peak</strong>, and the Netherlands, whose Groningen field defined European gas, is at <strong>9% of its 1977 maximum</strong>.</p>
<p>This is the part of the peak-oil case that was simply correct, and the popular statements of it were more careful than they are usually given credit for. A Swedish summary from 2012 put the central claim as <em>“the majority of all countries that have ever produced oil have peaked, and ever fewer countries account for an ever larger share of oil production”</em> — which is what the chart above shows, fourteen years on. It worked through sixteen charted cases — Indonesia, Mexico, Argentina, Ecuador, Venezuela, Denmark, Norway, Iraq, Kuwait, Algeria, Libya, Nigeria, Australia, Brunei, Malaysia and New Zealand — arguing in each that rising prices had failed to lift production back to its former level.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<p>Two features of that piece are worth recording, because they are what an argument made honestly looks like. It charted Iraq but set it aside explicitly as <em>not</em> an example of natural peak oil, the decline there being war rather than geology. And it allowed in advance that <em>“it is not certain that all the examples below have peaked permanently”</em>, since a country may reach an earlier top again.</p>
<section id="so-why-does-the-world-total-keep-setting-records" class="level3">
<h3 class="anchored" data-anchor-id="so-why-does-the-world-total-keep-setting-records">So why does the world total keep setting records?</h3>
<p>Because peaks are not synchronised, and a handful of new provinces have more than covered the losses. Eight producers reached their maximum in <strong>2025 itself</strong>: the United States, Canada, China, the United Arab Emirates, Brazil, Kazakhstan, Argentina and Guyana. Guyana produced no oil at all a decade ago and now produces <strong>716 000 barrels a day</strong>.</p>
<p>Argentina is the instructive one, and precisely the case that 2012 caveat left room for. It was declining when the piece was written. Vaca Muerta shale reversed it, and Argentina’s 2025 output is its highest ever. A country can come back off its peak if the rock beneath it turns out to hold a second, different resource that a new technique can reach.</p>
<p>That is the mechanism the depletion models keep missing, and it is the same one chapter 23’s argument turns on. <strong>The world is not one oil field.</strong> It is a portfolio, and the portfolio has been rebalanced twice in twenty years — once by American shale, once by the Atlantic pre-salt and Guyana. Each time, the aggregate curve stayed flat or rose while three-quarters of its constituents fell.</p>
</section>
<section id="the-peak-arrived-as-a-price-not-as-a-shortage" class="level3">
<h3 class="anchored" data-anchor-id="the-peak-arrived-as-a-price-not-as-a-shortage">The peak arrived as a price, not as a shortage</h3>
<p>If the good rock is being used up, the effect should show somewhere even when volumes hold. It shows in what a barrel costs to get out.</p>
<p>The average breakeven for a new non-OPEC project is now about <strong>$47 (£37) a barrel of Brent, up 5% in a single year</strong>. American shale, the resource that broke the last two peak forecasts, breaks even near <strong>$70 WTI today and is projected toward $95 by the mid-2030s</strong> — not because anything is running out in the absolute sense, but because the Permian’s best acreage is drilled first and the Eagle Ford and Bakken are already working through their core inventory. Onshore Middle East production remains far cheaper, which is precisely why the marginal barrel migrates back toward the countries that hold it.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<p>That is the honest form of the peak-oil claim, and it is worth stating plainly because it is neither the catastrophe its advocates predicted nor the non-event its critics claimed. <strong>Geology did not stop supply. It raised the price of the marginal barrel, and it moved the ownership of the cheap ones.</strong> The first of those is a tax on everyone. The second is the subject of the rest of this chapter.</p>
</section>
</section>
<section id="exports-fall-faster-than-production" class="level2">
<h2 class="anchored" data-anchor-id="exports-fall-faster-than-production">Exports fall faster than production</h2>
<p>There is a piece of arithmetic that changes the shape of every number above, and it is not in the reserves tables because it is not about geology.</p>
<p>An exporting country consumes some of what it produces. When its production begins to decline, its domestic consumption usually does not — it is a country getting richer, buying cars. <strong>Exports are the difference between two quantities moving in opposite directions, and a difference declines much faster than either term.</strong></p>
<p>Jeffrey Brown set this out as the <strong>Export Land Model</strong>. Take a country at its production peak that consumes half of what it produces, then let production fall 5% a year while domestic consumption rises 2.5% a year. Its exports do not decline by 5% a year. They reach <strong>zero in nine years</strong>.</p>
<p>Indonesia did it faster. From its 1997 peak, production fell 3.9% a year — gentler than the model — while domestic consumption grew 4.1%. Net exports reached zero in <strong>seven years</strong>, and a founding member of OPEC became an oil importer.</p>
<p>The consequence for an importing country like Britain is that the reserves-to-production ratios in the first table are the wrong numbers to be reassured by. What reaches the market is not world production but world <em>net exports</em>, and that quantity can be falling while production is flat. Brown and Foucher argued that global net exports had already peaked in 2006, which is a much sharper claim than peak production and rather harder to dismiss.</p>
<p>The same argument does not transfer cleanly to uranium, and it is worth saying why. Kazakhstan does not consume its own uranium in any quantity; there is no domestic-demand term to eat the exports. Uranium’s version of the problem is political rather than arithmetical, and that is the subject of the next section.</p>
</section>
<section id="the-constraint-that-actually-binds" class="level2">
<h2 class="anchored" data-anchor-id="the-constraint-that-actually-binds">The constraint that actually binds</h2>
<p>Which brings us to the thing this chapter exists to say, and it is not about geology.</p>
<p><strong>Uranium mining is extraordinarily concentrated.</strong> Of the 60 213 tonnes produced in 2024:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Country</th>
<th>Tonnes U</th>
<th>Share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Kazakhstan</td>
<td>23 270</td>
<td><strong>39%</strong></td>
</tr>
<tr class="even">
<td>Canada</td>
<td>14 309</td>
<td>24%</td>
</tr>
<tr class="odd">
<td>Namibia</td>
<td>7 333</td>
<td>12%</td>
</tr>
<tr class="even">
<td>Australia</td>
<td>4 598</td>
<td>8%</td>
</tr>
<tr class="odd">
<td>Uzbekistan</td>
<td>4 000</td>
<td>7%</td>
</tr>
<tr class="even">
<td>Russia</td>
<td>2 738</td>
<td>5%</td>
</tr>
<tr class="odd">
<td>Niger</td>
<td>962</td>
<td>2%</td>
</tr>
</tbody>
</table>
<p>Three countries supply about three-quarters of it. <strong>Kazakhstan alone supplies more than a third</strong>, and Kazakhstan, Uzbekistan and Russia together supply over half. Kazakh production is substantially owned or part-owned through Russian and Chinese joint ventures, and much of it has historically moved to market through Russian territory and Russian ports.</p>
<p>Set that beside chapter L’s finding that China refines over 90% of the world’s graphite and rare earths, and chapter 15’s that six Chinese firms make 69% of the world’s batteries, and a pattern emerges that MacKay’s method is structurally blind to. His question is whether the physics permits a thing. These chapters keep arriving at a different question: whether the supply chain for it runs through countries you would rather not depend on.</p>
<p>Nuclear power is often argued for on energy-security grounds — a fuel you can stockpile for years, unlike gas. That argument is sound and it is worth noticing that it is an argument about <em>storage</em>, not about <em>sourcing</em>. On sourcing, a British or European nuclear programme is more exposed to Central Asian politics than a gas plant is to Norwegian.</p>
<section id="supplied-the-demonstration" class="level3">
<h3 class="anchored" data-anchor-id="supplied-the-demonstration">2026 supplied the demonstration</h3>
<p>While this edition was being written, the argument stopped being hypothetical twice in one year.</p>
<p>In <strong>January 2026</strong> a United States military operation removed Nicolás Maduro from Venezuela — a country sitting on some of the largest proved oil reserves in the world. The market barely moved, for the instructive reason that Venezuela had already ceased to matter as a supplier: production under a million barrels a day, exports around half a million, against world consumption above a hundred million. A country can hold enormous reserves and be irrelevant to supply.</p>
<p>In <strong>February 2026</strong> the more serious case arrived, and it has not ended. United States and Israeli strikes on Iran on 28 February were followed on 2 March by the closure of the <strong>Strait of Hormuz</strong>, through which roughly a fifth of world oil trade passes. The International Energy Agency described it as the largest supply disruption in the history of the oil market.</p>
<p><strong>It is still closed as this chapter is written</strong>, more than five months on. Iran declared the strait open on 17 April and the Revolutionary Guard reversed the announcement the following day. A memorandum of understanding on 17 June lifted the American naval blockade of Iranian <em>ports</em> — which is a different thing, and let Iran itself export some 40 million barrels — but the waterway has not returned to normal use. Roughly <strong>ten ships transited on 23 July, against about eighty-eight a day before the war</strong>, some of them running with their transponders off. An LNG carrier with Qatari cargo was struck by a cruise missile crossing the strait on 1 August.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<p>Note what the numbers did and did not do. A fifth of world oil trade stopped moving and the oil price rose by roughly a tenth at first, not by a multiple, because there was a glut to absorb it; it went above $100 later, once the ceasefire lapsed. Reserves in the ground did not change at all, and neither did any reserves-to-production ratio. What changed was whether a ship could sail through a strait.</p>
</section>
<section id="the-cargoes-nobody-counts" class="level3">
<h3 class="anchored" data-anchor-id="the-cargoes-nobody-counts">The cargoes nobody counts</h3>
<p>Oil dominates the reporting, and it is not where the sharpest losses fell. Two other things go through Hormuz in concentrations that make the oil share look comfortable.</p>
<p><strong>Helium.</strong> Qatar supplies about a third of the world’s helium, as a by-product of its gas processing at Ras Laffan — facilities damaged in the strikes. The distributor Airgas declared force majeure and restricted customers to half their contracted volumes. South Korea, which took nearly two-thirds of its helium from Qatar, has no domestic alternative. Helium is not an energy carrier and gets no chapter in this book, but semiconductor fabrication, MRI scanners and cryogenics do not have a substitute for it at any price.</p>
<p><strong>Fertiliser.</strong> Up to <strong>30% of internationally traded fertiliser</strong> — around 16 million tonnes a year of nitrogen, phosphate and sulphur products — moves through the strait. The Gulf supplies 30–35% of world urea exports and 20–30% of ammonia; Qatar’s QAFCO complex alone is about 14% of global urea trade.</p>
<p>That second one belongs in this book more than the oil does, and chapter 13 explains why. Nitrogen fertiliser is essentially natural gas turned into food by the Haber–Bosch process: it is an energy carrier wearing a different label, and the world’s ability to feed itself runs through it. A disruption that takes a tenth off the oil price and a third off the traded fertiliser supply has done far more damage through the second channel, and it will show up as a harvest rather than as a pump price.</p>
</section>
<section id="who-is-preparing-for-it" class="level3">
<h3 class="anchored" data-anchor-id="who-is-preparing-for-it">Who is preparing for it</h3>
<p>The two largest economies have drawn opposite conclusions, and their inventories say so plainly.</p>
<p>The <strong>United States</strong> holds its Strategic Petroleum Reserve at about <strong>316 million barrels</strong> against an authorised capacity of 714 million — the lowest level since 1983, after some 352 million barrels were withdrawn over four years, including a 172-million-barrel release authorised in March 2026 during the Iran war.</p>
<p><strong>China</strong> now holds the largest emergency stocks in the world: total crude inventories estimated near <strong>1.3 billion barrels</strong>, of which perhaps 400–500 million is the strategic reserve proper, and it is still building — at least 169 million barrels of new capacity across eleven sites, with a stated intention to take state reserves past a billion barrels, framed explicitly as three months of net import cover.</p>
<p>So one country has spent its buffer and the other has been accumulating one. Whatever else that is, it is a judgement about the next twenty years being made in physical barrels rather than in forecasts, and it is the clearest available evidence of what large states actually expect. MacKay’s arithmetic can tell you how much energy a country needs. It cannot tell you that China has been quietly buying three months of insurance while America sold its own.</p>
<p><strong>There is a third response, and it is the only structural one.</strong> Stockpiles buy months. The alternative is to need less of the stuff, and the region most exposed to Hormuz is the one moving fastest. Asia holds <strong>54% of the world’s population and 2% of its oil reserves and 8% of its gas</strong>; it imported about <strong>$1.1 trillion of fossil fuel in 2024</strong> — $699bn of oil, $184bn of coal, $176bn of gas — at over <strong>3% of regional GDP</strong>. For Thailand the bill is near 7.5% of GDP, and for Taiwan, South Korea, Singapore, Viet Nam, Pakistan and the Philippines it is between four and six.</p>
<p>The trajectory is the part that matters. <strong>Southeast Asia was a net oil and gas exporter in 1990, at about 75% of its own demand in surplus, and by 2023 was importing 30%.</strong> Greater China went from roughly 40% import-dependent to 72% over the same period, South Asia from 55% to 75%, and Northeast Asia has been at essentially 100% throughout. Growth was bought with imports.</p>
<p>So the electrification is not principally a climate policy, and reading it as one misses what it is for. <strong>By 2023, 84% of Asia had overtaken the United States on the share of final energy delivered as electricity</strong>, and by 2025, 77% was ahead of it on electric share of new car sales — Nepal above 60%, China above 50%. Nepal is the case that shows the mechanism cleanly: no oil of its own, a great deal of water, and the highest electric share in Asia. Electrifying transport is import substitution that happens to reduce emissions.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
</section>
</section>
<section id="the-shape-of-the-answer" class="level2">
<h2 class="anchored" data-anchor-id="the-shape-of-the-answer">The shape of the answer</h2>
<p>Put the four resources together and the same conclusion emerges as in chapter 23. There is enough of all of them for the period anyone is planning over. Oil and gas have about half a century of proved reserves and have had about half a century for decades; coal has more than a century; uranium has roughly ninety years, or effectively unlimited if breeders ever work.</p>
<p>None of them will be exhausted. Each will instead be abandoned, priced out, restricted, or — the possibility this chapter adds — become unavailable for reasons that have nothing to do with what is in the ground.</p>
<p>That last is the one worth carrying away, because it is the one this book’s method is least equipped to see. A resource table answers <em>how much is left</em>. The Export Land Model answers <em>how much of it reaches the market</em>, which is a smaller and faster-moving quantity. Hormuz answers <em>whether it can physically get here this month</em>. And the strategic reserves answer the question underneath all of them: whether you have the money, the ships and the storage to be the customer who gets served.</p>
<p>The honest summary is the one in the question this chapter was asked to address. It is not only what is left. It is who has it, and whether they will sell it to us — and the answer to that is probably yes, at a price, until the week it is no.</p>
<p>Running out was the wrong thing to worry about. It was, however, a very good way of getting people to think about the numbers, which is what this book is for.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>The Red Book categories and the reporting discontinuities are set out in Dylan Bedford, “Peak Uranium and the Sustainability of Nuclear Energy”, Physics 241 coursework, Stanford University, 2018: <a href="http://large.stanford.edu/courses/2017/ph241/bedford1/" class="uri">http://large.stanford.edu/courses/2017/ph241/bedford1/</a>. This is student coursework rather than peer-reviewed work and is cited here for its clear summary of the Red Book’s structure and caveats, not as an authority on resource estimates. Production and resource figures above are from the World Nuclear Association’s compilations of Red Book and company data; oil, gas and coal reserves and production are from the Energy Institute’s <em>Statistical Review of World Energy</em> 2026, with reserves as assessed at end-2020 and R/P ratios recomputed here at 2025 production rates.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Michael Dittmar, “The end of cheap uranium”, <em>Science of the Total Environment</em> 461–462 (2013) 792–798, <a href="https://doi.org/10.1016/j.scitotenv.2013.04.035" class="uri">https://doi.org/10.1016/j.scitotenv.2013.04.035</a>. The IAEA projection is <em>Analysis of Uranium Supply to 2050</em>, IAEA, 2001. Production figures are the World Nuclear Association’s compilation: 60 342 t (2015), 63 207 (2016), 60 462 (2017), 54 154 (2018), 54 742 (2019), 47 731 (2020), 47 805 (2021), 49 614 (2022), 54 433 (2023), 60 213 (2024). Mining covered 74% of reactor requirements in 2020 and 90% in 2024.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Lars Wilderäng, “Inträffade peak oil 2018 eller 2019 och vad innebär det?”, <em>Cornucopia?</em>, October 2021: <a href="https://cornucopia.se/2021/10/intraffade-peak-oil-2018-eller-2019-och/" class="uri">https://cornucopia.se/2021/10/intraffade-peak-oil-2018-eller-2019-och/</a>. As with the latitude argument cited in chapter L, this is a blog essay arguing a position rather than a study, and is examined here as a well-documented instance of the reasoning rather than as evidence for it. The monthly all-liquids highs quoted are the EIA’s. Production and consumption figures in the table are from the Energy Institute’s <em>Statistical Review of World Energy</em> 2026: world oil production 95 001, 95 127, 88 943, 90 315, 97 156 and 100 590 thousand barrels daily for 2018, 2019, 2020, 2021, 2024 and 2025, and total world liquids consumption 101 022, 101 388, 92 369, 97 814, 105 133 and 106 519 for the same years. The Review notes that differences between world consumption and world production statistics are accounted for by stock changes and by consumption of non-petroleum additives and substitute fuels. The April 2020 OPEC+ cut of 9.7 mb/d is from the OPEC secretariat’s communiqué of 12 April 2020.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Computed from the Energy Institute’s <em>Statistical Review of World Energy</em> 2026 by the <code>chapterN</code> step in this edition’s data-refresh script: for each producer, the year of maximum output over the full record (oil from 1965, gas from 1970) and 2025 output as a share of it. Aggregates and regional groupings are excluded, as are producers below 200 thousand barrels a day of oil or 5 bcm of gas in 2025, which leaves 34 oil producers and 44 gas producers. Two caveats. A country counts as “past peak” here if its maximum fell in 2020 or earlier, so a producer whose record year was 2021–2023 is not counted either way; and a single year’s output can be depressed by war, sanctions or quota rather than by geology — Venezuela, Libya and Iran are all cases where politics, not rock, explains much of the decline. The measure shows what has happened, not why.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Lars Wilderäng, “Peak oil 101”, <em>Cornucopia?</em>, March 2012: <a href="https://cornucopia.se/2012/03/peak-oil-101-for-moderated/" class="uri">https://cornucopia.se/2012/03/peak-oil-101-for-moderated/</a>. Quotations are translated from the Swedish. As with the other citations to this blog in chapters L and N, it is an essay arguing a position rather than a study; it is used here because it stated a checkable claim and charted sixteen named cases, which is more than most statements of the argument do. The sixteen are read from the article’s own charts; Mexico, Australia, Brunei, Malaysia and New Zealand are charted without an accompanying sentence. Note that its peak years are not always the Energy Institute’s: it dates Nigeria to 2005 and Kuwait and Libya to 2008, where the full record used in figure N.1 gives 2010, 1972 and 1970 respectively — the piece is generally reading a recent window of crude production rather than an all-time maximum, so the two agree on direction and differ on dates. Its wider prediction, that rising prices would fail to bring on new supply, was wrong in aggregate: American shale and the Guyana–Brazil offshore arrived within the decade, and the text above says so.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Rystad Energy’s upstream cost analysis puts the average breakeven of a new non-OPEC oil project at about $47 per barrel of Brent, a 5% rise in a year, with North American shale averaging around $45 and onshore Middle East well below both. Enverus Intelligence Research projects US shale breakevens rising from roughly $70 per barrel WTI in 2025 toward $95 by the mid-2030s as core Permian, Eagle Ford and Bakken acreage is consumed. These are commercial estimates on differing bases — breakeven is sensitive to whether it includes full-cycle or half-cycle costs, and to the assumed hurdle rate — so the direction is more reliable than any single figure.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>The Venezuela intervention of January 2026; the strikes on Iran of 28 February 2026 and the closure of the Strait of Hormuz from 2 March, with the IEA’s characterisation of it as the largest supply disruption in the history of the oil market. The strait remained closed to normal commercial traffic at the beginning of August 2026: about ten transits on 23 July against a pre-war norm near eighty-eight a day, and an LNG carrier struck by a cruise missile on 1 August. The memorandum of understanding of 17 June ended the American naval blockade of Iranian ports, which is distinct from the strait reopening. Helium: Qatar about a third of world supply, damage at Ras Laffan, Airgas force majeure at 50% of contracted volumes, South Korea sourcing 64.7% of its helium from Qatar in 2025. Fertiliser: Rystad Energy and WTO trade analyses put up to 30% of traded fertiliser products, some 16 Mt/year, through the strait, with the Gulf at 30–35% of urea exports and QAFCO alone about 14% of global urea trade. Strategic reserve figures: US Department of Energy and EIA for the SPR, including the 172-million-barrel release authorised in March 2026; Chinese inventory estimates are third-party and EIA-derived, since China does not publish strategic reserve volumes, and the split between strategic and commercial stocks is uncertain. These are recent and contested events and the figures should be expected to move.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Figures are from Ember’s <em>Electric Asia: How Asia is leading the electric age</em>, 11 June 2026, drawing on IEA, IRENA, UN Comtrade, World Bank and Ember’s own analysis. Coverage: 54% of world population against 2% of oil and 8% of gas reserves; fossil imports of about $1.1 trillion in 2024, made up of $699bn oil, $184bn coal and $176bn gas, at over 3% of the region’s GDP, with the per-country bill running from about 7.5% of GDP for Thailand through four to six per cent for Taiwan, South Korea, Singapore, Viet Nam, Pakistan and the Philippines, and Malaysia and Myanmar near zero because they export; net oil and gas imports as a share of demand moving between 1990 and 2023 from about −75% to +30% for Southeast Asia, 40% to 72% for Greater China and 55% to 75% for South Asia, with Northeast Asia near 100% throughout; the crossover at which Asia passed the West on electrification in 2016, at roughly a quarter of Western income per head, with Asian electrification since growing about five times faster; roughly 26% of final energy delivered as electricity against 21% in the West; 84% of Asia ahead of the United States on electrification in 2023 and 77% ahead on electric share of new car sales in 2025, with Nepal above 60% and China above 50%, and with Brunei and Malaysia among the economies named as having passed the United States on electrification; about three quarters of world electricity demand growth since 2000; some 60% of installed solar and wind, and manufacturing shares of over 95% of solar panels, 85% of batteries and 75% of wind turbines; and solar and wind resources sufficient for at least fourteen times regional energy demand. <strong>Four things to hold in mind about this source.</strong> Ember is an energy think-tank that advocates for electrification, and the deck is a campaigning document as well as an analytical one — the figures are sourced and checkable, the framing is not neutral, and the phrase “the Asian century” is theirs rather than this book’s. The 84% and 77% shares are given by Ember as “share of Asia”, and <strong>the deck does not state whether the denominator is population, countries or energy demand</strong>; they are quoted here as reported and should not be read as a headcount of countries. “Asia” excludes Russia, which is classed with Europe and Eurasia in the underlying IEA data; that matters because Russia is the clearest case of an exporter whose incentives run the opposite way. And the fourteen-times resource figure is a technical potential computed on land-use assumptions, not a forecast or an economic estimate — it belongs in the same category as MacKay’s own maximum-conceivable stacks, which he insisted were bounds rather than plans.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/chapM.html" class="pagination-link" aria-label="M Energy return on investment">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">M Energy return on investment</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/charts.html" class="pagination-link" aria-label="Charts">
        <span class="nav-page-text"><span class="chapter-title">Charts</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>