<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>11a The machines behind the screen – Sustainable Energy — Without the Hot Air</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/chap12.html" rel="next">
<link href="../chapters/chap11.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1b15cd7dfe5d645daabccee077c4b062.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chap01.html">Part I · Numbers, not adjectives</a></li><li class="breadcrumb-item"><a href="../chapters/chap11a.html"><span class="chapter-title">11a The machines behind the screen</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Sustainable Energy — Without the Hot Air</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About this edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I · Numbers, not adjectives</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap01.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1 Motivations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap02.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2 The balance sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap03.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3 Cars</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap04.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4 Wind</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap05.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5 Planes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap06.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6 Solar</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap07.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7 Heating and cooling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap08.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8 Hydroelectricity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap09.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">9 Light</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap10.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10 Offshore wind</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap11.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11 Gadgets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap11a.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">11a The machines behind the screen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap12.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12 Wave</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap13.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13 Food and farming</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap14.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14 Tide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap15.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15 Stuff</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap16.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">16 Geothermal</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap17.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17 Public services</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap18.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18 Can we live on renewables?</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II · Making a difference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap19.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19 Every BIG helps</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap20.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20 Better transport</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap21.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">21 Smarter heating</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap22.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">22 Efficient electricity use</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap23.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">23 Sustainable fossil fuels?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap24.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">24 Nuclear?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap25.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">25 Living on other countries’ renewables?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap26.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">26 Fluctuations and storage</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap27.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">27 Five energy plans for Britain</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap28.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">28 Putting costs in perspective</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap-value-of-renewables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">28a The value of renewable energy as it scales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap29.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">29 What to do now</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap30.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">30 Energy plans for Europe, America, and the World</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap31.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">31 The last thing we should talk about</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap32.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">32 Saying yes</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III · Technical chapters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapA.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">A Cars II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapB.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">B Wind II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapC.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">C Planes II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapD.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">D Solar II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapE.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">E Heating II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapF.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">F Waves II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapG.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">G Tide II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapH.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">H Stuff II</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV · Useful data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapI.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">I Quick reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapJ.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">J Populations and areas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapK.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">K UK energy history</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapL.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">L The world in 2025</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapM.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">M Energy return on investment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapN.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">N Peak oil, peak gas, peak uranium</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/charts.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Charts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/bibliography.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bibliography</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/author.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The author</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/acknowledgments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Acknowledgments</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#what-the-number-is-now" id="toc-what-the-number-is-now" class="nav-link active" data-scroll-target="#what-the-number-is-now">What the number is now</a></li>
  <li><a href="#the-growth-rate-is-the-whole-story" id="toc-the-growth-rate-is-the-whole-story" class="nav-link" data-scroll-target="#the-growth-rate-is-the-whole-story">The growth rate is the whole story</a></li>
  <li><a href="#what-is-hidden" id="toc-what-is-hidden" class="nav-link" data-scroll-target="#what-is-hidden">What is hidden</a></li>
  <li><a href="#why-the-data-centre-wins-the-electron" id="toc-why-the-data-centre-wins-the-electron" class="nav-link" data-scroll-target="#why-the-data-centre-wins-the-electron">Why the data centre wins the electron</a>
  <ul class="collapse">
  <li><a href="#the-fork" id="toc-the-fork" class="nav-link" data-scroll-target="#the-fork">The fork</a></li>
  <li><a href="#west-london-where-the-losing-arm-was-housing" id="toc-west-london-where-the-losing-arm-was-housing" class="nav-link" data-scroll-target="#west-london-where-the-losing-arm-was-housing">West London, where the losing arm was housing</a></li>
  </ul></li>
  <li><a href="#the-jobs-behind-the-machines" id="toc-the-jobs-behind-the-machines" class="nav-link" data-scroll-target="#the-jobs-behind-the-machines">The jobs behind the machines</a></li>
  <li><a href="#what-it-means-for-the-balance-sheet" id="toc-what-it-means-for-the-balance-sheet" class="nav-link" data-scroll-target="#what-it-means-for-the-balance-sheet">What it means for the balance sheet</a></li>
  <li><a href="#notes-and-further-reading" id="toc-notes-and-further-reading" class="nav-link" data-scroll-target="#notes-and-further-reading">Notes and further reading</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chap01.html">Part I · Numbers, not adjectives</a></li><li class="breadcrumb-item"><a href="../chapters/chap11a.html"><span class="chapter-title">11a The machines behind the screen</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">11a The machines behind the screen</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>Editor’s note: this chapter is new in the 2026 revision. It is not David MacKay’s writing. Added by Örjan Lundberg.</em></p>
<p>Chapter 11 has a short section called “Powering the hidden tendrils of the information age”. It reports Jonathan Koomey’s finding that in 2005 the servers in American data centres, with their cooling and backup power, used <strong>0.4 kWh per day per person</strong> — “just over 1% of US electricity consumption” — and notes that this had doubled since 2000 as the server count went from 5.6 to 10 million.</p>
<p>MacKay put that in a chapter about gadgets, and in 2005 he was right to. A percent of national electricity is a rounding error next to heating and driving. This chapter exists because the tendrils stopped being hidden.</p>
<section id="what-the-number-is-now" class="level2">
<h2 class="anchored" data-anchor-id="what-the-number-is-now">What the number is now</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Data centre electricity</th>
<th>Share of that grid</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>World, 2024</td>
<td>415 TWh</td>
<td><strong>1.5%</strong></td>
</tr>
<tr class="even">
<td>United States, 2023</td>
<td>176 TWh</td>
<td><strong>4.4%</strong></td>
</tr>
<tr class="odd">
<td>United Kingdom, 2025</td>
<td>7 to 17 TWh</td>
<td><strong>2.5 to 6%</strong></td>
</tr>
<tr class="even">
<td>Ireland, 2024</td>
<td>about 7 TWh</td>
<td><strong>22%</strong></td>
</tr>
</tbody>
</table>
<p>In this book’s units, an American’s share of data-centre electricity is about <strong>1.4 kWh/d</strong>, against MacKay’s 0.4 twenty years ago. A citizen of the world averages 0.14. <strong>A British person’s share is between 0.3 and 0.7 kWh/d</strong>, the range reflecting a genuine disagreement about what counts. <strong>An Irish person’s share is about 3.6 kWh/d</strong> — which is close to the 5 kWh/d that chapter 11 offers as the figure for a whole houseful of gadgets left on all the time.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>The British range needs explaining, because it is wide. The lower figure, about 2.5% of national electricity, is the one usually quoted for data centres proper. A 2026 assessment put the United Kingdom and the United States both near <strong>6%</strong>, which is roughly double. The gap is boundary: whether telecoms and networking equipment count, whether enterprise server rooms inside ordinary offices count, and whether cryptocurrency mining counts. National Grid’s <em>Future Energy Scenarios</em> projects <strong>5.2 GW and just over 20 TWh a year by 2030</strong>, which would be about 7% of British electricity and roughly a fourfold rise.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>Ireland is the case worth staring at, because it is the future arriving early in a small country. Data centres took <strong>5% of Irish electricity in 2015 and 22% in 2024</strong>, more than quadrupling in nine years. No other consumer of electricity has ever grown like that inside a developed grid, and Ireland now has more of its power going into computation than into all its homes’ lighting, cooking and appliances combined.</p>
</section>
<section id="the-growth-rate-is-the-whole-story" class="level2">
<h2 class="anchored" data-anchor-id="the-growth-rate-is-the-whole-story">The growth rate is the whole story</h2>
<p>Absolute numbers understate this, because the interesting quantity is the exponent.</p>
<p>American data-centre demand grew at about <strong>7% a year from 2014 to 2018</strong>, then <strong>18% a year from 2018 to 2023</strong>, and is projected at <strong>13 to 27% a year to 2028</strong>, reaching <strong>325 to 580 TWh, or 6.7 to 12% of American electricity</strong>. Globally the IEA expects <strong>485 TWh in 2025 to become about 950 TWh in 2030</strong>, roughly 3% of world electricity.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p>Notice what the 2018 inflection is. Between 2010 and 2018 data-centre computing rose enormously while electricity barely moved, because efficiency — better chips, virtualisation, hyperscale facilities replacing cupboards full of servers — absorbed the growth. That is the same story as chapter 9’s light bulb: the service expanded and the energy did not.</p>
<p><strong>Then it stopped working.</strong> The efficiency gains ran out at roughly the moment demand for AI training and inference began, and since 2018 the curve has followed demand rather than efficiency. Servers for artificial intelligence were <strong>24% of server electricity and 15% of total data-centre energy in 2024</strong>, and are projected at <strong>35 to 50% of data-centre power by 2030</strong>.</p>
<p>This is the shape MacKay’s method is built to expose. A quantity growing at 18% a year doubles in four years. Applied to something that is already 4% of a national grid, four more doublings reaches the whole grid. The exponent cannot continue, and the interesting question is what stops it.</p>
</section>
<section id="what-is-hidden" class="level2">
<h2 class="anchored" data-anchor-id="what-is-hidden">What is hidden</h2>
<p>Three costs sit outside the electricity meter, and all three are the sort MacKay would have insisted on counting.</p>
<p><strong>Water.</strong> Cooling evaporates it. The industry average is about <strong>1.8 litres per kWh</strong> of electricity used, though the best operators are far better — Amazon reports a fleet average of <strong>0.19 L/kWh</strong>, nearly ten times lower. Virginia’s data centres consumed over <strong>2.1 billion gallons in 2023</strong>, about 8 million cubic metres, with Loudoun County alone at 900 million gallons.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> At 1.8 L/kWh the world’s 415 TWh implies something like 750 million cubic metres — and unlike electricity, water is consumed where it is drawn, in places increasingly chosen for cheap power rather than plentiful rivers.</p>
<p><strong>Grid position.</strong> A data centre is a large, constant, inflexible load that wants to be built quickly. It is therefore the opposite of what chapters 26 and 28a say a renewable-heavy system needs. Where it lands, it competes for connection capacity with everything else, and because it can pay more per kilowatt-hour than a smelter or a housing estate, it wins. Ireland’s grid operator has had to refuse or defer connections in Dublin for exactly this reason.</p>
<p><strong>The rebound that did not happen.</strong> Chapter 9 concludes that Britain kept its lighting efficiency gain because demand for light saturated. Computation has not saturated and shows no sign of it. Every efficiency improvement in computing since 1950 has been met by doing more computing, which is Jevons in its purest available form, and the AI build-out is the largest instance yet.</p>
</section>
<section id="why-the-data-centre-wins-the-electron" class="level2">
<h2 class="anchored" data-anchor-id="why-the-data-centre-wins-the-electron">Why the data centre wins the electron</h2>
<p>The section above says a data centre “can pay more per kilowatt-hour than a smelter”. The elmix model puts a number on that, and the number is the whole explanation.</p>
<p><strong>An electron does not know what it is for, but the buyers do.</strong> A power-intensive industry — an aluminium smelter, an ammonia plant, a silicon works — turns a kilowatt-hour into a few kronor of product. Electricity is a large share of its cost, which is why chapter 28a’s industrial price is existential for it. A hyperscale data centre running AI workloads turns the same kilowatt-hour into something on the order of <strong>80 to 100 kronor — roughly £6.50 to £8, or €7.50 to €9.50</strong> — of revenue. One reported arrangement, Anthropic renting about 300 MW of xAI compute for roughly $1.25 billion a month, works out near <strong>$5.70 per kWh: about £4.50, €5.30, or 53 kronor</strong>.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<p>That is roughly <strong>an order of magnitude</strong> above what heavy industry earns from the same electricity. In any auction for the same connection, at any plausible price, the data centre wins — not because it is favoured but because electricity is a rounding error in its cost structure and the dominant term in the smelter’s.</p>
<p>The consequence is visible where the market prices capacity explicitly rather than only energy. In the American PJM market, data-centre demand drove capacity auction prices up roughly <strong>tenfold</strong>, and accounted for <strong>63% of the 2025/26 increase</strong>.</p>
<section id="the-fork" class="level3">
<h3 class="anchored" data-anchor-id="the-fork">The fork</h3>
<p>The elmix model calls the result a <strong>demand fork</strong>, and the two arms are very different lengths.</p>
<ul>
<li><strong>Data centres</strong> in the EU: about <strong>70 TWh in 2024 rising to 115 TWh by 2030</strong>, growing near 15% a year — more than four times faster than all other sectors combined, though still under a tenth of global demand growth.</li>
<li><strong>Electrified industrial heat</strong>: a technical potential of about <strong>600 TWh</strong> in the EU — nearly nine times larger, and the thing this book has been arguing for since chapter 7.</li>
</ul>
<p>Both arms want the same scarce grid capacity and the same clean generation. One of them can pay eighty kronor — about £6.50 — a kilowatt-hour and be built in eighteen months. The other cannot and takes a decade.</p>
<p><strong>That is the awkward finding, and it is not a technical one.</strong> Every chapter of this book that argues for electrification — heat pumps in chapter 7, industrial heat in chapter 28a, transport in chapter 3 — is arguing for loads that lose a bidding war against computation. Nothing in the physics decides this. The connection queue does.</p>
</section>
<section id="west-london-where-the-losing-arm-was-housing" class="level3">
<h3 class="anchored" data-anchor-id="west-london-where-the-losing-arm-was-housing">West London, where the losing arm was housing</h3>
<p>Britain has already run this experiment, and the arm that lost was not industry but housing.</p>
<p>In summer 2022 the Greater London Authority found that three west London boroughs — <strong>Ealing, Hillingdon and Hounslow</strong> — had effectively run out of electrical connection capacity, with the constraint reaching outward to Slough and Egham. Developers were told that new housing in the area might not be connectable <strong>until 2035</strong>. The proximate cause was that data centres along the M4 corridor had taken the available headroom.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<p>Two things should be said fairly. The data-centre sector disputes the blame, pointing out that the distribution network was under-invested for decades and that any large load arriving at once would have exposed it. And the position has improved: from March 2024 a capacity-allocation study by the network operator unlocked 3315 permitted homes, and City Hall reports at least <strong>11 690 permitted homes</strong> since released.</p>
<p>But the shape of the episode is the point, and it is the demand fork with a British postcode. A load that earns tens of pounds per kilowatt-hour arrived quickly and was connected. Loads that earn nothing per kilowatt-hour — houses — waited, and needed a public body to intervene on their behalf. <strong>No price signal produced that outcome. A queue did.</strong></p>
<p>Sweden shows the same thing at national scale: connection applications in 2025 totalled about <strong>9000 MW, roughly half of it data centres</strong>, concentrated in Mälardalen, Stockholm, Uppsala and Gävleborg — and Microsoft’s Sandviken project was paused in the resulting crunch. A country that spent a decade arguing about whether it had enough electricity for its industry now finds the question settled by a different bidder.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
</section>
</section>
<section id="the-jobs-behind-the-machines" class="level2">
<h2 class="anchored" data-anchor-id="the-jobs-behind-the-machines">The jobs behind the machines</h2>
<p>The section above explains why the data centre wins the electron: it turns a kilowatt-hour into more revenue than any competing buyer. The same property has a second consequence, and it points the other way. Of all the large loads on a grid, the data centre returns the least of that kilowatt-hour as local wages. Both facts have one cause, which is that the machine is enormously capital-intensive and barely staffed.</p>
<p>Put the staffing on a per-megawatt basis, since that is how the electricity arrives. Industry surveys give a small facility of 1 to 5 MW around 2 to 3 staff per MW, a large one of 20 MW and up between 1 and 1.5, and an ultra-hyperscale campus above 100 MW between 0.2 and 0.3. Google’s Kansas City campus, at 500 MW, employs about 200 permanent staff: 0.4 jobs per MW.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
<p>Now convert to energy, which is the unit this book uses. A megawatt running at 85% of the time delivers 7.45 GWh in a year. At 1.5 jobs per MW that is about 5000 MWh of electricity per job-year; at Kansas City’s 0.4 it is about 19 000; at 0.2 it is about 37 000. <strong>Take 5000 to 37 000 MWh per job-year as the range, and note two things about it.</strong> It applies to facilities of 20 MW and up, which is what this chapter means by a large load on a grid; the halls below 20 MW are about twice as well staffed and land at 2500 to 4300, which as the next paragraph shows is smelter territory. And within the range, the newest and largest sites sit at the wrong end.</p>
<p>Two comparisons give that number a scale. Kubikenborg Aluminium at Sundsvall, the most electricity-hungry single plant in Sweden, employs about 470 people and uses roughly 1.6 TWh a year — about 3400 MWh per job-year, and that is a smelter, the traditional emblem of a lot of power for few jobs. The Swedish and American economies as a whole each use about 25 MWh of electricity per job-year. So a hyperscale data centre consumes somewhere between 200 and 1500 times as much electricity per job as the economy it sits in, and between about one and a half and eleven times as much as an aluminium smelter. A small data hall, by the same arithmetic, is roughly the smelter’s equal. <strong>The finding is about scale, not about computation as such</strong>, which is worth holding onto, because it is the large sites that are being built.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></p>
<p>The aggregate check agrees with the arithmetic. Food &amp; Water Watch, working from Bureau of Labor Statistics data and Virginia’s capacity, estimates that as few as 23 000 people held a permanent data-centre job in the United States in 2024 — 0.01% of American employment, against 4.4% of American electricity. The industry’s own figure, from a PricewaterhouseCoopers report for the Data Center Coalition, is 603 000. The gap is definitional rather than dishonest: PwC counts the whole of industry classification 518210, “data processing, hosting, and related services”, which also holds web hosting, cyber security and data-labelling firms; it counts posts rather than full-time equivalents; and it applies an indirect multiplier. The tell is geographic. Virginia has about a third of American data-centre capacity and 4% of the 518210 jobs.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></p>
<p>In Sweden the arithmetic reaches the public finances through a specific mechanism. Municipalities are funded by <em>kommunalskatt</em>, a tax on the wages of people who live there. Corporation tax and energy tax go to the state. A load can therefore produce a great deal of value added and very little municipal revenue, because the municipality is paid in jobs and this load does not have many. The energy-tax reduction that data centres had enjoyed since 2017 was abolished on 1 July 2023, so the state now collects full energy tax on them, though sites in the northern municipalities may still take the standing Norrland deduction. That closed a subsidy. It did not change which level of government gets paid.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a></p>
<p>The displacement argument needs stating carefully, because it is conditional. Where grid capacity is not scarce, a data centre takes nothing from anyone. Where it is scarce — the regime this chapter has already described in west London and in the Swedish connection queue — a megawatt allocated to computation is a megawatt not allocated to something else, and the arithmetic above says what the something else would have employed. That is an opportunity cost under a binding constraint, not a general claim, and it depends on the displaced load actually having been built. Connection queues are full of projects that never are.</p>
<p>Against all of this sits the best evidence on the other side, and it is good evidence. Brookings, comparing 93 American counties that received their first large data centre between 2008 and 2024 against some 3000 control counties, found total private employment 4 to 5% higher within five to six years, construction up 11%, information-sector work up 22%, and wages 3 to 4% higher. Three qualifications come with it. Naive before-and-after comparisons overstate the effect roughly threefold. The gains fall to hyperscale counties and not to colocation ones, which showed no significant information-sector growth at all — that, rather than the 23% in counties with four or more facilities, is where the concentration shows, since 23% against a 22% average is barely a difference. And construction is the largest employer a data centre ever has, for the two or three years it lasts. None of that is unique to computation: Swedish industry generates about 1.1 indirect jobs for every direct one, so a smelter’s 470 employees stand for something closer to 1000 — a figure that belongs beside the data centre’s own indirect employment, which nobody in this section has counted, and not divided back into the 1.6 TWh.<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a></p>
</section>
<section id="what-it-means-for-the-balance-sheet" class="level2">
<h2 class="anchored" data-anchor-id="what-it-means-for-the-balance-sheet">What it means for the balance sheet</h2>
<p>MacKay’s summary figure for chapter 11 is 5 kWh/d for a houseful of gadgets. Data centres are not in that number in any meaningful way — his 0.4 kWh/d for America was a footnote.</p>
<p>On today’s American figures they would add about <strong>1.4 kWh/d per person</strong>, and on the 2028 projection something between 2 and 4. That is not enormous beside heating’s 37 or driving’s 40. <strong>But it is new demand, arriving fast, in the one form the system finds hardest to accommodate: electricity, constant, and inflexible.</strong></p>
<p>And it changes an argument the book makes elsewhere, in the way the previous section describes. Chapters 6, 10 and 28a are about a system where the difficulty is that supply fluctuates and demand does not follow. A data centre is demand that could follow — computation can in principle be moved in time and space more easily than heat or transport can — but is currently built to run flat out because the capital cost of the hardware dwarfs the electricity. If that ever changes, the largest new load on the grid becomes the largest new source of flexibility. Nothing in the physics forbids it. The economics, so far, point the other way.</p>
</section>
<section id="notes-and-further-reading" class="level2">
<h2 class="anchored" data-anchor-id="notes-and-further-reading">Notes and further reading</h2>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Global data-centre electricity of 415 TWh in 2024, about 1.5% of world electricity, is from the International Energy Agency’s <em>Energy and AI</em> (2025). The American figure of 176 TWh and 4.4% of national consumption in 2023, excluding cryptocurrency mining, is from Lawrence Berkeley National Laboratory’s <em>2024 United States Data Center Energy Usage Report</em>, prepared for the Department of Energy. Irish figures are from the Central Statistics Office: data centres took 22% of metered electricity in 2024, against 5% in 2015. Per-person figures here are computed by dividing by populations of roughly 8.2 billion, 335 million and 5.4 million; they are shares of national consumption, not a claim about what any individual uses, since much of the computation serves users in other countries. That last point matters for Ireland especially, where the data centres largely serve Europe rather than Ireland, so the electricity is Irish and the service is not.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>British estimates differ by more than a factor of two, and the difference is definitional rather than empirical. The commonly quoted figure is about 2.5% of UK electricity for data centres proper; a 2026 assessment reported in the engineering press put the UK and US both near 6%, on a boundary that includes more of the wider digital infrastructure. Neither is wrong; they are answering different questions, and this edition quotes the range rather than choosing. National Grid’s <em>Future Energy Scenarios</em> 2025 gives a ten-year forecast of 5.2 GW and just over 20 TWh a year by 2030. Per-person figures use a population of 68.4 million and UK electricity consumption of roughly 280 TWh. Note that the American 4.4% figure excludes cryptocurrency mining while some British figures may not, which is part of the gap.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Growth rates and the 2028 range are from the Berkeley Lab report: about 7% a year 2014–2018, about 18% a year 2018–2023, and 13–27% a year projected 2023–2028, giving 325–580 TWh or 6.7–12% of US electricity. The global 2030 projection of about 950 TWh, roughly 3% of world electricity, and the AI shares — 24% of server electricity and 15% of data-centre energy in 2024, rising to 35–50% of data-centre power by 2030 — are the IEA’s. All of these are projections made during a capital-investment boom, and projections made during booms have a poor record; the 2028 range spanning nearly a factor of two is the honest reflection of that. The claim that efficiency absorbed growth until about 2018 is the standard reading of the Berkeley Lab series and of Masanet et al.&nbsp;(2020), which found global data-centre energy roughly flat from 2010 to 2018 despite a sixfold rise in compute.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Water usage effectiveness figures: an industry average near 1.8 litres per kWh, against Amazon Web Services’ reported global fleet average of 0.19 L/kWh. Virginia consumption of over 2.1 billion US gallons in 2023, with Loudoun County near 900 million, is from state and county reporting compiled by the Center for Secure Water at the University of Illinois and others. Two cautions. WUE varies by more than an order of magnitude with cooling design and climate, so a single global multiplication is indicative only — the 750 million cubic metre figure in the text should be read as an order of magnitude, not an estimate. And water <em>withdrawn</em> is not water <em>consumed</em>: evaporative cooling consumes most of what it takes, while some designs return most of it, and public reporting rarely distinguishes the two.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>The price channel and the demand fork are set out with sources in the elmix cannibalization model, section 2 of <a href="https://oluies.github.io/elmix/modell/referenser.html" class="uri">https://oluies.github.io/elmix/modell/referenser.html</a>. The argument that data centres outbid industry because electricity is a small share of their cost is Pär Holmberg’s; the revenue-per-kilowatt-hour comparison, roughly 80–100 SEK/kWh for hyperscale AI against a few SEK/kWh for power-intensive industry, is Jonas Kristiansen Nøland’s. The Anthropic–xAI figure is derived from a reported commercial arrangement — roughly 300 MW for about $1.25 billion a month — which is $5.71 per kWh if the capacity runs continuously, and should be treated as an order-of-magnitude indication from a single reported deal rather than an industry rate. Currency conversions throughout this section use approximate mid-2026 rates of 9.6 SEK, 0.79 GBP and 0.92 EUR to the US dollar, rounded to two significant figures; they are given so the reader can weigh the number against prices in their own currency, not as precise valuations, and the SEK figures in the underlying Swedish analysis are the primary ones there. PJM capacity auction figures, a roughly tenfold rise with data centres accounting for 63% of the 2025/26 increase, are from the same section. The EU demand figures — data centres about 70 TWh in 2024 rising to about 115 TWh by 2030 at roughly 15% a year, against a technical potential near 600 TWh for electrified industrial heat — are likewise sourced there.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>The west London constraint was identified by the Greater London Authority in summer 2022 across Ealing, Hillingdon and Hounslow, with effects extending to Slough and Egham, and reported as potentially blocking new housing connections until 2035. Subsequent progress — 3315 permitted homes unlocked from March 2024 through the network operator’s capacity-allocation study, and at least 11 690 permitted homes released in total with City Hall involvement — is from the GLA’s own reporting on west London electricity capacity constraints. The data-centre industry has publicly contested the attribution, arguing that long-run under-investment in distribution networks is the underlying cause and that data centres were simply the first large load to expose it. That argument has force: the episode shows a queue allocating scarce capacity, not a technology consuming more than its share.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Swedish connection-application figures are from <em>Dagens Infrastruktur</em>, 17 June 2026, as compiled in section 8 of the elmix references: about 9000 MW applied for in 2025, roughly half of it data centres, concentrated in Mälardalen, Stockholm, Uppsala and Gävleborg, with Microsoft’s Sandviken project paused. Applications are not commitments — a large share of any connection queue never gets built, and queues are known to contain speculative and duplicate requests — so the figure indicates pressure on the queue rather than load that will certainly arrive.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Staffing ratios per megawatt are from iRecruit’s 2026 survey of data-centre staffing: 2.0–3.0 per MW at 1–5 MW, 1.75–2.5 at 5–20 MW, 1.0–1.5 at 20 MW and above, and 0.2–0.3 for ultra-hyperscale sites above 100 MW. The Google Kansas City campus, 200 permanent staff for 500 MW, is from the same source, which puts it at 0.4 jobs per MW — above the ultra-hyperscale band rather than inside it, and quoted here at its own figure. Staffing ratios are a weak statistic in one specific way: they count people employed at the site, and a hyperscale operator’s monitoring, security and software staff may sit in another country or another company. The direction of that bias is unknown, since it removes some jobs from the site’s count and adds others that a smelter would have contracted out too. The 85% load factor used to convert megawatts to energy is a round figure for facilities built to run flat out; the text of this chapter explains why they are.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Kubikenborg Aluminium’s workforce of about 470 and its annual production of about 135 000 tonnes of primary aluminium are from Sveriges Television. Its electricity use is not published directly; it is derived from the company’s own statement that one öre per kilowatt-hour costs it 16 million kronor a year, which implies 1.6 TWh, and cross-checked against its separate claim to use about 1% of Swedish electricity. A third check, 135 000 tonnes at the 13–15 MWh per tonne typical of a modern smelter, gives 1.8–2.0 TWh, so the derived figure may be somewhat low and the resulting 3400 MWh per job-year somewhat generous to the smelter. The economy-wide figure of about 25 MWh per job-year is electricity consumption divided by total employment: roughly 140 TWh across 5.2 million employed in Sweden, and roughly 4000 TWh across 160 million in the United States, which land within a couple of MWh of each other. These are ratios of two aggregates, not a measure of any job’s electricity use, and the comparison is only meaningful because all three are computed the same way. The pulp and paper industry is deliberately left out: the 18 TWh figure commonly quoted covers the whole forest industry including sawmills, while the 19 000 employees commonly quoted alongside it covers pulp and paper alone, and dividing one by the other mixes two boundaries.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>The 23 000 estimate, its share of American employment, and the critique of the industry figure are from Food &amp; Water Watch, <em>Artificial Jobs: The Illusion of Big Tech’s Data Center Employment Claims</em>, January 2026. The 4.4% electricity share is the Berkeley Lab figure for 2023 cited there, while the employment estimate is for 2024. Food &amp; Water Watch is a campaigning organisation calling for a moratorium on data-centre construction, and the PricewaterhouseCoopers report was commissioned by the Data Center Coalition, an industry body; neither is disinterested, which is why the definitional point rather than either total is what this section rests on. The Virginia comparison — about a third of national capacity against 4% of national 518210 employment — is the part of the argument that does not depend on trusting either side’s total. The separate figure of 1.12 jobs per MW comes from Virginia’s growth in 518210 employment of 2148 against 1910 MW of data-centre capacity connected by Dominion Energy in 2023 and 2024.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>The energy-tax reduction for <em>datorhallar</em>, introduced in 2017, was abolished with effect from 1 July 2023, decided by the Riksdag in December 2022 on the government’s proposal in the budget bill for 2023 (prop. 2022/23:1); see Skatteverket, “Slopad skattenedsättning för datorhallar”. The stated reason was to give data centres an incentive to use electricity more efficiently under changed European market conditions. The <em>Norrlandsavdraget</em>, a standing reduction for electricity consumed in certain northern municipalities, is separate and continues to apply. The description of municipal finance here is the ordinary Swedish arrangement — <em>kommunalskatt</em> is levied on the income of residents, while corporation tax and energy tax accrue to the state — and is given because it explains why a municipality’s interest in a large employer differs from the state’s interest in a large investment.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>Employment effects are from Brookings, “New evidence on data center employment effects”, which links about 770 American facilities to county employment data for 2003–2024 and applies the synthetic control method to 93 counties receiving their first large facility between 2008 and 2024, against roughly 3000 controls. The stated caution that naive comparisons overstate the effect about threefold matters, because data-centre counties were already growing faster than their neighbours before the facilities arrived. The Swedish employment multiplier of 1.1 indirect jobs per direct job, giving a total multiplier of 2.1, is from Industriarbetsgivarna’s 2023 analysis by Industriekonomerna. <strong>It is not applied to either side of the MWh-per-job-year comparison</strong>: every such figure in this section, for the data centre and for the smelter alike, counts direct employment only. The ~1000 in the text shows what the multiplier would do to one side if it were applied, and is not to be divided back into the smelter’s 1.6 TWh. No published equivalent for data centres was found, which is itself a reason to leave both sides direct. Two of these findings are in tension and the tension is not resolved here: county-level employment rises where data centres are built, while the facilities themselves employ very few people. Construction, the information-sector cluster effect, and the ordinary economic activity of a large capital investment are the candidate explanations, and the Brookings authors favour the cluster effect. What the per-megawatt arithmetic establishes is narrower than the county result contradicts: it is a statement about operating employment per unit of electricity, not about the total economic effect of building the thing.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/chap11.html" class="pagination-link" aria-label="11 Gadgets">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">11 Gadgets</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/chap12.html" class="pagination-link" aria-label="12 Wave">
        <span class="nav-page-text"><span class="chapter-title">12 Wave</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>