<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Q The IPCC’s scenarios, in this book’s units – Sustainable Energy — Without the Hot Air</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/charts.html" rel="next">
<link href="../chapters/chapP.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-dabb4177d918b2a71d8bf8ab8beb4a59.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Pageview counting, same GoatCounter account as the elmix site. No cookies,
     no cross-site identifiers, nothing that needs a consent banner.
     Pinned to the versioned file with an SRI hash: count.js is a mutable URL
     and this runs in <head> on every page. -->
<script data-goatcounter="https://oluies.goatcounter.com/count" async="" src="https://gc.zgo.at/count.v4.js" integrity="sha384-nRw6qfbWyJha9LhsOtSb2YJDyZdKvvCFh0fJYlkquSFjUxp9FVNugbfy8q1jdxI+" crossorigin="anonymous"></script>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chapI.html">Part IV · Useful data</a></li><li class="breadcrumb-item"><a href="../chapters/chapQ.html"><span class="chapter-title">Q The IPCC’s scenarios, in this book’s units</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Sustainable Energy — Without the Hot Air</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About this edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I · Numbers, not adjectives</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap01.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1 Motivations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap02.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2 The balance sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap03.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3 Cars</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap04.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4 Wind</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap05.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5 Planes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap06.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6 Solar</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap07.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7 Heating and cooling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap08.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8 Hydroelectricity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap09.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">9 Light</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap10.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10 Offshore wind</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap11.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11 Gadgets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap11a.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11a The machines behind the screen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap12.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12 Wave</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap13.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13 Food and farming</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap14.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14 Tide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap15.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15 Stuff</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap16.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">16 Geothermal</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap17.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17 Public services</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap18.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18 Can we live on renewables?</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II · Making a difference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap19.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19 Every BIG helps</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap20.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20 Better transport</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap21.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">21 Smarter heating</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap22.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">22 Efficient electricity use</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap23.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">23 Sustainable fossil fuels?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap24.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">24 Nuclear?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap25.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">25 Living on other countries’ renewables?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap26.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">26 Fluctuations and storage</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap27.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">27 Five energy plans for Britain</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap28.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">28 Putting costs in perspective</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap-value-of-renewables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">28a The value of renewable energy as it scales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap29.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">29 What to do now</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap30.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">30 Energy plans for Europe, America, and the World</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap31.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">31 The last thing we should talk about</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap32.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">32 Saying yes</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III · Technical chapters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapA.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">A Cars II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapB.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">B Wind II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapC.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">C Planes II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapD.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">D Solar II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapE.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">E Heating II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapF.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">F Waves II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapG.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">G Tide II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapH.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">H Stuff II</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV · Useful data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapI.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">I Quick reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapJ.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">J Populations and areas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapK.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">K UK energy history</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapL.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">L The world in 2025</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapM.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">M Energy return on investment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapN.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">N Peak oil, peak gas, peak uranium</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapO.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">O The hydrogen ladder</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapP.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">P A book that starts where this one stops</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapQ.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Q The IPCC’s scenarios, in this book’s units</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/charts.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Charts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/bibliography.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bibliography</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/author.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The author</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/acknowledgments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Acknowledgments</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-two-categories-the-report-leads-with" id="toc-the-two-categories-the-report-leads-with" class="nav-link active" data-scroll-target="#the-two-categories-the-report-leads-with">The two categories the report leads with</a></li>
  <li><a href="#the-same-pathways-divided-by-the-people-living-on-them" id="toc-the-same-pathways-divided-by-the-people-living-on-them" class="nav-link" data-scroll-target="#the-same-pathways-divided-by-the-people-living-on-them">The same pathways, divided by the people living on them</a></li>
  <li><a href="#what-that-is-as-energy" id="toc-what-that-is-as-energy" class="nav-link" data-scroll-target="#what-that-is-as-energy">What that is, as energy</a></li>
  <li><a href="#what-the-report-says-about-energy-in-particular" id="toc-what-the-report-says-about-energy-in-particular" class="nav-link" data-scroll-target="#what-the-report-says-about-energy-in-particular">What the report says about energy in particular</a></li>
  <li><a href="#the-whole-ladder" id="toc-the-whole-ladder" class="nav-link" data-scroll-target="#the-whole-ladder">The whole ladder</a></li>
  <li><a href="#does-it-say-how-much-solar-or-how-much-nuclear" id="toc-does-it-say-how-much-solar-or-how-much-nuclear" class="nav-link" data-scroll-target="#does-it-say-how-much-solar-or-how-much-nuclear">Does it say how much solar, or how much nuclear?</a></li>
  <li><a href="#what-to-take-from-it" id="toc-what-to-take-from-it" class="nav-link" data-scroll-target="#what-to-take-from-it">What to take from it</a></li>
  <li><a href="#notes-and-further-reading" id="toc-notes-and-further-reading" class="nav-link" data-scroll-target="#notes-and-further-reading">Notes and further reading</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chapI.html">Part IV · Useful data</a></li><li class="breadcrumb-item"><a href="../chapters/chapQ.html"><span class="chapter-title">Q The IPCC’s scenarios, in this book’s units</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Q The IPCC’s scenarios, in this book’s units</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>Editor’s note: this chapter is new in the 2026 revision. It is not David MacKay’s writing. Added by Örjan Lundberg.</em></p>
<p>This book is about one country, and its quantity is energy: kilowatt-hours per day per person, supply against demand. The Intergovernmental Panel on Climate Change’s Sixth Assessment Report is about the whole world, and its quantity is emissions: gigatonnes of carbon dioxide equivalent per year. The two are quoted at each other constantly and almost never in the same units, so this chapter converts the report’s headline pathways into the ones the rest of this book uses.</p>
<p>A word on the abbreviation first, because this edition uses it for two different things. In chapters 4 and 28a, AR6 is Allocation Round 6, the sixth auction of British contracts for difference. Here it is the Sixth Assessment Report, and specifically the 2022 report of its working group III, on mitigation.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<section id="the-two-categories-the-report-leads-with" class="level2">
<h2 class="anchored" data-anchor-id="the-two-categories-the-report-leads-with">The two categories the report leads with</h2>
<p>The report sorts more than a thousand modelled pathways by how much warming they produce. Two categories carry the argument.</p>
<p>C1 limits warming to 1.5 °C with no or limited overshoot: 97 pathways. C3 limits it to 2 °C with better than two chances in three: 311 pathways. Measured against modelled 2019 emissions of 55 GtCO<sub>2</sub>-equivalent, the median pathway in each category cuts global greenhouse gases by:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>by 2030</th>
<th>by 2040</th>
<th>by 2050</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>C1 — 1.5 °C</td>
<td>43%</td>
<td>69%</td>
<td>84%</td>
</tr>
<tr class="even">
<td>C3 — 2 °C</td>
<td>21%</td>
<td>46%</td>
<td>64%</td>
</tr>
</tbody>
</table>
<p>Global net zero CO<sub>2</sub> arrives in the early 2050s in C1 and around the early 2070s in C3. The cumulative carbon dioxide C1 spends on the way is 510 GtCO<sub>2</sub>, which at the 2019 rate is about thirteen years of it.</p>
</section>
<section id="the-same-pathways-divided-by-the-people-living-on-them" class="level2">
<h2 class="anchored" data-anchor-id="the-same-pathways-divided-by-the-people-living-on-them">The same pathways, divided by the people living on them</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/without-hot-air/fig-q1-ar6-pathways.svg" class="img-fluid figure-img"></p>
<figcaption>The IPCC’s C1 and C3 pathways expressed as tonnes of CO2-equivalent per person per year, falling from 7.0 tonnes in 2019 to 0.90 for C1 and 2.02 for C3 by 2050, with the 5th-to-95th-percentile ranges shaded and a second axis giving the equivalent in kWh per day of fuel at 250 g of CO2 per kWh.</figcaption>
</figure>
</div>
<p><span class="figurenumber">Figure Q.1.</span> <em>Added in the 2026 revision.</em> The report’s two headline categories, computed from the 1202 vetted pathways of the AR6 Scenarios Database and divided by the United Nations’ medium population projection, with the right-hand axis converting the tonnage to the fuel it would be at this book’s own 250 g of CO<sub>2</sub> per kWh.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>In 2019 the world emitted 7.0 tonnes per person. C1’s median takes that to 3.6 tonnes by 2030 and 0.90 by 2050; C3’s to 5.1 and 2.0.</p>
<p>Notice what the division does to the headline. The report’s 84% cut by 2050 is a cut in the global total, and the population is projected to grow from 7.8 billion to 9.7 billion over the same period — so the cut each person has to make is 87%, not 84%. At 2030 the gap is wider in proportion: 43% globally, 48% each. Growth in the denominator is doing some of the work the report’s percentages hide, and it is working against us.</p>
</section>
<section id="what-that-is-as-energy" class="level2">
<h2 class="anchored" data-anchor-id="what-that-is-as-energy">What that is, as energy</h2>
<p>This book’s carbon chart converts at 250 grams of CO<sub>2</sub> per kWh of chemical fuel, oil or petrol. Run the per-person emissions through it and the pathways turn into something a reader of chapter 2 can hold.</p>
<p>Today’s 7.0 tonnes per person is 77 kWh/d of burning — which is close to the 68.9 kWh/d of primary energy per person the world’s richer half actually uses, and not far from MacKay’s British stack of 125. C1’s 2050 figure of 0.90 tonnes is 9.9 kWh/d.&nbsp;C3’s 2.0 tonnes is 22.</p>
<p>Ten kilowatt-hours a day is not a plan for the energy supply; it is the entire greenhouse budget, and farming, cement and everything else has to come out of it first. So the honest reading of the number is the other way round: if the C1 pathway is met while anyone still burns anything, almost all of the energy in chapters 2 to 18 has to arrive without combustion. That is the same conclusion this book reaches from the supply side, arrived at from the emissions side.</p>
</section>
<section id="what-the-report-says-about-energy-in-particular" class="level2">
<h2 class="anchored" data-anchor-id="what-the-report-says-about-energy-in-particular">What the report says about energy in particular</h2>
<p>Five of its findings bear directly on the arithmetic in this book.</p>
<p>Coal, oil and gas all fall, and not equally. In C1 pathways, 2050 use falls by a median 95% for coal, 60% for oil and 45% for gas against 2019; without carbon capture the falls are 100%, 60% and 70%. In C3 they are 85%, 30% and 15%. Gas survives longest in the scenarios and coal not at all.</p>
<p>Electricity carries the transition. In C1 pathways, almost all electricity in 2050 comes from zero- or low-carbon sources, alongside increased electrification of everything else — which is chapter 20’s argument about cars and chapter 21’s about heat, made globally.</p>
<p>The costs came down faster than anyone’s plans assumed. Between 2010 and 2019 the unit cost of solar fell 85%, wind 55% and lithium-ion batteries 85%, while deployment rose more than tenfold for solar and more than a hundredfold for electric vehicles. MacKay’s own cost figures in chapter 28 are from before that fall, which is what chapter 28’s revision is about.</p>
<p>Half of the 2030 job is available cheaply. Options costing 100 dollars a tonne of CO<sub>2</sub>-equivalent or less could cut global emissions to half their 2019 level by 2030, and the largest contributions below 20 dollars come from solar, wind, efficiency, stopping the conversion of natural ecosystems, and methane from coal, oil, gas and waste.</p>
<p>And demand is not fixed. Demand-side measures — how buildings, transport and cities are used, not only what supplies them — can cut end-use emissions 40 to 70% by 2050 against baseline. This book holds demand roughly constant and asks what can supply it; the report says the demand is itself a variable, and a large one.</p>
<p>The money is the part this book’s chapter 28 is about. Average annual investment for 2020 to 2030 in pathways limiting warming to 2 °C or 1.5 °C is three to six times current levels.</p>
</section>
<section id="the-whole-ladder" class="level2">
<h2 class="anchored" data-anchor-id="the-whole-ladder">The whole ladder</h2>
<p>The two categories above are the ones the report leads with, but it sorts its pathways into eight. Computed the same way — the median pathway in each, in 2050, divided by the people then alive — the ladder reads like this.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Category</th>
<th>Pathways</th>
<th>Cut by 2050</th>
<th>Per person</th>
<th>As fuel</th>
<th>Net zero CO<sub>2</sub></th>
<th>Peak warming</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>C1 · 1.5 °C, no or limited overshoot</td>
<td>97</td>
<td>84%</td>
<td>0.90 t</td>
<td>9.9 kWh/d</td>
<td>2052</td>
<td>1.58 °C</td>
</tr>
<tr class="even">
<td>C2 · 1.5 °C after high overshoot</td>
<td>133</td>
<td>75%</td>
<td>1.41 t</td>
<td>15.4</td>
<td>2058</td>
<td>1.70</td>
</tr>
<tr class="odd">
<td>C3 · 2 °C (&gt;67%)</td>
<td>311</td>
<td>64%</td>
<td>2.02 t</td>
<td>22.1</td>
<td>2070</td>
<td>1.75</td>
</tr>
<tr class="even">
<td>C4 · 2 °C (&gt;50%)</td>
<td>159</td>
<td>49%</td>
<td>2.91 t</td>
<td>31.9</td>
<td>2079</td>
<td>1.91</td>
</tr>
<tr class="odd">
<td>C5 · 2.5 °C</td>
<td>212</td>
<td>29%</td>
<td>4.05 t</td>
<td>44.3</td>
<td>—</td>
<td>2.15</td>
</tr>
<tr class="even">
<td>C6 · 3 °C</td>
<td>97</td>
<td>5%</td>
<td>5.42 t</td>
<td>59.4</td>
<td>—</td>
<td>2.69</td>
</tr>
<tr class="odd">
<td>C7 · 4 °C</td>
<td>164</td>
<td>−24%</td>
<td>7.06 t</td>
<td>77.3</td>
<td>—</td>
<td>3.48</td>
</tr>
<tr class="even">
<td>C8 · above 4 °C</td>
<td>29</td>
<td>−46%</td>
<td>8.31 t</td>
<td>91.0</td>
<td>—</td>
<td>4.22</td>
</tr>
</tbody>
</table>
<p>Two things are worth reading off it. The step from C3 to C1 — from two degrees to one and a half — costs about 12 kWh/d per person of burning, which is roughly what the average European spends on driving. And the bottom of the ladder is not a plan at all: C8 has emissions per person higher in 2050 than today, and C7 is level with today — 7.06 tonnes against 7.04, a difference far inside the report’s own 53 to 58 GtCO<sub>2</sub>-equivalent band for 2019. That is what “no new policy” looks like once population growth is taken out.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
</section>
<section id="does-it-say-how-much-solar-or-how-much-nuclear" class="level2">
<h2 class="anchored" data-anchor-id="does-it-say-how-much-solar-or-how-much-nuclear">Does it say how much solar, or how much nuclear?</h2>
<p>Not per scenario, and the omission is deliberate.</p>
<p>What the report does publish for each category is the fossil side, which is above, and three statements about the low-carbon side. In pathways that limit warming to 2 °C or below, 88% (69 to 97%) of primary energy comes from low-carbon sources by 2100, and non-biomass renewables — wind, solar, hydro, geothermal — account for 52% (24 to 77%) of all primary energy. Carbon dioxide from energy supply reaches net zero around 2041 (2033 to 2057) in the 1.5 °C pathways and around 2053 (2040 to 2066) in the 2 °C ones. And nearly all electricity comes from low- or no-carbon fuels.</p>
<p>But the report states plainly that those fuels arrive in “different shares of nuclear, biomass, non-biomass renewables, and fossil CCS across pathways”. There is no C1 number for nuclear, or for solar, because the category is defined by its temperature outcome and not by its machines. Its illustrative pathways make the point by disagreeing with each other on purpose: one leans on renewables, one on carbon dioxide removal, one on low demand, one on a broader shift in development. Each reaches the same temperature by a different stack.</p>
<p>That is the same shape as chapter 27 of this book, which offers five plans that all add up and differ completely — MacKay’s point being that the arithmetic constrains the total and leaves the mix to politics. The report reaches it from the other end and says it in the same tone.</p>
<p>Where the per-technology numbers do exist is underneath: every pathway is published in the AR6 Scenarios Database, with primary energy by carrier for each one. The report does not summarise them, and this edition’s first pass through the chapter said so and stopped there.</p>
<p>Then the database was read, and it does.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/without-hot-air/fig-q2-ar6-energy-mix.svg" class="img-fluid figure-img"></p>
<figcaption>Two panels, one per category, showing each energy carrier’s primary energy in 2020 and in 2050 on a logarithmic scale. In the 1.5 °C pathways solar grows 32-fold and wind 16-fold while coal falls 95%, oil 62% and gas 42%; nuclear roughly doubles and hydro and biomass grow by about 80 and 98%. The 5th-to-95th-percentile bars are wide: solar spans 31 to 200 EJ and nuclear 4 to 70.</figcaption>
</figure>
</div>
<p><span class="figurenumber">Figure Q.2.</span> <em>Added in the 2026 revision.</em> What the pathways build, carrier by carrier, computed from the AR6 Scenarios Database. Grey is 2020, the coloured dot is the median across the pathways in 2050, and the pale bar is the range they span.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p>In the 1.5 °C category the median pathway multiplies solar by 32 and wind by 16 between 2020 and 2050, roughly doubles both nuclear and biomass, grows hydro by about four-fifths, and cuts coal by 95%, oil by 62% and gas by 42%. In the 2 °C category the growth is smaller and slower: solar by 21, wind by 13, nuclear by four-fifths, with coal down 82%, oil 33% and gas 15%.</p>
<p>In the book’s own units, the median across the 1.5 °C pathways for total primary energy in 2050 is about 43 kWh/d per person — a third less than Britain uses today — with a median of 9.3 kWh/d for biomass, 8.5 for solar, 6.9 for wind, 2.4 for hydro and 1.6 for nuclear. Those are six separate medians over slightly different sets of pathways rather than one pathway’s stack, which is why they do not add up to the total.</p>
<p>So nuclear does grow — and of every carrier that grows, it adds the least new energy: 10 EJ a year by 2050, against hydro’s 14, biomass’s 58, wind’s 82 and solar’s 104. That is not a judgement the report makes; it is what happens when a thousand modelling teams each pick a mix and the middle one is taken.</p>
<p>The spread is the part worth staring at. Across the 1.5 °C pathways, solar in 2050 runs from 31 to 200 exajoules and nuclear from 4 to 70 — a factor of six for one and sixteen for the other. The models agree that coal ends and disagree about nearly everything that replaces it. That is why the report publishes the fossil declines as numbers and describes the low-carbon side in words, and it is the honest answer to the question: yes, there is an increase in solar and in nuclear in the scenarios; no, there is no such thing as the IPCC’s number for either.</p>
<p>The nearest thing to a technology ranking the report does publish is a different quantity: the emissions each option could remove in 2030, and what that costs. Wind and solar are the two largest options in that chart, each around 4 GtCO<sub>2</sub>-equivalent a year, most of it available below 20 dollars a tonne; nuclear is on the same chart at well under a gigatonne, and at a higher cost. That is a statement about 2030 potential and price, not about what any scenario builds.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
</section>
<section id="what-to-take-from-it" class="level2">
<h2 class="anchored" data-anchor-id="what-to-take-from-it">What to take from it</h2>
<p>The report and this book agree about more than they disagree. Both say electrification, both say the resource is adequate and the rate of building is not, both say the cheap options are cheap and unbuilt, both are impatient with plans that do not add up.</p>
<p>They differ in two ways worth keeping in mind while reading either. The report’s pathways lean on carbon capture and on carbon dioxide removal at a scale that does not yet exist, which is the caution chapter 23 makes at length. And the report is a set of scenarios, not a forecast: the pathways say what would have to happen for a temperature outcome, not what will. Read as arithmetic, though, they are exactly the kind this book is built on — a quantity, divided by the people who have to live on it, checked against what the machines can actually do.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
</section>
<section id="notes-and-further-reading" class="level2">
<h2 class="anchored" data-anchor-id="notes-and-further-reading">Notes and further reading</h2>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>The report is the Intergovernmental Panel on Climate Change’s <em>Climate Change 2022: Mitigation of Climate Change</em>, the working group III contribution to the Sixth Assessment Report, Cambridge University Press, 2022. Everything quoted in this chapter is from its Summary for Policymakers, which is free: the scenario categories and the reduction percentages from Table SPM.2 and paragraph C.1; the net zero dates from C.2; the fossil-fuel declines and the electricity finding from C.3.2; the cost falls and deployment multiples from B.4.1; the cost-of-abatement finding from C.12; the demand-side range from C.10; and the investment factor from E.5.1. Modelled 2019 emissions of 55 [53–58] GtCO<sub>2</sub>-equivalent are the report’s own baseline, and its reductions are measured against that rather than against the observed series in its chapter 2, which differs slightly. “AR6” in chapters 4 and 28a of this edition means Allocation Round 6 of the British contracts-for-difference auctions, which is an unrelated thing that shares an abbreviation.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Figure Q.1 is this edition’s arithmetic on the report’s own ensemble rather than on its printed table. The pathways come from the AR6 Scenarios Database’s metadata indicators, version 1.1, the vetted set of 1202 scenarios that chapter 3 of the working group III report is built on, cut here to the columns used. Medians and 5th-to-95th-percentile ranges are computed across the pathways in each category, and the data task checks its own medians against the percentages Table SPM.2 prints and fails if any drifts by more than 1.5 points — they agree to within a third of a point: 43.3 against 43 for C1 in 2030, 68.9 against 69, 84.2 against 84, and 20.7, 46.3 and 64.5 against 21, 46 and 64 for C3. The category counts come back as the report prints them too, 97 pathways in C1 and 311 in C3 out of 1202. Population is the United Nations’ medium projection as published by Our World in Data: 7.81 billion in 2019, 8.57 in 2030 and 9.66 in 2050. Three cautions. These are greenhouse gases, not carbon dioxide alone, so the conversion to kWh at 250 g per kWh describes what the tonnage would be if all of it were burnt fuel, which it is not — agriculture, cement and industrial gases are inside these totals, and the fuel share is the part this book’s chapters can address. Dividing a global pathway by global population says nothing about who emits what: the report’s own figures put the top 10% of households at 34 to 45% of consumption-based emissions. And a scenario is not a forecast; the ranges shown are the spread of models, not a probability that the world does any of this.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The ladder is computed from the same file as figure Q.1: for each category, the median across its pathways of the greenhouse-gas reduction from 2019 to 2050, applied to the report’s modelled 2019 total of 55 GtCO<sub>2</sub>-equivalent, then divided by the United Nations’ medium projection of 9.66 billion people in 2050 and converted at 250 g of CO<sub>2</sub> per kWh. Net zero is the median year of net zero CO<sub>2</sub> among the pathways in the category that reach it, and is left blank where fewer than half of them do — from C5 downwards, most never do. Peak warming is the median of the database’s own MAGICC estimate. A caution that applies to the whole table: a median across models is not a pathway. Each row mixes scenarios from many modelling teams with different assumptions, so the median is a description of a literature rather than a route anyone proposed.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Figure Q.2 is computed from the AR6 Scenarios Database’s world timeseries file, version 1.1, which is 345 MB and is not kept in this edition’s repository: it has to be fetched by hand from the IIASA Scenario Explorer, which wants a free account, and the data task says where to put it. The derived table is small and is kept. Each figure is the median across the pathways of a category for a carrier’s primary energy, with the 5th and 95th percentiles for 2050, joined to the categories by model and scenario name. Not every pathway reports every carrier — 94 of C1’s 97 report primary energy at all, and 76 report solar and wind separately — so these medians are over slightly different sets, which is one more reason to read the spread rather than the middle. The check is the report’s own published fossil declines: this extraction gives 95%, 62% and 42% for coal, oil and gas in C1 against the 95%, 60% and 45% of paragraph C.3.2, and 82%, 33% and 15% for C3 against 85%, 30% and 15%, and the task fails if any of the six drifts by more than eight points. Primary energy is converted to kWh per day per person at the 2050 population used in figure Q.1, and the report’s accounting counts one unit of nuclear or non-biomass renewable output as one unit of primary energy, so these are not the substitution-method numbers used elsewhere in this book.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>The low-carbon and renewable shares of primary energy in 2100, and the dates at which carbon dioxide from energy supply reaches net zero, are from section 3.4.2 of chapter 3 of the working group III report, <em>Mitigation Pathways Compatible with Long-term Goals</em>, which is also where the sentence about different shares of nuclear, biomass, non-biomass renewables and fossil CCS comes from. The illustrative mitigation pathways — IMP-Ren, IMP-Neg, IMP-LD, IMP-GS and IMP-SP — are described in the Summary for Policymakers’ Box SPM.1 and in chapter 3. The per-pathway energy mix is published in the AR6 Scenarios Database, hosted by the International Institute for Applied Systems Analysis, which is the source the report’s own tables draw on. The 2030 potentials for wind, solar and nuclear are read off Figure SPM.7 of the Summary for Policymakers, which is why they are given here as approximate: this edition has not had the figure’s underlying values, and the text beside it says only that the large contributions below 20 dollars a tonne come from solar and wind energy, efficiency, ecosystems and methane. Chapter 3’s table 3.4 does give a low-carbon share of primary energy and an electricity share of final energy for every category in 2030, 2050 and 2100, and they are not quoted here because this edition could not map that table’s columns from the published PDF with enough confidence to print numbers from it.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>The report is the Intergovernmental Panel on Climate Change’s <em>Climate Change 2022: Mitigation of Climate Change</em>, the working group III contribution to the Sixth Assessment Report, Cambridge University Press, 2022. Everything quoted in this chapter is from its Summary for Policymakers, which is free: the scenario categories and the reduction percentages from Table SPM.2 and paragraph C.1; the net zero dates from C.2; the fossil-fuel declines and the electricity finding from C.3.2; the cost falls and deployment multiples from B.4.1; the cost-of-abatement finding from C.12; the demand-side range from C.10; and the investment factor from E.5.1. Modelled 2019 emissions of 55 [53–58] GtCO<sub>2</sub>-equivalent are the report’s own baseline, and its reductions are measured against that rather than against the observed series in its chapter 2, which differs slightly. “AR6” in chapters 4 and 28a of this edition means Allocation Round 6 of the British contracts-for-difference auctions, which is an unrelated thing that shares an abbreviation.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/chapP.html" class="pagination-link" aria-label="P A book that starts where this one stops">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">P A book that starts where this one stops</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/charts.html" class="pagination-link" aria-label="Charts">
        <span class="nav-page-text"><span class="chapter-title">Charts</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>