<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>24 Nuclear? – Sustainable Energy — Without the Hot Air</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/chap25.html" rel="next">
<link href="../chapters/chap23.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1b15cd7dfe5d645daabccee077c4b062.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chap19.html">Part II · Making a difference</a></li><li class="breadcrumb-item"><a href="../chapters/chap24.html"><span class="chapter-title">24 Nuclear?</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Sustainable Energy — Without the Hot Air</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About this edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I · Numbers, not adjectives</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap01.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1 Motivations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap02.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2 The balance sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap03.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3 Cars</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap04.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4 Wind</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap05.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5 Planes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap06.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6 Solar</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap07.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7 Heating and cooling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap08.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8 Hydroelectricity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap09.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">9 Light</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap10.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10 Offshore wind</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap11.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11 Gadgets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap12.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12 Wave</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap13.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13 Food and farming</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap14.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14 Tide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap15.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15 Stuff</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap16.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">16 Geothermal</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap17.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17 Public services</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap18.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18 Can we live on renewables?</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II · Making a difference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap19.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19 Every BIG helps</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap20.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20 Better transport</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap21.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">21 Smarter heating</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap22.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">22 Efficient electricity use</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap23.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">23 Sustainable fossil fuels?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap24.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">24 Nuclear?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap25.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">25 Living on other countries’ renewables?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap26.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">26 Fluctuations and storage</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap27.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">27 Five energy plans for Britain</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap28.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">28 Putting costs in perspective</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap-value-of-renewables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">28a The value of renewable energy as it scales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap29.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">29 What to do now</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap30.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">30 Energy plans for Europe, America, and the World</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap31.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">31 The last thing we should talk about</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap32.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">32 Saying yes</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III · Technical chapters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapA.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">A Cars II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapB.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">B Wind II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapC.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">C Planes II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapD.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">D Solar II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapE.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">E Heating II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapF.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">F Waves II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapG.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">G Tide II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapH.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">H Stuff II</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV · Useful data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapI.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">I Quick reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapJ.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">J Populations and areas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapK.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">K UK energy history</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapL.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">L The world in 2025</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/charts.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Charts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/bibliography.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bibliography</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sustainable-power-from-nuclear-fission" id="toc-sustainable-power-from-nuclear-fission" class="nav-link active" data-scroll-target="#sustainable-power-from-nuclear-fission">“Sustainable” power from nuclear fission</a>
  <ul class="collapse">
  <li><a href="#once-through-reactors-using-uranium-from-the-ground" id="toc-once-through-reactors-using-uranium-from-the-ground" class="nav-link" data-scroll-target="#once-through-reactors-using-uranium-from-the-ground">Once-through reactors, using uranium from the ground</a></li>
  <li><a href="#fast-breeder-reactors-using-uranium-from-the-ground" id="toc-fast-breeder-reactors-using-uranium-from-the-ground" class="nav-link" data-scroll-target="#fast-breeder-reactors-using-uranium-from-the-ground">Fast breeder reactors, using uranium from the ground</a></li>
  <li><a href="#once-through-using-uranium-from-the-oceans" id="toc-once-through-using-uranium-from-the-oceans" class="nav-link" data-scroll-target="#once-through-using-uranium-from-the-oceans">Once-through, using uranium from the oceans</a></li>
  <li><a href="#fast-breeder-reactors-using-uranium-from-the-oceans" id="toc-fast-breeder-reactors-using-uranium-from-the-oceans" class="nav-link" data-scroll-target="#fast-breeder-reactors-using-uranium-from-the-oceans">Fast breeder reactors, using uranium from the oceans</a></li>
  <li><a href="#using-uranium-from-rivers" id="toc-using-uranium-from-rivers" class="nav-link" data-scroll-target="#using-uranium-from-rivers">Using uranium from rivers</a></li>
  <li><a href="#what-about-costs" id="toc-what-about-costs" class="nav-link" data-scroll-target="#what-about-costs">What about costs?</a></li>
  </ul></li>
  <li><a href="#thorium" id="toc-thorium" class="nav-link" data-scroll-target="#thorium">Thorium</a></li>
  <li><a href="#land-use" id="toc-land-use" class="nav-link" data-scroll-target="#land-use">Land use</a></li>
  <li><a href="#economics-of-cleanup" id="toc-economics-of-cleanup" class="nav-link" data-scroll-target="#economics-of-cleanup">Economics of cleanup</a></li>
  <li><a href="#safety" id="toc-safety" class="nav-link" data-scroll-target="#safety">Safety</a>
  <ul class="collapse">
  <li><a href="#inherently-safe-nuclear-power" id="toc-inherently-safe-nuclear-power" class="nav-link" data-scroll-target="#inherently-safe-nuclear-power">Inherently safe nuclear power</a></li>
  </ul></li>
  <li><a href="#mythconceptions" id="toc-mythconceptions" class="nav-link" data-scroll-target="#mythconceptions">Mythconceptions</a></li>
  <li><a href="#what-about-nuclear-fusion" id="toc-what-about-nuclear-fusion" class="nav-link" data-scroll-target="#what-about-nuclear-fusion">What about nuclear fusion?</a>
  <ul class="collapse">
  <li><a href="#lithium-fusion" id="toc-lithium-fusion" class="nav-link" data-scroll-target="#lithium-fusion">Lithium fusion</a></li>
  <li><a href="#deuterium-fusion" id="toc-deuterium-fusion" class="nav-link" data-scroll-target="#deuterium-fusion">Deuterium fusion</a></li>
  </ul></li>
  <li><a href="#notes-and-further-reading" id="toc-notes-and-further-reading" class="nav-link" data-scroll-target="#notes-and-further-reading">Notes and further reading</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chap19.html">Part II · Making a difference</a></li><li class="breadcrumb-item"><a href="../chapters/chap24.html"><span class="chapter-title">24 Nuclear?</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">24 Nuclear?</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><img src="img/without-hot-air/figure192.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 24.1</span>. Electricity generated per capita from nuclear fission in 2007, in kWh per day per person, in each of the countries with nuclear power. <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<blockquote class="blockquote">
<p><em>We made the mistake of lumping nuclear energy in with nuclear weapons, as if all things nuclear were evil. I think that’s as big a mistake as if you lumped nuclear medicine in with nuclear weapons.</em></p>
<p>Patrick Moore, former Director of Greenpeace International</p>
</blockquote>
<p>Nuclear power comes in two flavours. Nuclear <em>fission</em> is the flavour that we know how to use in power stations; fission uses uranium, an exceptionally heavy element, as fuel. Nuclear <em>fusion</em> is the flavour that we don’t yet know how to implement in power stations; fusion would use light elements, especially hydrogen, as its fuel. Fission reactions split up heavy nuclei into medium-sized nuclei, releasing energy. Fusion reactions fuse light nuclei into medium-sized nuclei, releasing energy.</p>
<p>Both forms of nuclear power, fission and fusion, have an important property: the nuclear energy available per atom is roughly one million times bigger than the chemical energy per atom of typical fuels. This means that the amounts of fuel and waste that must be dealt with at a nuclear reactor can be up to one million times smaller than the amounts of fuel and waste at an equivalent fossil-fuel power station.</p>
<p>Let’s try to personalize these ideas. The mass of the fossil fuels consumed by “the average British person” is about 16 kg per day (4 kg of coal, 4 kg of oil, and 8 kg of gas). That means that every single day, an amount of fossil fuels with the same weight as 28 pints of milk is extracted from a hole in the ground, transported, processed, and burned somewhere on your behalf. The average Brit’s fossil fuel habit creates 11 tons per year of waste carbon dioxide; that’s 30 kg per day. In the previous chapter we raised the idea of capturing waste carbon dioxide, compressing it into solid or liquid form, and transporting it somewhere for disposal. Imagine that one person was responsible for capturing and dealing with all their own carbon dioxide waste. 30 kg per day of carbon dioxide is a substantial rucksack-full every day – the same weight as 53 pints of milk!</p>
<p>In contrast, the amount of natural uranium required to provide the same amount of energy as 16 kg of fossil fuels, in a standard fission reactor, is 2 grams; and the resulting waste weighs one quarter of a gram. (This 2 g of uranium is not as small as one millionth of 16 kg per day, by the way, because today’s reactors burn up less than 1% of the uranium.) To deliver 2 grams of uranium per day, the miners at the uranium mine would have to deal with perhaps 200 g of ore per day.</p>
<p>So the material streams flowing into and out of nuclear reactors are small, relative to fossil-fuel streams. “Small is beautiful,” but the fact that the nuclear waste stream is small doesn’t mean that it’s not a problem; it’s just a “beautifully small” problem.</p>
<section id="sustainable-power-from-nuclear-fission" class="level2">
<h2 class="anchored" data-anchor-id="sustainable-power-from-nuclear-fission">“Sustainable” power from nuclear fission</h2>
<p>Figure 24.1 shows how much electricity was generated globally by nuclear power in 2007, broken down by country.</p>
<p>million tons uranium</p>
<p>Australia</p>
<p>1.14</p>
<p>Kazakhstan</p>
<p>0.82</p>
<p>Canada</p>
<p>0.44</p>
<p>USA</p>
<p>0.34</p>
<p>South Africa</p>
<p>0.34</p>
<p>Namibia</p>
<p>0.28</p>
<p>Brazil</p>
<p>0.28</p>
<p>Russian Federation</p>
<p>0.17</p>
<p>Uzbekistan</p>
<p>0.12</p>
<p>World total (conventional reserves in the ground)</p>
<p>4.7</p>
<p>Phosphate deposits</p>
<p>22</p>
<p>Seawater</p>
<p>4500</p>
<p><span class="figurenumber">Table 24.2</span>. Known recoverable resources of uranium. The top part of the table shows the “reasonable assured resources” and “inferred resources,” at cost less than $130 per kg of uranium, as of 1 Jan 2005. These are the estimated resources in areas where exploration has taken place. There’s also 1.3 million tons of depleted uranium sitting around in stockpiles, a by-product of previous uranium activities.</p>
<p><img src="img/without-hot-air/figure194.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 24.3</span>. Workers push uranium slugs into the X-10 Graphite Reactor.</p>
<p>Could nuclear power be “sustainable”? Leaving aside for a moment the usual questions about safety and waste-disposal, a key question is whether humanity could live for generations on fission. How great are the world wide supplies of uranium, and other fissionable fuels? Do we have only a few decades’ worth of uranium, or do we have enough for millennia?</p>
<p>To estimate a “sustainable” power from uranium, I took the total recoverable uranium in the ground and in seawater, divided it fairly between 6 billion humans, and asked “how fast can we use this if it has to last 1000 years?”</p>
<p>Almost all the recoverable uranium is in the oceans, not in the ground: seawater contains 3.3 mg of uranium per m<sup>3</sup> of water, which adds up to 4.5 billion tons worldwide. I called the uranium in the ocean “recoverable” but this is a bit inaccurate – most ocean waters are quite inaccessible, and the ocean conveyor belt rolls round only once every 1000 years or so; and no-one has yet demonstrated uranium-extraction from seawater on an in dustrial scale. So we’ll make separate estimates for two cases: first using only mined uranium, and second using ocean uranium too.</p>
<p>The uranium ore in the ground that’s extractable at prices below $130 per kg of uranium is about one thousandth of this. If prices went above $130 per kg, phosphate deposits that contain uranium at low concentrations would become economic to mine. Recovery of uranium from phosphates is perfectly possible, and was done in America and Belgium before 1998. For the estimate of mined uranium, I’ll add both the conventional uranium ore and the phosphates, to give a total resource of 27 million tons of uranium (table 24.2).</p>
<p>We’ll consider two ways to use uranium in a reactor: (a) the widely-used <em>once-through method</em> gets energy mainly from the <sup>235</sup>U (which makes up just 0.7% of uranium), and discards the remaining <sup>238</sup>U; (b) <em>fast breeder reactors</em>, which are more expensive to build, convert the <sup>238</sup>U to fissionable plutonium-239 and obtain roughly 60 times as much energy from the uranium. <a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<section id="once-through-reactors-using-uranium-from-the-ground" class="level3">
<h3 class="anchored" data-anchor-id="once-through-reactors-using-uranium-from-the-ground">Once-through reactors, using uranium from the ground</h3>
<p><img src="img/without-hot-air/figure195.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 24.4</span>. Three Mile Island nuclear power plant.</p>
<p>A once-through <strong>one-gigawatt</strong> nuclear power station uses <strong>162 tons per year of uranium</strong>. <a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> So the known mineable resources of uranium, shared between 6 billion people, would last for 1000 years if we produced nuclear power at a rate of <span class="green">0.55 kWh per day per person</span>. This sustainable rate is the output of just 136 nuclear power stations, and is half of today’s nuclear power production. It’s very possible this is an underestimate of uranium’s potential, since, as there is not yet a uranium shortage, there is no incentive for exploration and little uranium exploration has been undertaken since the 1980s; so maybe more mineable uranium will be discovered. Indeed, one paper published in 1980 estimated that the low-grade uranium resource is more than 1000 times greater than the 27 million tons we just assumed. <a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p>Could our current once-through use of mined uranium be sustainable? It’s hard to say, since there is such uncertainty about the result of future exploration. Certainly at today’s rate of consumption, once-through reactors could keep going for hundreds of years. But if we wanted to crank up nuclear power 40-fold worldwide, in order to get off fossil fuels and to allow standards of living to rise, we might worry that once-through reactors are not a sustainable technology.</p>
</section>
<section id="fast-breeder-reactors-using-uranium-from-the-ground" class="level3">
<h3 class="anchored" data-anchor-id="fast-breeder-reactors-using-uranium-from-the-ground">Fast breeder reactors, using uranium from the ground</h3>
<blockquote class="blockquote">
<p><em>(Figure omitted from this edition: third-party rights.)</em></p>
</blockquote>
<p><span class="figurenumber">Figure 24.5</span>. Dounreay Nuclear Power Development Establishment, whose primary purpose was the development of fast breeder reactor technology. Photo by John Mullen.</p>
<p>Uranium can be used 60 times more efficiently in fast breeder reactors, which burn up all the uranium – both the <sup>238</sup>U and the <sup>235</sup>U (in contrast to the once-through reactors, which burn mainly <sup>235</sup>U). As long as we don’t chuck away the spent fuel that is spat out by once-through reactors, this source of depleted uranium could be used too, so uranium that is put in once-through reactors need not be wasted. If we used all the mineable uranium (plus the depleted uranium stockpiles) in 60-times-more-efficient fast breeder reactors, the power would be <span class="green">33 kWh per day per person</span>. Attitudes to fast breeder reactors range from “this is a dangerous failed experimental technology whereof one should not speak” to “we can and should start building breeder reactors right away.” I am not competent to comment on the risks of breeder technology, and I don’t want to mix ethical assertions with factual assertions. My aim is just to help understand the numbers. The one ethical position I wish to push is “we should have a plan that adds up.”</p>
</section>
<section id="once-through-using-uranium-from-the-oceans" class="level3">
<h3 class="anchored" data-anchor-id="once-through-using-uranium-from-the-oceans">Once-through, using uranium from the oceans</h3>
<p>The oceans’ uranium, if completely extracted and used in once-through reactors, corresponds to a total energy of</p>
<p><span class="math display">\[
\begin{matrix}
\frac{\text{4.5\ billion\ tons\ per\ planet}}{\text{162\ tons\ uranium\ per\ GW-year}} \\
{\text{\quad\quad\quad} = \text{~28\ million\ GW-years\ per\ planet.}} \\
\end{matrix}
\]</span></p>
<p>How fast could uranium be extracted from the oceans? The oceans circulate slowly: half of the water is in the Pacific Ocean, and deep Pacific waters circulate to the surface on the great ocean conveyor only every 1600 years. Let’s imagine that 10% of the uranium is extracted over such a 1600-year period. That’s an extraction rate of 280 000 tons per year. In once-through reactors, this would deliver power at a rate of</p>
<p>2.8 million GW-years / 1600 years = 1750 GW,</p>
<p>which, shared between 6 billion people, is <span class="green">7 kWh per day per person</span>. (There’s currently 369 GW of nuclear reactors, so this figure corresponds to a 4-fold increase in nuclear power over today’s levels.) I conclude that ocean extraction of uranium would turn today’s once-through reactors into a “sustainable” option – assuming that the uranium reactors can cover the energy cost of the ocean extraction process.</p>
</section>
<section id="fast-breeder-reactors-using-uranium-from-the-oceans" class="level3">
<h3 class="anchored" data-anchor-id="fast-breeder-reactors-using-uranium-from-the-oceans">Fast breeder reactors, using uranium from the oceans</h3>
<p>If fast reactors are 60 times more efficient, the same extraction of ocean uranium could deliver <span class="green">420 kWh per day per person</span>. At last, a sustainable figure that beats current consumption! – but only with the joint help of two technologies that are respectively scarcely-developed and unfashionable: ocean extraction of uranium, and fast breeder reactors.</p>
</section>
<section id="using-uranium-from-rivers" class="level3">
<h3 class="anchored" data-anchor-id="using-uranium-from-rivers">Using uranium from rivers</h3>
<p>The uranium in the oceans is being topped up by rivers, which deliver uranium at a rate of 32 000 tons per year. If 10% of this influx were captured, it would provide enough fuel for 20 GW of once-through reactors, or 1200 GW of fast breeder reactors. The fast breeder reactors would deliver <span class="green">5 kWh per day per person</span>.</p>
<p>All these numbers are summarized in figure 24.6.</p>
<p><img src="img/without-hot-air/figure193.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 24.6</span>. “Sustainable” power from uranium. For comparison, world nuclear power production today is 1.2 kWh/d per person. British nuclear power production used to be 4 kWh/d per person and is declining.</p>
</section>
<section id="what-about-costs" class="level3">
<h3 class="anchored" data-anchor-id="what-about-costs">What about costs?</h3>
<p>As usual in this book, my main calculations have paid little attention to economics. However, since the potential contribution of ocean-uranium-based power is one of the biggest in our “sustainable” production list, it seems appropriate to discuss whether this uranium-power figure is at all economically plausible.</p>
<p>Japanese researchers have found a technique for extracting uranium from seawater <a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> at a cost of $100–300 per kilogram of uranium, in comparison with a current cost of about $20/kg for uranium from ore. Because uranium contains so much more energy per ton than traditional fuels, this 5-fold or 15-fold increase in the cost of uranium would have little effect on the cost of nuclear power: nuclear power’s price is dominated by the cost of power-station construction and decommissioning, not by the cost of the fuel. Even a price of $300/kg would increase the cost of nuclear energy by only about 0.3 p per kWh. The expense of uranium extraction could be reduced by combining it with another use of seawater – for example, power-station cooling. <a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<p>We’re not home yet: does the Japanese technique scale up? What is the energy cost of processing all the seawater? In the Japanese experiment, three cages full of adsorbent uranium-attracting material weighing 350 kg collected “more than 1 kg of yellow cake in 240 days;” this figure corresponds to about 1.6 kg per year. The cages had a cross-sectional area of 48 m<sup>2</sup>. To power a once-through 1 GW nuclear power station, we need 160 000 kg per year, which is a production rate 100 000 times greater than the Japanese experiment’s. If we simply scaled up the Japanese technique, which accumulated uranium passively from the sea, a power of 1 GW would thus need cages having a collecting area of 4.8 km<sup>2</sup> and containing a weight of 350 000 tons of adsorbent material – more than the weight of the steel in the reactor itself. To put these large numbers in human terms, if uranium were delivering, say, 22 kWh per day per person, each 1 GW reactor would be shared between 1 million people, each of whom needs 0.16 kg of uranium per year. So each person would require one tenth of the Japanese experimental facility, with a weight of 35 kg per person, and an area of <span class="darkblue">5 m<sup>2</sup></span> per person. The proposal that such uranium-extraction facilities should be created is thus similar in scale to proposals such as “every person should have <span class="darkblue">10 m<sup>2</sup></span> of solar panels” and “every person should have a one-ton car and a dedicated parking place for it.” A large investment, yes, but not absurdly off scale. And that was the calculation for once-through reactors. For fast breeder reactors, 60 times less uranium is required, so the mass per person of the uranium collector would be 0.5 kg.</p>
</section>
</section>
<section id="thorium" class="level2">
<h2 class="anchored" data-anchor-id="thorium">Thorium</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Country</th>
<th>Reserves (1000 tons)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Turkey</td>
<td>380</td>
</tr>
<tr class="even">
<td>Australia</td>
<td>300</td>
</tr>
<tr class="odd">
<td>India</td>
<td>290</td>
</tr>
<tr class="even">
<td>Norway</td>
<td>170</td>
</tr>
<tr class="odd">
<td>USA</td>
<td>160</td>
</tr>
<tr class="even">
<td>Canada</td>
<td>100</td>
</tr>
<tr class="odd">
<td>South Africa</td>
<td>35</td>
</tr>
<tr class="even">
<td>Brazil</td>
<td>16</td>
</tr>
<tr class="odd">
<td>Other countries</td>
<td>95</td>
</tr>
<tr class="even">
<td>World total</td>
<td>1580</td>
</tr>
</tbody>
</table>
<p><span class="figurenumber">Table 24.7</span>. Known world thorium resources in monazite (economically extractable). <a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<p>Thorium is a radioactive element similar to uranium. Formerly used to make gas mantles, it is about three times as abundant in the earth’s crust as uranium. Soil commonly contains around 6 parts per million of thorium, and some minerals contain 12% thorium oxide. Seawater contains little thorium, because thorium oxide is insoluble. Thorium can be completely burned up in simple reactors (in contrast to standard uranium reactors which use only about 1% of natural uranium). Thorium is used in nuclear reactors in India. If uranium ore runs low, thorium will probably become the dominant nuclear fuel.</p>
<p>Thorium reactors deliver 3.6 billion kWh of heat per ton of thorium, <a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> which implies that a 1 GW reactor requires about 6 tons of thorium per year, assuming its generators are 40% efficient. Worldwide thorium resources are estimated to total about 6 million tons, four times more than the known reserves shown in table 24.7. As with the uranium resources, it seems plausible that these thorium resources are an underestimate, since thorium prospecting is not highly valued today. If we assume, as with uranium, that these resources are used up over 1000 years and shared equally among 6 billion people, we find that the “sustainable” power thus generated is <span class="green">4 kWh/d per person</span>.</p>
<p><img src="img/without-hot-air/figure197.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 24.8</span>. Thorium options.</p>
<blockquote class="blockquote">
<p><em>(Figure omitted from this edition: third-party rights.)</em></p>
</blockquote>
<p><span class="figurenumber">Figure 24.9</span>. Sizewell’s power stations. Sizewell A, in the foreground, had a capacity of 420 MW, and was shut down at the end of 2006. Sizewell B, behind, has a capacity of 1.2 GW. Photo by William Connolley.</p>
<p>An alternative nuclear reactor for thorium, the “energy amplifier” or “accelerator-driven system” proposed by Nobel laureate Carlo Rubbia and his colleagues <a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> would, they estimated, convert 6 million tons of thorium to 15 000 TWy of energy, or 60 kWh/d per person over 1000 years. Assuming conversion to electricity at 40% efficiency, this would deliver <span class="green">24 kWh/d per person</span> for 1000 years. And the waste from the energy amplifier would be much less radioactive too. They argue that, in due course, many times more thorium would be economically extractable than the current 6 million tons. If their suggestion – 300 times more – is correct, then thorium and the energy amplifier could offer 120 kWh/d per person for 60 000 years.</p>
</section>
<section id="land-use" class="level2">
<h2 class="anchored" data-anchor-id="land-use">Land use</h2>
<p>Let’s imagine that Britain decides it is serious about getting off fossil fuels, and creates a lot of new nuclear reactors, even though this may not be “sustainable.” If we build enough reactors to make possible a significant decarbonization of transport and heating, can we fit the required nuclear reactors into Britain? The number we need to know is the power per unit area of nuclear power stations, which is about <span class="green">1000W/m<sup>2</sup></span> (figure 24.10). Let’s imagine generating 22 kWh per day per person of nuclear power – equivalent to 55 GW (roughly the same as France’s nuclear power), which could be delivered by 55 nuclear power stations, each occupying one square kilometre. That’s about 0.02% of the area of the country. Wind farms delivering the same average power would require 500 times as much land: 10% of the country. If the nuclear power stations were placed in pairs around the coast (length about 3000 km, at 5 km resolution), then there’d be two every 100 km. Thus while the area required is modest, the fraction of coastline gobbled by these power stations would be about 2% (2 kilometres in every 100).</p>
<blockquote class="blockquote">
<p><em>(Figure omitted from this edition: third-party rights.)</em></p>
</blockquote>
<p><span class="figurenumber">Figure 24.10</span>. Sizewell occupies less than 1 km<sup>2</sup>. The blue grid’s spacing is 1 km. © Crown copyright; Ordnance Survey.</p>
</section>
<section id="economics-of-cleanup" class="level2">
<h2 class="anchored" data-anchor-id="economics-of-cleanup">Economics of cleanup</h2>
<p>What’s the cost of cleaning up nuclear power sites? The nuclear decommissioning authority has an annual budget of £2 billion for the next 25 years. <a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a> The nuclear industry sold everyone in the UK 4 kWh/d for about 25 years, <a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a> so the nuclear decommissioning authority’s cost is 2.3 p/kWh. That’s a hefty subsidy – though not, it must be said, as hefty as the subsidy currently given to offshore wind (7 p/kWh).</p>
<p><span class="red">Erratum</span>: “The nuclear decommissioning authority has an annual budget of 2 billion.” In fact this is to clean up not only the civilian nuclear power stations but also the military nuclear-bomb-making facilities at Sellafield. The lion’s share of the money is thus cleaning up military mess, not civilian-power mess. This means I have overestimated the cost per kWh of cleaning up old civilian nuclear power.</p>
</section>
<section id="safety" class="level2">
<h2 class="anchored" data-anchor-id="safety">Safety</h2>
<p>The safety of nuclear operations in Britain remains a concern. The THORP reprocessing facility at Sellafield, built in 1994 at a cost of £1.8 billion, had a growing leak from a broken pipe from August 2004 to April 2005. Over eight months, the leak let <em><span class="darkblue">85 000 litres</span></em> of uranium-rich fluid flow into a sump which was equipped with safety systems that were designed to detect immediately any leak of as little as <em><span class="darkblue">15 litres</span></em>. But the leak went undetected because the operators hadn’t completed the checks that ensured the safety systems were working; and the operators were in the habit of ignoring safety alarms anyway.</p>
<p>The safety system came with belt and braces. Independent of the failed safety alarms, routine safety-measurements of fluids in the sump should have detected the abnormal presence of uranium within one month of the start of the leak; but the operators often didn’t bother taking these routine measurements, because they felt too busy; and when they <em>did</em> take measurements that detected the abnormal presence of uranium in the sump (on 28 August 2004, 26 November 2004, and 24 February 2005), no action was taken.</p>
<p>By April 2005, <em><span class="darkblue">22 tons</span></em> of uranium had leaked, but still none of the leak-detection systems detected the leak. The leak was finally detected by <em>accountancy</em>, when the bean-counters noticed that they were getting 10% less uranium out than their clients claimed they’d put in! Thank goodness this private company had a profit motive, hey? The criticism from the Chief Inspector of Nuclear Installations was withering: “The Plant was operated in a culture that seemed to allow instruments to operate in alarm mode rather than questioning the alarm and rectifying the relevant fault.” <a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a></p>
<p><img src="img/without-hot-air/figure199.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 24.11</span>. Death rates of electricity generation technologies. <span class="darkblue">x</span>: European Union estimates by the ExternE project. <span class="red">O</span>: Paul Scherrer Institute.</p>
<p>If we let private companies build new reactors, how can we ensure that higher safety standards are adhered to? I don’t know.</p>
<p>At the same time, we must not let ourselves be swept off our feet in horror at the danger of nuclear power. Nuclear power is not infinitely dangerous. It’s just dangerous, <a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a> much as coal mines, petrol repositories, fossil-fuel burning and wind turbines are dangerous. Even if we have no guarantee against nuclear accidents in the future, I think the right way to assess nuclear is to compare it objectively with other sources of power. Coal power stations, for example, expose the public to nuclear radiation, because coal ash typically contains uranium. Indeed, according to a paper published in the journal <em>Science</em>, people in America living near coal-fired power stations are exposed to higher radiation doses than those living near nuclear power plants. <a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a></p>
<p>When quantifying the public risks of different power sources, we need a new unit. I’ll go with “deaths per GWy (gigawatt-year).” Let me try to convey what it would mean if a power source had a death rate of 1 death per GWy. One gigawatt-year is the energy produced by a 1 GW power station, if it operates flat-out for one year. Britain’s electricity consumption is roughly 45 GW, or, if you like, 45 gigawatt-years per year. So if we got our electricity from sources with a death rate of 1 death per GWy, that would mean the British electricity supply system was killing 45 people per year. For comparison, 3000 people die per year on Britain’s roads. So, if you are <em>not</em> campaigning for the abolition of roads, you may deduce that “1 death per GWy” is a death rate that, while sad, you might be content to live with. Obviously, 0.1 deaths per GWy would be preferable, but it takes only a moment’s reflection to realize that, sadly, fossil-fuel energy production must have a cost greater than 0.1 deaths per GWy – just think of disasters on oil rigs; helicopters lost at sea; pipeline fires; refinery explosions; and coal mine accidents: there are tens of fossil-chain fatalities per year in Britain.</p>
<p>So, let’s discuss the actual death rates of a range of electricity sources. The death rates vary a lot from country to country. In China, for example, the death rate in coal mines, per ton of coal delivered, is 50 times that of most nations. Figure 24.11 shows numbers from studies by the Paul Scherrer Institute and by a European Union project called ExternE, which made comprehensive estimates of all the impacts of energy production. According to the EU figures, coal, lignite, and oil have the highest death rates, followed by peat and biomass-power, with death rates above 1 per GWy. Nuclear and wind are the best, with death rates below 0.2 per GWy. <a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a> Hydroelectricity is the best of all according to the EU study, but comes out worst in the Paul Scherrer Institute’s study, because the latter surveyed a different set of countries.</p>
<section id="inherently-safe-nuclear-power" class="level3">
<h3 class="anchored" data-anchor-id="inherently-safe-nuclear-power">Inherently safe nuclear power</h3>
<p>Spurred on by worries about nuclear accidents, engineers have devised many new reactors with improved safety features. The GT-MHR power plant, for example, is claimed to be inherently safe; and, moreover it has a higher efficiency of conversion of heat to electricity than conventional nuclear plants [<a href="http://gt-mhr.ga.com/"><span class="websitetitle">gt-mhr.ga.com</span></a>].</p>
<p><img src="img/without-hot-air/figure200.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 24.12</span>. Chernobyl power plant (top), and the abandoned town of Prypiat, which used to serve it (bottom). Photos by Nik Stanbridge.</p>
</section>
</section>
<section id="mythconceptions" class="level2">
<h2 class="anchored" data-anchor-id="mythconceptions">Mythconceptions</h2>
<p>Two widely-cited defects of nuclear power are construction costs, and waste. Let’s examine some aspects of these issues.</p>
<section id="building-a-nuclear-power-station-requires-huge-amounts-of-concrete-and-steel-materials-whose-creation-involves-huge-co2-pollution." class="level4">
<h4 class="anchored" data-anchor-id="building-a-nuclear-power-station-requires-huge-amounts-of-concrete-and-steel-materials-whose-creation-involves-huge-co2-pollution.">Building a nuclear power station requires huge amounts of concrete and steel, materials whose creation involves huge CO<sub>2</sub> pollution.</h4>
<p>The steel and concrete in a 1 GW nuclear power station have a carbon footprint of roughly 300 000 t CO<sub>2</sub>. <a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a></p>
<p>Spreading this “huge” number over a 25-year reactor life we can express this contribution to the carbon intensity in the standard units (g CO<sub>2</sub> per kWh(e)),</p>
<p><span class="math display">\[
\begin{matrix}
{\text{carbon\ intensity}\phantom{\text{construction}}} \\
\text{associated\ with\ construction} \\
{\quad = \ \frac{300 \times 10^{9}\text{~g}}{10^{6}\text{~kW(e)~} \times \text{~220\ 000\ h}}} \\
{= \ 1.4\text{~g/kWh(e),}\phantom{\text{constru}}} \\
\end{matrix}
\]</span></p>
<p>which is much smaller than the fossil-fuel benchmark of 400g CO<sub>2</sub>/kWh(e). The IPCC estimates that the total carbon intensity of nuclear power (including construction, fuel processing, and decommissioning) is less than 40 g CO<sub>2</sub>/kWh(e) (Sims et al., 2007).</p>
<p>Please don’t get me wrong: I’m not trying to be pro-nuclear. I’m just pro-arithmetic.</p>
</section>
<section id="isnt-the-waste-from-nuclear-reactors-a-huge-problem" class="level4">
<h4 class="anchored" data-anchor-id="isnt-the-waste-from-nuclear-reactors-a-huge-problem">Isn’t the waste from nuclear reactors a huge problem?</h4>
<p>As we noted in the opening of this chapter, the volume of waste from nuclear reactors is relatively small. Whereas the ash from ten coal-fired power stations would have a mass of four million tons per year (having a volume of roughly 40 litres per person per year), the nuclear waste from Britain’s ten nuclear power stations has a volume of just 0.84 litres per person per year – think of that as a bottle of wine per person per year (figure 24.13).</p>
<p>Most of this waste is low-level waste. 7% is intermediate-level waste, and just 3% of it – 25 ml per year – is high-level waste.</p>
<p>The high-level waste is the really nasty stuff. It’s conventional to keep the high-level waste at the reactor for its first 40 years. It is stored in pools of water and cooled. After 40 years, the level of radioactivity has dropped 1000-fold. The level of radioactivity continues to fall; after 1000 years, if we <em>reprocess</em> the waste, separating off the uranium and plutonium for use in new nuclear fuel, then after 1000 years, the radioactivity of the high-level waste is about the same as that of uranium ore. Thus waste storage engineers need to make a plan to secure high-level waste for about 1000 years. <a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a></p>
<p><img src="img/without-hot-air/figure201.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 24.13</span>. British nuclear waste, per person, per year, has a volume just a little larger than one wine bottle.</p>
<p>Is this a difficult problem? 1000 years is certainly a long time compared with the lifetimes of governments and countries! But the volumes are so small, I feel nuclear waste is only a minor worry, compared with all the other forms of waste we are inflicting on future generations. At 25 ml per year, a lifetime’s worth of high-level nuclear waste would amount to less than 2 litres. Even when we multiply by 60 million people, the lifetime volume of nuclear waste doesn’t sound unmanageable: 105 000 cubic metres. That’s the same volume as 35 olympic swimming pools. If this waste were put in a layer one metre deep, it would occupy just one tenth of a square kilometre.</p>
<p>There are already plenty of places that are off-limits to humans. I may not trespass in your garden. Nor should you in mine. We are neither of us welcome in Balmoral. “Keep out” signs are everywhere. Downing Street, Heathrow airport, military facilities, disused mines – they’re all off limits. Is it impossible to imagine making another one-square-kilometre spot – perhaps deep underground – off limits for 1000 years?</p>
<p>Compare this 25 ml per year per person of high-level nuclear waste with the other traditional forms of waste we currently dump: municipal waste – 517 kg per year per person; hazardous waste – 83 kg per year per person.</p>
<p>People sometimes compare possible new nuclear waste with the nuclear waste we already have to deal with, thanks to our existing old reactors. Here are the numbers for the UK. The projected volume of “higher activity wastes” up to 2120, following decommissioning of existing nuclear facilities, is 478 000 m<sup>3</sup>. Of this volume, 2% (about 10 000 m<sup>3</sup>) will be the high level waste (1290 m<sup>3</sup>) and spent fuel (8150 m<sup>3</sup>) that together contain 92% of the activity. Building 10 new nuclear reactors (10 GW) would add another 31 900 m<sup>3</sup> of spent fuel to this total. That’s the same volume as ten swimming pools.</p>
</section>
<section id="if-we-got-lots-and-lots-of-power-from-nuclear-fission-or-fusion-wouldnt-this-contribute-to-global-warming-because-of-all-the-extra-energy-being-released-into-the-environment" class="level4">
<h4 class="anchored" data-anchor-id="if-we-got-lots-and-lots-of-power-from-nuclear-fission-or-fusion-wouldnt-this-contribute-to-global-warming-because-of-all-the-extra-energy-being-released-into-the-environment">If we got lots and lots of power from nuclear fission or fusion, wouldn’t this contribute to global warming, because of all the extra energy being released into the environment?</h4>
<p><img src="img/without-hot-air/figure346.gif" class="img-fluid"></p>
<p>That’s a fun question. And because we’ve carefully expressed everything in this book in a single set of units, it’s quite easy to answer. First, let’s recap the key numbers about global energy balance from <a href="../Text/chap01.xhtml#Carbon">chapter 1</a>: the average solar power absorbed by atmosphere, land, and oceans is 238 W/m<sup>2</sup>; doubling the atmospheric CO<sub>2</sub> concentration would effectively increase the net heating by 4 W/m<sup>2</sup>. This 1.7% increase in heating is believed to be bad news for climate. Variations in solar power during the 11-year solar cycle have a range of 0.25 W/m<sup>2</sup>. So now let’s assume that in 100 years or so, the world population is 10 billion, and everyone is living at a European standard of living, using 125 kWh per day derived from fossil sources, from nuclear power, or from mined geothermal power. The area of the earth per person would be 51 000 m<sup>2</sup>. Dividing the power per person by the area per person, we find that the extra power contributed by human energy use would be 0.1 W/m<sup>2</sup>. That’s one fortieth of the 4 W/m<sup>2</sup> that we’re currently fretting about, and a little smaller than the 0.25 W/m<sup>2</sup> effect of solar variations. So yes, under these assumptions, human power production would <em>just</em> show up as a contributor to global climate change.</p>
</section>
<section id="i-heard-that-nuclear-power-cant-be-built-at-a-sufficient-rate-to-make-a-useful-contribution." class="level4">
<h4 class="anchored" data-anchor-id="i-heard-that-nuclear-power-cant-be-built-at-a-sufficient-rate-to-make-a-useful-contribution.">I heard that nuclear power can’t be built at a sufficient rate to make a useful contribution.</h4>
<p><img src="img/without-hot-air/figure202.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 24.14</span>. Graph of the total nuclear power in the world that was built since 1967 and that is still operational today. The world construction rate peaked at 30 GW of nuclear power per year in 1984.</p>
<p>The difficulty of building nuclear power fast has been exaggerated with the help of a misleading presentation technique I call “the magic playing field.” In this technique, two things appear to be compared, but the basis of the comparison is switched halfway through. The Guardian’s environment editor, summarizing a report from the <em>Oxford Research Group</em>, wrote “For nuclear power to make any significant contribution to a reduction in global carbon emissions in the next two generations, the industry would have to construct nearly 3000 new reactors – or about one a week for 60 years. A civil nuclear construction and supply programme on this scale is a pipe dream, and completely unfeasible. The highest historic rate is 3.4 new reactors a year.” 3000 sounds much bigger than 3.4, doesn’t it! In this application of the “magic playing field” technique, there is a switch not only of <span class="red">timescale</span> but also of <span class="darkblue">region</span>. While the first figure (3000 new reactors <span class="red">over 60 years</span>) is the number required <em><span class="darkblue">for the whole planet</span></em>, the second figure (3.4 new reactors <span class="red">per year</span>) is the maximum rate of building by a <em><span class="darkblue">single country</span></em> (France)!</p>
<p>A more honest presentation would have kept the comparison on a per-planet basis. France has 59 of the world’s 429 operating nuclear reactors, so it’s plausible that the highest rate of reactor building for the whole planet was something like ten times France’s, that is, 34 new reactors per year. And the required rate (3000 new reactors over 60 years) is 50 new reactors per year. So the assertion that “civil nuclear construction on this scale is a pipe dream, and completely unfeasible” is poppycock. Yes, it’s a big construction rate, but it’s in the same ballpark as historical construction rates.</p>
<p>How reasonable is my assertion that the world’s maximum historical construction rate must have been about 34 new nuclear reactors per year? Let’s look at the data. Figure 24.14 shows the power of the world’s nuclear fleet as a function of time, showing only the power stations still operational in 2007. The rate of new build was biggest in 1984, and had a value of (drum-roll please…) about 30 GW per year – about 30 1-GW reactors. So there!</p>
</section>
</section>
<section id="what-about-nuclear-fusion" class="level2">
<h2 class="anchored" data-anchor-id="what-about-nuclear-fusion">What about nuclear fusion?</h2>
<blockquote class="blockquote">
<p><em>We say that we will put the sun into a box. The idea is pretty. The problem is, we don’t know how to make the box.</em></p>
<p>S´ebastien Balibar, Director of Research, CNRS</p>
</blockquote>
<blockquote class="blockquote">
<p><em>(Figure omitted from this edition: third-party rights.)</em></p>
</blockquote>
<p><span class="figurenumber">Figure 24.15</span>. The inside of an experimental fusion reactor. Split image showing the JET vacuum vessel with a superimposed image of a JET plasma, taken with an ordinary TV camera. Photo: EFDA-JET.</p>
<blockquote class="blockquote">
<p><em>(Figure omitted from this edition: third-party rights.)</em></p>
</blockquote>
<p><span class="figurenumber">Figure 24.16</span>. Lithium-based fusion, if used fairly and “sustainably,” could match our current levels of consumption. Mined lithium would deliver 10 kWh/d per person for 1000 years; lithium extracted from seawater could deliver 105 kWh/d per person for over a million years.</p>
<p>Fusion power is speculative and experimental. I think it is reckless to assume that the fusion problem <em>will</em> be cracked, but I’m happy to estimate how much power fusion could deliver, <em>if</em> the problem is cracked.</p>
<p>The two fusion reactions that are considered the most promising are:</p>
<p><strong>the DT reaction</strong>, which fuses deuterium with tritium, making helium; and</p>
<p><strong>the DD reaction</strong>, which fuses deuterium with deuterium.</p>
<p>Deuterium, a naturally occurring heavy isotope of hydrogen, can be obtained from seawater; tritium, a heavier isotope of hydrogen, isn’t found in large quantities naturally (because it has a half-life of only 12 years) but it can be manufactured from lithium.</p>
<p>ITER is an international project to figure out how to make a steadily working fusion reactor. The ITER prototype will use the DT reaction. DT is preferred over DD, because the DT reaction yields more energy and because it requires a temperature of “only” 100 million °C to get it going, whereas the DD reaction requires 300 million °C. (The maximum temperature in the sun is 15 million °C.)</p>
<p>Let’s fantasize, and assume that the ITER project is successful. What sustainable power could fusion then deliver? Power stations using the DT reaction, fuelled by lithium, will run out of juice when the lithium runs out. Before that time, hopefully the second installment of the fantasy will have arrived: fusion reactors using deuterium alone.</p>
<p>I’ll call these two fantasy energy sources “lithium fusion” and “deuterium fusion,” naming them after the principal fuel we’d worry about in each case. Let’s now estimate how much energy each of these sources could deliver.</p>
<section id="lithium-fusion" class="level3">
<h3 class="anchored" data-anchor-id="lithium-fusion">Lithium fusion</h3>
<p>World lithium reserves are estimated to be 9.5 million tons in ore deposits. <a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a> If all these reserves were devoted to fusion over 1000 years, the power delivered would be <span class="green">10 kWh/d per person</span>.</p>
<p>There’s another source for lithium: seawater, where lithium has a concentration of 0.17 ppm. <a href="#fn19" class="footnote-ref" id="fnref19" role="doc-noteref"><sup>19</sup></a> To produce lithium at a rate of 100 million kg per year from seawater is estimated to have an energy requirement of 2.5 kWh(e) per gram of lithium. If the fusion reactors give back 2300 kWh(e) per gram of lithium, the power thus delivered would be 105 kWh/d per person (assuming 6 billion people). At this rate, the lithium in the oceans would last more than a million years. <a href="#fn20" class="footnote-ref" id="fnref20" role="doc-noteref"><sup>20</sup></a></p>
<p><img src="img/without-hot-air/figure203.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 24.17</span>. Deuterium-based fusion, if it is achievable, offers plentiful sustainable energy for millions of years. This diagram’s scale is shrunk ten-fold in each dimension so as to fit fusion’s potential contribution on the page. The red and green stacks from figure 18.1 are shown to the same scale, for comparison.</p>
</section>
<section id="deuterium-fusion" class="level3">
<h3 class="anchored" data-anchor-id="deuterium-fusion">Deuterium fusion</h3>
<p>If we imagine that scientists and engineers crack the problem of getting the DD reaction going, we have some very good news. There’s 33 g of deuterium in every ton of water, and the energy that would be released from fusing just one gram of deuterium is a mind-boggling 100 000 kWh. Bearing in mind that the mass of the oceans is 230 million tons per person, we can deduce that there’s enough deuterium to supply every person in a ten-fold increased world population with a power of 30 000 kWh per day (that’s more than 100 times the average American consumption) for 1 million years (figure 24.17).</p>
</section>
</section>
<section id="notes-and-further-reading" class="level2">
<h2 class="anchored" data-anchor-id="notes-and-further-reading">Notes and further reading</h2>
<p>[<a href="http://tinyurl.com/yju4a4"><span class="websitetitle">yju4a4</span></a>] omits the figure for Turkey, which is found here: [<a href="http://tinyurl.com/yeyr7z"><span class="websitetitle">yeyr7z</span></a>].</p>
<p>Further reading about fission: Hodgson (1999), Nuttall (2004), Rogner (2000), Williams (2000). Uranium Information Center – <a href="http://www.uic.com.au/"><span class="websitetitle">www.uic.com.au</span></a>. <a href="http://www.world-nuclear.org/"><span class="websitetitle">www.world-nuclear.org</span></a>, [<a href="http://tinyurl.com/wnchw"><span class="websitetitle">wnchw</span></a>]. On costs: Zaleski (2005). On waste repositories: [<a href="http://tinyurl.com/shrln"><span class="websitetitle">shrln</span></a>]. On breeder reactors and thorium: <a href="http://www.energyfromthorium.com/"><span class="websitetitle">www.energyfromthorium.com</span></a>.</p>
<p>Further reading about fusion: <a href="http://www.fusion.org.uk/"><span class="websitetitle">www.fusion.org.uk</span></a>, <a href="http://www.askmar.com/Fusion.html"><span class="websitetitle">www.askmar.com/Fusion.html</span></a>.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p><em>Figure 24.1</em>. Source: World Nuclear Association [<a href="http://tinyurl.com/5qntkb"><span class="websitetitle">5qntkb</span></a>]. The total capacity of operable nuclear reactors is 372 GW(e), using 65 000 tons of uranium per year. The USA has 99 GW, France 63.5 GW, Japan 47.6 GW, Russia 22 GW, Germany 20 GW, South Korea 17.5 GW, Ukraine 13 GW, Canada 12.6 GW, and UK 11 GW. In 2007 all the world’s reactors generated 2608 TWh of electricity, which is an average of 300 GW, or <span class="green">1.2 kWh per day per person</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><em>Fast breeder reactors obtain 60 times as much energy from the uranium</em>. Source: <a href="http://www.world-nuclear.org/info/inf98.html"><span class="websitetitle">www.world-nuclear.org/info/inf98. html</span></a>. Japan currently leads the development of fast breeder reactors.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><em>A once-through one-gigawatt nuclear power station uses 162 tons per year of uranium</em>. Source: <a href="http://www.world-%20nuclear.org/info/inf03.html"><span class="websitetitle">www.world-nuclear.org/info/inf03.html</span></a>. A 1 GW(e) station with a thermal efficiency of 33% running at a load factor of 83% has the following upstream footprint: mining – 16 600 tons of 1%-uranium ore; milling – 191 t of uranium oxide (containing 162 t of natural uranium); enrichment and fuel fabrication – 22.4 t of uranium oxide (containing 20 t of enriched uranium). The enrichment requires 115 000 SWU; see p102 for the energy cost of SWU (separative work units).<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><em>it’s been estimated that the low-grade uranium resource is more than 1000 times greater than the 22 million tons we just assumed</em>. Deffeyes and MacGregor (1980) estimate that the resource of uranium in concentrations of 30 ppm or more is 3×10<sup>10</sup> tons. (The average ore grade processed in South Africa in 1985 and 1990 was 150 ppm. Phosphates typically average 100 ppm.) Here’s what the World Nuclear Association said on the topic of uranium reserves in June 2008: “From time to time concerns are raised that the known resources might be insufficient when judged as a multiple of present rate of use. But this is the Limits to Growth fallacy, … which takes no account of the very limited nature of the knowledge we have at any time of what is actually in the Earth’s crust. Our knowledge of geology is such that we can be confident that identified resources of metal minerals are a small fraction of what is there.”Measured resources of uranium, the amount known to be economically recoverable from orebodies, are … dependent on the intensity of past exploration effort, and are basically a statement about what is known rather than what is there in the Earth’s crust. “The world’s present measured resources of uranium (5.5 Mt) … are enough to last for over 80 years. This represents a higher level of assured resources than is normal for most minerals. Further exploration and higher prices will certainly, on the basis of present geological knowledge, yield further resources as present ones are used up.” “Economically rational players will only invest in finding these new reserves when they are most confident of gaining a return from them, which usually requires positive price messages caused by undersupply trends. If the economic system is working correctly and maximizing capital efficiency, there should never be more than a few decades of any resource commodity in reserves at any point in time.” [Exploration has a cost; exploring for uranium, for example, has had a cost of $1–$1.50 per kg of uranium ($3.4/MJ), which is 2% of the spot price of $78/kgU; in contrast, the finding costs of crude oil have averaged around $6/barrel ($1050/MJ) (12% of the spot price) over at least the past three decades.] “Unlike the metals which have been in demand for centuries, society has barely begun to utilize uranium. There has been only one cycle of exploration-discovery-production, driven in large part by late 1970s price peaks.”It is premature to speak about long-term uranium scarcity when the entire nuclear industry is so young that only one cycle of resource replenishment has been required.” <a href="http://www.world-nuclear.org/info/inf75.html"><span class="websitetitle">www.world-nuclear.org/info/inf75.html</span></a> Further reading: Herring (2004); Price and Blaise (2002); Cohen (1983). The IPCC, citing the OECD, project that at the 2004 utilization levels, the uranium in conventional resources and phosphates would last 670 years in once-through reactors, 20 000 years in fast reactors with plutonium recycling, and 160 000 years in fast reactors recycling uranium and all actinides (Sims et al., 2007).<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p><em>Japanese researchers have found a technique for extracting uranium from seawater</em>. The price estimate of $100 per kg is from Seko et al.&nbsp;(2003) and [<a href="http://tinyurl.com/y3wnzr"><span class="websitetitle">y3wnzr</span></a>]; the estimate of $300 per kg is from OECD Nuclear Energy Agency (2006, p130). The uranium extraction technique involves dunking tissue in the ocean for a couple of months; the tissue is made of polymer fibres that are rendered sticky by irradiating them before they are dunked; the sticky fibres collect uranium to the tune of 2 g of uranium per kilogram of fibre.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p><em>The expense of uranium extraction could be reduced by combining it with another use of seawater – for example, power-station cooling</em>. The idea of a nuclear-powered island producing hydrogen was floated by C. Marchetti. Breeder reactors would be cooled by seawater and would extract uranium from the cooling water at a rate of 600 t uranium per 500 000 Mt of seawater.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p><em>World thorium resources in monazite</em>. source: US Geological Survey, Mineral Commodity Summaries, January 1999. [<a href="http://tinyurl.com/yl7tkm"><span class="websitetitle">yl7tkm</span></a>] Quoted in UIC Nuclear Issues Briefing Paper #67 November 2004. “Other ore minerals with higher thorium contents, such as thorite, would be more likely sources if demand significantly increased.”<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p><em>Thorium reactors deliver 3.6×10<sup>9</sup> kWh of heat per ton of thorium</em>. Source: <a href="http://www.world-nuclear.org/info/inf62.html"><span class="websitetitle">www.world-nuclear.org/info/inf62.html</span></a>. There remains scope for advancement in thorium reactors, so this figure could be bumped up in the future.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p><em>An alternative nuclear reactor for thorium, the “energy amplifier”…</em> See Rubbia et al.&nbsp;(1995), <a href="http://web.ift.uib.no/~lillestol/Energy_Web/EA.html"><span class="websitetitle">web.ift.uib.no/~lillestol/Energy_Web/EA.html</span></a>, [<a href="http://tinyurl.com/32t5zt"><span class="websitetitle">32t5zt</span></a>], [<a href="http://tinyurl.com/2qr3yr"><span class="websitetitle">2qr3yr</span></a>], [<a href="http://tinyurl.com/ynk54y"><span class="websitetitle">ynk54y</span></a>].<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p><em>The nuclear decommissioning authority has an annual budget of £2 billion</em>. In fact, this clean-up budget seems to rise and rise. The latest figure for the total cost of decommissioning is £73 billion. <a href="http://news.bbc.co.uk/1/hi/uk/7215688.stm"><span class="websitetitle">news.bbc.co.uk/1/hi/uk/7215688.stm</span></a><a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p><em>The nuclear industry sold everyone in the UK 4 kWh/d for about 25 years</em>. The total generated to 2006 was about 2200 TWh. Source: Stephen Salter’s Energy Review for the Scottish National Party.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p><em>The criticism of the Chief Inspector of Nuclear Installations was withering…</em> (Weightman, 2007).<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p><em>Nuclear power is not infinitely dangerous. It’s just dangerous</em>. Further reading on risk: Kammen and Hassenzahl (1999).<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p><em>People in America living near coal-fired power stations are exposed to higher radiation doses than those living near nuclear power plants</em>. Source: McBride et al.&nbsp;(1978). Uranium and thorium have concentrations of roughly 1 ppm and 2 ppm respectively in coal. Further reading: <a href="http://gabe.web.psi.ch/research/ra/ra_res.html"><span class="websitetitle">gabe.web.psi.ch/research/ra/ra_res.html</span></a>, <a href="http://www.physics.ohio-state.edu/~wilkins/energy/Companion/E20.12.pdf.xpdf"><span class="websitetitle">www.physics.ohio-state.edu/~wilkins/energy/Companion/E20.12.pdf.xpdf</span></a>.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p><em>Nuclear power and wind power have the lowest death rates</em>. See also Jones (1984). These death rates are from studies that are predicting the future. We can also look in the past. In Britain, nuclear power has generated 200 GWy of electricity, and the nuclear industry has had 1 fatality, a worker who died at Chapelcross in 1978 [<a href="http://tinyurl.com/4f2ekz"><span class="websitetitle">4f2ekz</span></a>]. One death per 200 GWy is an impressively low death rate compared with the fossil fuel industry. Worldwide, the nuclear-power historical death rate is hard to estimate. The Three Mile Island meltdown killed no-one, and the associated leaks are estimated to have perhaps killed one person in the time since the accident. The accident at Chernobyl first killed 62 who died directly from exposure, and 15 local people who died later of thyroid cancer; it’s estimated that nearby, another 4000 died of cancer, and that worldwide, about 5000 people (among 7 million who were exposed to fallout) died of cancer because of Chernobyl (Williams and Baverstock, 2006); but these deaths are impossible to detect because cancers, many of them caused by natural nuclear radiation, already cause 25% of deaths in Europe. One way to estimate a global death rate from nuclear power worldwide is to divide this estimate of Chernobyl’s deathtoll (9000 deaths) by the cumulative output of nuclear power from 1969 to 1996, which was 3685 GWy. This gives a death rate of 2.4 deaths per GWy. As for deaths attributed to wind, Caithness Windfarm Information Forum <a href="http://www.caithnesswindfarms.co.uk/"><span class="websitetitle">www.caithnesswindfarms.co.uk</span></a> list 49 fatalities worldwide from 1970 to 2007 (35 wind industry workers and 14 members of the public). In 2007, Paul Gipe listed 34 deaths total worldwide [<a href="http://www.wind-works.org/articles/BreathLife.html"><span class="websitetitle">www.wind-works.org/articles/BreathLife.html</span></a>]. In the mid-1990s the mortality rate associated with wind power was 3.5 deaths per GWy. According to Paul Gipe, the worldwide mortality rate of wind power dropped to 1.3 deaths per GWy by the end of 2000. So the historical death rates of both nuclear power and wind are higher than the predicted future death rates.<a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p><em>The steel and concrete in a 1 GW nuclear power station have a carbon footprint of roughly 300 000 t CO<sub>2</sub></em>. A 1 GW nuclear power station contains 520 000 m<sup>3</sup> of concrete (1.2 million tons) and 67 000 tons of steel [<a href="http://tinyurl.com/2k8y7o"><span class="websitetitle">2k8y7o</span></a>]. Assuming 240 kg CO<sub>2</sub> per m<sup>3</sup> of concrete [<a href="http://tinyurl.com/3pvf4j"><span class="websitetitle">3pvf4j</span></a>], the concrete’s footprint is around 100 000 t CO<sub>2</sub>. From Blue Scope Steel [<a href="http://tinyurl.com/4r7zpg"><span class="websitetitle">4r7zpg</span></a>], the footprint of steel is about 2.5 tons of CO<sub>2</sub> per ton of steel. So the 67 000 tons of steel has a footprint of about 170 000 tons of CO<sub>2</sub>.<a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17"><p><em>Nuclear waste discussion</em>. Sources: <a href="http://www.world-nuclear.org/info/inf04.html"><span class="websitetitle">www.world-nuclear.org/info/inf04.html</span></a>, [<a href="http://tinyurl.com/49hcnw"><span class="websitetitle">49hcnw</span></a>], [<a href="http://tinyurl.com/3kduo7"><span class="websitetitle">3kduo7</span></a>]. New nuclear waste compared with old. Committee on Radioactive Waste Management (2006).<a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18"><p><em>World <span id="lithium">lithium reserves</span> are estimated as 9.5 million tons</em>. The main lithium sources are found in Bolivia (56.6%), Chile (31.4%) and the USA (4.3%). <a href="http://www.dnpm.gov.br/"><span class="websitetitle">www.dnpm.gov.br</span></a><a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn19"><p><em>There’s another source for lithium: seawater…</em> Several extraction techniques have been investigated (Steinberg and Dang, 1975; Tsuruta, 2005; Chitrakar et al., 2001).<a href="#fnref19" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn20"><p><em>Fusion power from lithium reserves.</em> The energy density of natural lithium is about 7500 kWh per gram (Ongena and Van Oost, 2006). There’s considerable variation among the estimates of how efficiently fusion reactors would turn this into electricity, ranging from 310 kWh(e)/g (Eckhartt, 1995) to 3400 kWh(e)/g of natural lithium (Steinberg and Dang, 1975). I’ve assumed 2300 kWh(e)/g, based on this widely quoted summary figure: “A 1 GW fusion plant will use about 100 kg of deuterium and 3 tons of natural lithium per year, generating about 7 billion kWh.” [<a href="http://tinyurl.com/69vt8r"><span class="websitetitle">69vt8r</span></a>], [<a href="http://tinyurl.com/6oby22"><span class="websitetitle">6oby22</span></a>], [<a href="http://tinyurl.com/63l2lp"><span class="websitetitle">63l2lp</span></a>].<a href="#fnref20" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/chap23.html" class="pagination-link" aria-label="23 Sustainable fossil fuels?">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">23 Sustainable fossil fuels?</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/chap25.html" class="pagination-link" aria-label="25 Living on other countries’ renewables?">
        <span class="nav-page-text"><span class="chapter-title">25 Living on other countries’ renewables?</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>