<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>28a The value of renewable energy as it scales – Sustainable Energy — Without the Hot Air</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/chap29.html" rel="next">
<link href="../chapters/chap28.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1b15cd7dfe5d645daabccee077c4b062.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chap19.html">Part II · Making a difference</a></li><li class="breadcrumb-item"><a href="../chapters/chap-value-of-renewables.html"><span class="chapter-title">28a The value of renewable energy as it scales</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Sustainable Energy — Without the Hot Air</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About this edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I · Numbers, not adjectives</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap01.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1 Motivations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap02.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2 The balance sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap03.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3 Cars</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap04.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4 Wind</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap05.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5 Planes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap06.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6 Solar</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap07.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7 Heating and cooling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap08.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8 Hydroelectricity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap09.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">9 Light</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap10.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10 Offshore wind</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap11.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11 Gadgets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap11a.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11a The machines behind the screen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap12.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12 Wave</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap13.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13 Food and farming</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap14.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14 Tide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap15.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15 Stuff</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap16.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">16 Geothermal</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap17.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17 Public services</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap18.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18 Can we live on renewables?</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II · Making a difference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap19.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19 Every BIG helps</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap20.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20 Better transport</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap21.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">21 Smarter heating</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap22.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">22 Efficient electricity use</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap23.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">23 Sustainable fossil fuels?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap24.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">24 Nuclear?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap25.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">25 Living on other countries’ renewables?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap26.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">26 Fluctuations and storage</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap27.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">27 Five energy plans for Britain</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap28.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">28 Putting costs in perspective</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap-value-of-renewables.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">28a The value of renewable energy as it scales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap29.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">29 What to do now</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap30.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">30 Energy plans for Europe, America, and the World</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap31.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">31 The last thing we should talk about</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap32.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">32 Saying yes</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III · Technical chapters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapA.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">A Cars II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapB.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">B Wind II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapC.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">C Planes II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapD.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">D Solar II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapE.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">E Heating II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapF.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">F Waves II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapG.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">G Tide II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapH.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">H Stuff II</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV · Useful data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapI.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">I Quick reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapJ.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">J Populations and areas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapK.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">K UK energy history</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapL.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">L The world in 2025</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapM.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">M Energy return on investment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapN.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">N Peak oil, peak gas, peak uranium</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/charts.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Charts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/bibliography.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bibliography</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/author.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The author</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/acknowledgments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Acknowledgments</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#storage-and-the-demand-that-arrives-with-the-supply" id="toc-storage-and-the-demand-that-arrives-with-the-supply" class="nav-link active" data-scroll-target="#storage-and-the-demand-that-arrives-with-the-supply">Storage, and the demand that arrives with the supply</a></li>
  <li><a href="#what-a-twenty-year-guarantee-costs-when-the-value-falls" id="toc-what-a-twenty-year-guarantee-costs-when-the-value-falls" class="nav-link" data-scroll-target="#what-a-twenty-year-guarantee-costs-when-the-value-falls">What a twenty-year guarantee costs when the value falls</a>
  <ul class="collapse">
  <li><a href="#one-argument-to-be-careful-with" id="toc-one-argument-to-be-careful-with" class="nav-link" data-scroll-target="#one-argument-to-be-careful-with">One argument to be careful with</a></li>
  </ul></li>
  <li><a href="#whose-money-and-whose-bill" id="toc-whose-money-and-whose-bill" class="nav-link" data-scroll-target="#whose-money-and-whose-bill">Whose money, and whose bill</a></li>
  <li><a href="#what-it-costs-to-build-against-what-it-earns" id="toc-what-it-costs-to-build-against-what-it-earns" class="nav-link" data-scroll-target="#what-it-costs-to-build-against-what-it-earns">What it costs to build against what it earns</a></li>
  <li><a href="#the-same-comparison-for-a-country-that-imports-its-fuel" id="toc-the-same-comparison-for-a-country-that-imports-its-fuel" class="nav-link" data-scroll-target="#the-same-comparison-for-a-country-that-imports-its-fuel">The same comparison, for a country that imports its fuel</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chap19.html">Part II · Making a difference</a></li><li class="breadcrumb-item"><a href="../chapters/chap-value-of-renewables.html"><span class="chapter-title">28a The value of renewable energy as it scales</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">28a The value of renewable energy as it scales</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><em>Editor’s note: this chapter is new in the 2026 revision. It is not David MacKay’s writing. It extends his balance-sheet method into a question the 2008 book leaves largely open: what happens to the economic value of renewable electricity as it grows to the scale the balance sheet calls for. Written by Örjan Lundberg; every figure is sourced.</em></p>
<p>MacKay’s book answers one question with great care. Can sustainable sources physically supply as much energy as we consume? The balance sheet adds up kWh per person per day on each side and asks whether the green stack can match the red. By 2026 the answer, for electricity at least, is yes in many places. The physical potential is real, and the cost of building it has fallen a long way: solar modules cost about a twentieth of their 2008 price, utility-scale solar electricity about a tenth of its 2010 cost, and onshore wind and battery costs have fallen steeply too.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/without-hot-air/fig-cost-decline.svg" class="img-fluid figure-img"></p>
<figcaption>Global levelized cost of electricity, 2010 against 2024 (USD/MWh, IRENA weighted average). Solar PV fell from 417 to 43, onshore wind 113 to 34, offshore wind 208 to 79.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/without-hot-air/fig-uk-electricity-mix.svg" class="img-fluid figure-img"></p>
<figcaption>UK electricity generation by source, 1985 to 2025, in TWh per year. Coal, the incumbent MacKay wrote around, supplied about 124 TWh in 2008 and essentially none by 2025; wind rose from 7 to 86 TWh and solar from nothing to 19.</figcaption>
</figure>
</div>
<p>The British grid MacKay described has already changed in one respect that matters for the rest of the book. In 2008 coal was the incumbent baseload at about 124 TWh; the last coal power station closed in September 2024, and by 2025 coal supplied essentially none of Britain’s electricity. Wind grew twelvefold over the same period, solar from nothing, and bioenergy fourfold, while gas and nuclear both fell.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> MacKay’s arithmetic is untouched, since it concerns physical potential and holds whatever the starting mix. What moves is the baseline of several later chapters: the five energy plans of Chapter 27, the nuclear question of Chapter 24 and the fossil-fuel discussion of Chapter 23 were written against a coal-heavy grid that no longer exists. Where a chapter’s argument leans on that baseline, this edition flags it.</p>
<p>A second question then takes over, and the 2008 book barely touches it, because in 2008 there was not yet enough weather-dependent generation for it to bite. The question is what a unit of renewable electricity is worth once a great deal of it has been built.</p>
<p>A wind turbine or a solar panel has no fuel cost, so it bids into the electricity market at close to zero and sets the price in every hour it runs. Add more panels and the price falls in exactly the sunny hours when they all produce at once, because their output is correlated. The revenue each panel earns per unit of energy therefore falls as more panels are built. This is not a market failure. It is the market working. The effect has a name, cannibalization, and a measure, the capture price: the average price a generator actually realises, weighted by its own output, rather than the flat average price.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p>The gap is already large. In the German solar market the capture price has fallen as installed capacity has grown, and in a detailed study of the Swedish system a wind-dominated 2035 shows one thousand to fifteen hundred hours a year at a price of zero.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> Weather-dependent generators earn the lowest per-unit prices of any source, because they are all selling at once.</p>
<p>Britain shows the same pattern in measured data rather than in a model. Across 2025, GB wind captured about 90% of the average market price and solar about 82%, the only two sources below the average, while gas earned a premium of almost 20% by running in the scarce hours and nuclear sat at the average.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/without-hot-air/fig-gb-capture.svg" class="img-fluid figure-img"></p>
<figcaption>GB electricity in 2025: capture price by source against the system-average market-index price. Wind and solar are the only sources below the average; gas earns a scarcity premium and nuclear sits at baseload.</figcaption>
</figure>
</div>
<p>This changes the useful question. MacKay asks how much we can build. Once it is built, the question becomes what absorbs the surplus, because whatever drains the cheap hours decides where the value lands. A study of the German energy system to 2045 makes the point sharply: a system short of flexibility does not deliver cheap power. It delivers a wider spread of prices, with both more zero-price hours and a higher average price, because the peak still has to be covered by plant that now earns its keep in fewer hours.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<p>The surplus does not reach demand on its own. Between the cheap hours and the demand that would use them stand two gates. The first is a price gate. A flat per-unit electricity tax puts a floor under what a buyer pays, so however deep the surplus goes the delivered cost stops falling, and the strongest signal a market can send, a negative price, never reaches the meter. Sweden and Finland run the cleanest natural experiment on this. With comparable district-heating hardware but opposite tax treatment, Finnish electric boilers supplied about 8% of district heat in 2025 while the larger Swedish fleet sat almost idle.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> The second gate is physical. A project can be economic on every hour of the year and still wait years for a grid connection, or be refused one.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
<section id="storage-and-the-demand-that-arrives-with-the-supply" class="level2">
<h2 class="anchored" data-anchor-id="storage-and-the-demand-that-arrives-with-the-supply">Storage, and the demand that arrives with the supply</h2>
<p>There is a way to undo much of the cannibalization, and MacKay half-describes it already. If something consumes the surplus in the hours it appears, the trough is filled, the price recovers, and the capture price stops falling. Storage does this from the supply side. A pumped-hydro scheme like Dinorwig, which MacKay treats in Chapter 26, “Fluctuations and storage”, buys power when it is cheap and sells it when it is dear, which is the same as buying in the surplus hours and selling in the scarce ones. Heat storage does it from the demand side. A district-heating system with a hot-water store can run its electric boilers when power is cheap and coast on the store when it is not, which is why Finland’s boilers earn their keep while Sweden’s, taxed at a flat rate and with little storage behind them, sit idle.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></p>
<p>Storage does not escape the trap it is meant to cure. A battery earns from the spread between cheap and dear hours, and as more batteries are built they all charge in the same cheap hours and discharge in the same dear ones, narrowing the spread they live on. The revenue figures already show it: in California the arbitrage revenue a battery earns has fallen year after year, and the Australian market has reached record lows.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a> A generator competes away its capture price and a battery competes away its spread; the effect is general, and it reaches every resource whose value comes from a price signal. No single store answers every duration, either: lithium-ion is the cheapest way to shift energy across a few hours and among the dearest to shift it across a hundred, so the merit order of storage inverts as the duration lengthens. Batteries cover the daily swing, and the seasonal balance needs another technology, or demand that can wait.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a></p>
<p>This is why a purely merchant market under-builds the system as a whole, and why some planning guidance is needed. A wind farm, a battery and a flexible boiler each hold their value only if the others are there, yet none is paid to consider the others, and each meets the same falling return as it scales. What is missing is coordination: sizing storage and flexible demand against the generation being built, rather than hoping the market assembles the parts in the right proportion after each has separately learned that it cannot. In Donella Meadows’s ranking of where to intervene in a system, a tax rate or a queue rule is a weak lever near the bottom, and the goal the system is steered toward is a strong one near the top. A market told only to minimise the cost of each megawatt-hour will not build the storage and demand that make the megawatt-hours worth producing. It has to be given that goal.</p>
<p>Not every flexible consumer is equally worth building. Michael Liebreich’s hydrogen ladder ranks the uses of clean hydrogen from the unavoidable, fertiliser and refining and methanol, down to the uncompetitive, domestic heating and cars.<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a> The lesson carries over to flexible demand in general: the load worth pairing with intermittent supply is the one whose end product is genuinely valuable, not any load that can be switched on when the wind blows. Electrolysis is a good sponge for surplus power where it feeds a factory that needed the hydrogen anyway, and a poor one where it is a roundabout way to heat a house.</p>
<p>The corollary is economic rather than physical, and it is the sharper half of the point. Because the capture price falls as intermittent supply grows, each new tranche of wind or solar pays only if something is built alongside it to absorb the surplus and hold the price up. To keep adding intermittent producers you have to keep adding flexible consumers: storage, electrolysers, heat that can wait, cars that charge when the wind blows. The demand has to arrive with the supply. Where it does not, the realised price falls, and the build-out continues only because a support payment makes up the difference.</p>
<p>Policy is starting to force this into the open. On 29 July 2026 the German government agreed to phase out the fixed feed-in tariff for new small rooftop solar, so that new installations must sell directly on the market rather than at a guaranteed price. The economy minister, Katherina Reiche, framed it as ending the “produce and forget” principle, under which curtailment costs are borne by the public “regardless of whether the electricity is needed”.<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a> Stripped of the guaranteed price, a new panel is exposed to exactly the cannibalized market price described above, and its owner now has a reason to care whether the electricity is worth anything in the hour it is made.</p>
<p>Sweden had already done it, and said the same thing in plainer terms. On 17 September 2024 the finance ministry announced that the tax deduction for installing solar cells would fall from 20% to 15% from July 2025, and that the separate tax reduction for <em>mikroproduktion av förnybar el</em> — the credit a household earned for selling its surplus back to the grid — would be abolished outright from January 2026.<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a> The reasoning given was not that solar had failed but that it had worked: installations had “ökat kraftigt”, past 250 000 systems by the end of 2023, so the support was no longer needed and solar should stand <em>på marknadsmässiga grunder</em>, on market terms, with the electricity price left to guide where the next panel goes. Withdrawing the microproduction credit alone was reckoned to be worth 680 million kronor a year to the treasury.</p>
<p>Two governments of quite different politics, two years apart, reached the same conclusion by the same route: a payment that is indifferent to when the electricity arrives stops being a subsidy for clean energy and becomes a subsidy for ignoring the market. That is the argument of this chapter, arrived at from the fiscal side rather than the physical one.</p>
<p>It has a second effect, and this one supplies the missing half rather than merely exposing it. A household with panels faces two quite different prices. What it earns for exporting a surplus kilowatt-hour is roughly the spot price; what it saves by consuming that kilowatt-hour itself is the full retail price — spot plus energy tax plus network fee plus VAT. Self-consumption has always been worth several times export, and the microproduction credit existed to narrow that gap. Removing it widens the gap again, and the gap is precisely what a battery is paid to arbitrage: it turns exported kilowatt-hours into self-consumed ones. The same flat tax that, on the industrial side of this argument, floors the price and blunts the signal reaching an electric boiler, works the other way at a domestic meter, because avoided consumption avoids the tax too.</p>
<p>Sweden’s tax code now says this outright. Under the <em>grön teknik</em> deduction the rate for installing solar panels is 15%, while the rate for installing storage of self-produced electricity is <strong>50%</strong>, as it is for an EV charge point, up to 50 000 kronor per person a year.<a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a> Support has been shifted, by more than a factor of three, from adding intermittent supply to adding the things that absorb it. In practice that means batteries of the order of 10 to 20 kWh for a single house and perhaps 100 kWh for an apartment building, sized to move an evening peak rather than to ride out a still week — which is the right scale for the daily cycle that cannibalizes solar, and the wrong one for the seasonal problem that chapter 26 is about.</p>
<p>So the reform does more than expose the owner of a panel to the cannibalized price. It changes what the household is rewarded for building next, from another panel to the storage that makes the panel worth more. That is the mechanism this chapter has been asking for, working at the smallest scale in the system. Whether it also works at the scale of a smelter is the harder question, and there the answer still runs through the grid connection and the industrial tariff rather than through a household’s tax return.</p>
</section>
<section id="what-a-twenty-year-guarantee-costs-when-the-value-falls" class="level2">
<h2 class="anchored" data-anchor-id="what-a-twenty-year-guarantee-costs-when-the-value-falls">What a twenty-year guarantee costs when the value falls</h2>
<p>The German reform did not come from a change of heart. It came from a deadline. The European Commission’s state-aid approval for the EEG expires on <strong>31 December 2026</strong>, so a compliant replacement has to be in force on 1 January 2027 or new plant cannot lawfully be supported at all.<a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a> That is worth saying plainly, because it changes what the decision was. A country that had paid the subsidy for a quarter of a century did not stop because it concluded the subsidy was wrong. It stopped because the permission ran out and something had to be written in its place.</p>
<p>The status matters for how firmly any of this should be read: what follows is a ministry draft, sent to consultation on 20 July 2026 and agreed in cabinet on 29 July, now going through the parliamentary process, and the numbers may move. As drafted, what replaces the guarantee is modest. New systems get a transitional payment set below the old tariff and capped at <strong>36 months</strong>. Separately, systems under 25 kW get a <strong>direct-marketing bonus of 1.5 cents per kilowatt-hour</strong> for their first four years in direct marketing — the two run for different periods, which is in the draft rather than a slip here. The obligation to sell directly reaches systems of 50 kW and above in 2027 and steps down year by year until, by 2030, it covers every new system except plug-in and mini-PV units of 2 kW or less.<a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a></p>
<p>The reason the reform is contentious is the size of what is being wound down. The EEG has lately moved about <strong>€18 billion a year</strong>. In 2024 the EEG paid solar producers roughly <strong>€10 billion above what their output earned on the market — about twice the top-up wind received</strong>, while solar generated <strong>75.9 TWh against wind’s 139.8</strong>, a little over half as much.<a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a> The explanation is not that solar is inefficient but that the payments still being honoured are the guarantees written in the 2000s, when a rooftop system was awarded 40 to 57 cents a kilowatt-hour for twenty years. Averaged across the whole installed fleet, German solar still drew about <strong>17.4 cents per kilowatt-hour</strong> in 2024, while a system commissioned that same year received 6.5 to 10.7.</p>
<p>Now set that against what the electricity was worth in the hours it was actually made. In April 2026, <strong>123 of Germany’s 720 market hours cleared below zero</strong>, and <strong>105 of them — 85% — fell between 10:00 and 16:00</strong>, which is the solar block. The mean price across those negative hours was <strong>−€36/MWh</strong>, and the deepest single hour reached <strong>−€413.8/MWh</strong>.<a href="#fn19" class="footnote-ref" id="fnref19" role="doc-noteref"><sup>19</sup></a></p>
<p>That juxtaposition is this chapter’s argument standing in one place: a fixed payment of 17.4 cents against a market value that is not merely low but negative, in precisely the hours the asset produces. But it needs one qualification, and the qualification is the interesting part. The generator on a legacy guarantee does not pay anyone to take its output. The EEG account does, which is to say the public does — exactly the “produce and forget” arrangement Reiche described above, in which curtailment and negative-price costs are borne by the public “regardless of whether the electricity is needed”.</p>
<p>Germany has been closing that door for two decades, but from the top down by size and only forward by vintage. Large plants have lost their payment during runs of negative prices since the 2016 vintage, and the trigger has tightened from six consecutive hours to four, then three, and reaches one hour in 2027. The <em>Solarspitzengesetz</em> of 25 February 2025 went much further: it removed the size floor that had confined the rule to plants of several hundred kilowatts, so that a system as small as <strong>2 kW</strong> now loses its payment in <strong>every single quarter-hour</strong> the day-ahead price is negative.<a href="#fn20" class="footnote-ref" id="fnref20" role="doc-noteref"><sup>20</sup></a> What all of this shares is that it looks forward. The 40-to-57-cent contracts from the 2000s — the ones the €10 billion is mostly paying — sit below every size threshold ever set and predate every vintage band, and keep their money whatever the price does. Cannibalization at its limit does not show up as a low price. It shows up as a bill, and the question is only whose name is on it.</p>
<section id="one-argument-to-be-careful-with" class="level3">
<h3 class="anchored" data-anchor-id="one-argument-to-be-careful-with">One argument to be careful with</h3>
<p>The German debate about this is fierce, and one move in it is worth naming because a reader will meet it often. It is frequently observed that after twenty-six years of the EEG, Germany still takes about <strong>80% of its primary energy from fossil fuels</strong>, “almost unchanged”. The actual figure for 2025 is <strong>76.4%</strong>, with renewables at 20.6%. But the gap between 80 and 76.4 is not the problem with the claim. The problem is that it does not test what it appears to test, because the EEG is an electricity law and primary energy counts the petrol, diesel, heating oil and gas boilers it never addressed. On the quantity the law was actually aimed at, the renewable share of gross electricity consumption rose from <strong>6.3% in 2000 to 55.1% in 2025</strong>.<a href="#fn21" class="footnote-ref" id="fnref21" role="doc-noteref"><sup>21</sup></a></p>
<p>Both numbers are real, and only one of them is a measure of the policy. This is worth flagging in a book built on unit arithmetic, because it is the characteristic failure that MacKay wrote against: not a wrong number, but a right number answering a different question. The case against the cost does not need it. The case against the cost is the €10 billion, and it stands on its own.</p>
</section>
</section>
<section id="whose-money-and-whose-bill" class="level2">
<h2 class="anchored" data-anchor-id="whose-money-and-whose-bill">Whose money, and whose bill</h2>
<p>The €10 billion is where an old phrase becomes exact. Adam Smith observed in The Wealth of Nations (1776) that the directors of a joint-stock company, “being the managers rather of other people’s money than of their own”, cannot be expected to watch over it as carefully as they would their own. Margaret Thatcher’s line, usually paraphrased as the trouble with socialism being that you eventually run out of other people’s money, points at the same hazard from the other end. Intermittent capacity whose returns rest on subsidy rather than on the price it earns is financed, in both readings, with other people’s money, and that money is spent whether or not the energy arrives when it is wanted. The way out is the storage and the flexible demand that let the energy earn its own value, so the investment rests on the price it commands rather than on the payment that currently stands in for it.</p>
<p>There is a reading of all this that connects back to the reason MacKay wrote the book. Cheap energy, if it reaches industry, is what keeps energy-intensive industry alive, and that industry is a large part of what an economy runs on. The same surplus that starves a generator’s revenue is, read at the buyer’s meter, cheap input, but only if the gates let it through. Germany shows the loop run backward: after its gas price rose, energy-intensive output fell to about 82% of its 2021 level and stayed there.<a href="#fn22" class="footnote-ref" id="fnref22" role="doc-noteref"><sup>22</sup></a></p>
</section>
<section id="what-it-costs-to-build-against-what-it-earns" class="level2">
<h2 class="anchored" data-anchor-id="what-it-costs-to-build-against-what-it-earns">What it costs to build against what it earns</h2>
<p>The capture price becomes a decision rather than an observation when it is set beside the cost of building the thing. That comparison is rarely drawn, because the two numbers come from different places: the cost from engineering studies, the earnings from settlement data.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/without-hot-air/fig-lcoe-vs-capture.svg" class="img-fluid figure-img"></p>
<figcaption>Levelised cost of building against realised 2025 capture price for six GB technologies. Solar, onshore wind, fixed offshore wind and gas CCGT earn more than they cost; floating offshore wind at 91 against 72, and gas with carbon capture at 101 against 94.8, do not.</figcaption>
</figure>
</div>
<p><span class="figurenumber">Figure 28a.4.</span> Cost to build against price realised, Great Britain. Cost is the Department for Energy Security and Net Zero’s levelised cost for projects commissioning in 2035, in 2024 prices, with the low-to-high capex range shown. Earnings are the price each technology actually realised on the GB market in 2025, weighted by its own output.<a href="#fn23" class="footnote-ref" id="fnref23" role="doc-noteref"><sup>23</sup></a></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>£/MWh</th>
<th>Cost to build</th>
<th>Earned in 2025</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Large-scale solar</td>
<td>44</td>
<td><strong>65.9</strong></td>
</tr>
<tr class="even">
<td>Onshore wind</td>
<td>41</td>
<td><strong>72.0</strong></td>
</tr>
<tr class="odd">
<td>Offshore wind, fixed</td>
<td>59</td>
<td><strong>72.0</strong></td>
</tr>
<tr class="even">
<td>Offshore wind, floating</td>
<td><strong>91</strong></td>
<td>72.0</td>
</tr>
<tr class="odd">
<td>Gas CCGT</td>
<td>45</td>
<td><strong>94.8</strong></td>
</tr>
<tr class="even">
<td>Gas with carbon capture</td>
<td><strong>101</strong></td>
<td>94.8</td>
</tr>
</tbody>
</table>
<p>Four of the six clear their costs on today’s prices. <strong>Floating offshore wind does not</strong> — 91 against 72 — which is the quantified version of the proviso chapter 10 records MacKay repeating from wind experts in 2008, that deep offshore is prohibitively expensive. Eighteen years later it is still about a quarter short. <strong>Gas with carbon capture does not either</strong>, at 101 against 94.8, which is chapter 23’s finding in one line: capture works and has not been built, for reasons of cost rather than physics.</p>
<p><strong>Before reading anything into those margins, one asymmetry in the chart has to be admitted.</strong> The two columns are not measured on the same boundary. The right-hand column is a <strong>system</strong> quantity: a capture price is what the market actually paid, in the hours the plant actually produced, with everything the system was doing at the time already in it. The left-hand column is an <strong>asset</strong> quantity: DESNZ’s levelised cost counts capital, fuel and operations inside the fence, and excludes the balancing capacity a variable source needs, the curtailment it suffers, and the capacity utilisation it takes away from the dispatchable plant that must stay available for it.</p>
<p>That asymmetry has a direction. It leaves the cost of a variable source understated relative to a dispatchable one, so the margins in the table are <strong>too generous to solar and wind and too harsh on gas</strong> — by an amount nobody in this chart has measured. Chapter M sets out the methodological case and one attempt to quantify it: a Norwegian onshore wind farm costed on a system boundary came out <strong>19% above its asset figure</strong>, 34% once uncertainties were carried through, and up to 3.5 times if the capacity model was left at nameplate. Those numbers come from a single case with a strong assumption — it firms one wind farm to a dispatchable standard using dedicated gas, which no system operator actually does — so they are an upper bound rather than a correction to apply. The direction, however, is not in doubt.</p>
<p>Which means the honest reading of the chart is not “four of six clear their costs by these margins” but <strong>“four of six clear their costs, and the variable ones by less than shown.”</strong> The £13/MWh that fixed offshore wind clears by is the number most exposed to this, and it is the number the rest of this section leans on.</p>
<p><strong>And the chart is a snapshot of a moving thing, which is this chapter’s whole point.</strong> The right-hand column is what the <em>existing</em> fleet earned. Build more of a technology and its capture price falls, because the new plant produces in the same hours as the old. So a project appraised against today’s £72 will not receive £72 once it and its neighbours are running: wind’s value factor of 0.90 has further to fall.</p>
<p>Read that way the figure states the investment problem exactly. <strong>Fixed offshore wind clears its cost by about £13/MWh, and its own expansion is what closes that gap.</strong> The CfD exists to bridge it, which is why chapter 4’s note on AR6 matters: a strike price of about £82 in today’s money against a captured £72 is the public purse paying the difference between what the market gives and what the machine costs.</p>
<p>And it explains why the strike price and the levelised cost do not match. AR6 cleared at roughly £82/MWh indexed while the levelised cost here is £59. A bid below the published cost of building is not a contradiction; it is what happens when a contract removes the price risk, because the discount rate a project is financed at falls when its revenue is guaranteed. <strong>The CfD’s real product is cheap capital rather than a high price.</strong> That is the same insight as chapter 28a’s opening, arriving from the financing side: what a generator is paid for is not only energy but certainty.</p>
<p>Britain’s version of the problem is not a shock but a standing condition, and it is worse than the German one. Of the 28 IEA countries that reported industrial electricity prices for 2024, <strong>the United Kingdom’s were the highest</strong>, counting taxes and levies. Large British industrial users paid about <strong>25.3p per kWh, some 125% above the EU-14 median of 11.3p</strong>.<a href="#fn24" class="footnote-ref" id="fnref24" role="doc-noteref"><sup>24</sup></a> For a book whose argument is that Britain should electrify — heat, transport, industry — that is the most awkward number in the entire subject, and MacKay’s method cannot see it, because it is not a fact about joules.</p>
<p>Set it beside the wholesale figure from earlier in this chapter and the shape of the problem becomes clear. The GB market price averaged <strong>£79.9/MWh in 2025, which is 8.0p per kWh</strong>. Large industrial users pay roughly <strong>three times that</strong>. The difference — some 17p per kWh — is network charges, policy levies, supplier margin and the cost of firming, and almost none of it is the cost of generating the electricity.</p>
<p>That is the reconciliation this chapter has been circling. The complaint of the generator, that wind captures only 90% of a falling average, and the complaint of the smelter, that power costs three times what the market says it does, sound like opposite grievances. They are the same wedge measured from its two ends. Cheap generation and expensive delivered power are not in contradiction; the surplus is real, and it is being consumed somewhere between the turbine and the meter. A country can cannibalise its generators and impoverish its industrial consumers at the same time, and Britain currently does both.</p>
<p>So the argument of this chapter has a corollary it would be dishonest to leave out. Storage and flexible demand let renewable energy earn its own value, which is the answer to the first complaint. They do nothing whatever about the second. If 17p of a 25p industrial price is network, levy and margin, then no amount of cheap wind reaches the factory until that wedge is addressed, and it is addressed by policy rather than by physics or by batteries.</p>
</section>
<section id="the-same-comparison-for-a-country-that-imports-its-fuel" class="level2">
<h2 class="anchored" data-anchor-id="the-same-comparison-for-a-country-that-imports-its-fuel">The same comparison, for a country that imports its fuel</h2>
<p>The table above is a British question, and it takes a particular form because Britain has a liquid wholesale market: the thing a generator is measured against is the price other generators were paid. <strong>For most of Asia the comparison is a different one, and it is much less forgiving of fossil fuel.</strong></p>
<p>An importer is not choosing between two ways of earning £/MWh in an auction. It is choosing between building a machine once, in its own currency, and buying fuel every year, for ever, in someone else’s — through a strait that chapter N describes being closed in March 2026. Asia has <strong>54% of the world’s population and 2% of its oil reserves</strong>, imports about <strong>$1.1 trillion of fossil fuel a year at over 3% of regional GDP</strong>, and has solar and wind resources sufficient for <strong>at least fourteen times its total energy demand</strong>. Set beside those numbers, the levelised cost of solar is not competing with a capture price. It is competing with an import bill and a currency risk.</p>
<p><strong>That is why the bet is being placed, and the exceptions are what confirm it.</strong> The countries paying most — Thailand at around 7.5% of GDP, then Taiwan, South Korea, Singapore, Viet Nam, Pakistan, the Philippines — have the most to gain from displacing the bill. The countries sitting near zero on the same measure are Malaysia and Myanmar, and they are near zero because they export. An exporter’s arithmetic runs the other way: every kilowatt-hour of domestic solar displaces a barrel it would rather have sold. Russia is the limiting case of that position, and it is not electrifying anything in a hurry.</p>
<p><strong>The caution is that this cuts both ways as an explanation.</strong> Import dependence explains the urgency, not the whole of the behaviour — Malaysia and Brunei are both exporters and both ahead of the United States on electrification, because the share of final energy delivered as electricity is driven by what a country builds and sells as much as by what it must buy. And the fourteen-times resource figure is a technical potential, the same class of number as MacKay’s own green stack in chapter 18, which he was careful to say was not a forecast. <strong>What the trade balance predicts is which countries have a reason to hurry, and on that it predicts well.</strong><a href="#fn25" class="footnote-ref" id="fnref25" role="doc-noteref"><sup>25</sup></a></p>
<p>None of this argues against building renewables. MacKay’s arithmetic still holds, and the build-out has largely happened. It argues that the balance sheet needs a second page. The first page asks whether we can produce enough clean energy. The second asks who bears the cost of turning an intermittent surplus into firm, useful supply, and whether policy lets the cheap hours reach the demand that would value them. A fuller treatment, with the feedback loops drawn out and the Swedish and European data behind each figure, is at oluies.github.io/elmix.<a href="#fn26" class="footnote-ref" id="fnref26" role="doc-noteref"><sup>26</sup></a></p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Regenerated by this edition’s data-refresh script (<code>Refresh.scala</code>, DuckDB) from Our World in Data. Solar module cost fell from USD 4.61/W (2008) to 0.26/W (2024). Global weighted-average LCOE (IRENA), USD/MWh, 2010 to 2024: solar PV 417 to 43, onshore wind 113 to 34, offshore wind 208 to 79. Battery pack price, cited separately (BloombergNEF): about USD 1200/kWh (2010) to 115/kWh (2024).<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Figure regenerated from Our World in Data (Ember and the Energy Institute) by this edition’s data-refresh script (<code>Refresh.scala</code>, DuckDB), in TWh: UK coal 124 (2008) to 0 (2025), wind 7 to 86, solar 0 to 19, bioenergy 10 to 41, gas 176 to 91, nuclear 52 to 36.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Capture price = the sum of (production times spot price) divided by the sum of production. Source list at https://oluies.github.io/elmix/modell/referenser.html .<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Goransson, Johnsson and others, “Tre elsystem som kan mota omstallningen av industri- och transportsektorerna”, Chalmers / Mistra Electrification, 2025.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Computed by this edition’s data-refresh script (<code>Refresh.scala</code>, DuckDB) from Elexon BMRS: half-hourly GB generation by fuel type and the market-index price (APXMIDP), 2025. Capture price = sum(generation × price) / sum(generation); value factor against the 79.9 GBP/MWh time-weighted average. Gas 1.19, Biomass 1.08, Nuclear 1.01, Wind 0.90, Solar 0.82.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Geis, Lindner and Brown, “Managing the mismatch: The role of flexibility on the path to a carbon-neutral energy system”, Advances in Applied Energy 23 (2026) 100284.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Energiateollisuus district-heating statistics, 2025; Fernqvist, Broberg, Toren and Svensson, “District heating as a flexibility service”, Energy Policy 172 (2023) 113332.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Energimarknadsinspektionen finding of 11 June 2026 on connection times; the Power2Earth refusal at Lulea, autumn 2025.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>MacKay, Chapter 26, “Fluctuations and storage”. Finnish and Swedish figures and the role of thermal storage: Energiateollisuus 2025; Fernqvist and others, Energy Policy 172 (2023) 113332; the Arlanda aquifer store, Swedavia.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>California battery arbitrage revenue: CAISO Department of Market Monitoring, and Modo Energy’s series of about 103, 80, 51 and 38 USD per kW-year. Australian NEM battery revenues at a record low: Modo Energy, 2026.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>The storage merit order by duration: installed cost per kWh at a four-hour duty against a hundred-hour duty, where the spread widens to roughly a factor of 22 and lithium-ion falls from second-cheapest to dearest. https://oluies.github.io/elmix/lagring.html .<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>Michael Liebreich, “Clean Hydrogen Ladder Version 5.0”, 19 October 2023, https://liebreich.com/hydrogen-ladder-version-5-0/ .<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>“Government agrees to phase out Germany’s landmark fixed feed-in tariffs for new small solar PV”, Clean Energy Wire, 29 July 2026.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p>“Förändrade skattesubventioner för solceller”, Finansdepartementet, 17 September 2024: <a href="https://www.regeringen.se/pressmeddelanden/2024/09/forandrade-skattesubventioner-for-solceller/" class="uri">https://www.regeringen.se/pressmeddelanden/2024/09/forandrade-skattesubventioner-for-solceller/</a>. The changes were part of an agreement between the government and Sverigedemokraterna; the rate cut was estimated at 100 million kronor in 2025 and 200 million a year from 2026, the abolition of the microproduction credit at 680 million a year from 2026.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p>Rates for the <em>skattereduktion för grön teknik</em>, Energimyndigheten’s Solelportalen: <a href="https://www.energimyndigheten.se/effektiv-energianvandning/guider/solelportalen/vilka-stod-och-intakter-kan-jag-fa/skattereduktion-for-gron-teknik/" class="uri">https://www.energimyndigheten.se/effektiv-energianvandning/guider/solelportalen/vilka-stod-och-intakter-kan-jag-fa/skattereduktion-for-gron-teknik/</a>. As of 2026: 15% for solar panels, 50% for storage of self-produced electricity, 50% for an EV charging point, capped at 50 000 kronor per person per year. The battery sizes quoted are typical installed capacities rather than a recommendation.<a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p>The EEG’s approval under EU state-aid law runs only to 31 December 2026, so an EU-compliant successor regime must take effect on 1 January 2027; without one, new plant could be built and connected but not supported. Industry bodies including the BDEW and the BEE have pressed for a rapid parliamentary conclusion precisely so that the Commission has time to review and approve the replacement. Note that it is the state-aid approval that expires, not the statute itself.<a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17"><p>Draft EEG reform sent to consultation by the federal economics ministry under Katherina Reiche in July 2026: guaranteed feed-in ends for new rooftop systems, replaced by a transitional payment set below the previous tariff and capped at 36 months, plus a direct-marketing bonus of 1.5 ct/kWh for the first four years for systems under 25 kW. Direct marketing becomes mandatory for systems of 50 kW and above from 2027, extending to smaller classes each year until it covers all new systems except plug-in and mini-PV units of 2 kW or less by 2030. Summary at <a href="https://www.pv-magazine.de/2026/07/20/reiche-schickt-entwuerfe-fuer-eeg-und-netzpaket-in-die-verbaendeanhoerung/" class="uri">https://www.pv-magazine.de/2026/07/20/reiche-schickt-entwuerfe-fuer-eeg-und-netzpaket-in-die-verbaendeanhoerung/</a>. The industry association rejected the transitional terms as a “wertloses Trostpflaster” — a worthless sticking plaster — arguing they cannot replace the roughly 7 ct/kWh paid to partial feed-in systems and 10 to 12 ct to full feed-in systems. Those are the association’s own characterisation of the rates the reform removes, spanning the vintages currently in payment, and are not directly comparable with the 6.47 and 10.68 ct/kWh applying to systems commissioned in 2024 quoted in the previous note; EEG tariffs degress downward, so a figure above the 2024 rate refers to earlier commissioning years. Figures here are from a draft in consultation and may change in the parliamentary process.<a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18"><p>The primary source is the Bundesnetzagentur’s <em>Monitoringbericht</em>, which has not been consulted directly here. The EEG flow of about €18 billion a year, the €10 billion paid to solar producers in 2024 against roughly half that for wind, and the fleet-average 17.4 ct/kWh are as reported from that monitoring report by Daniel Wetzel, “Die Ökostrom-Lobby hängt an den Subventionen wie ein Junkie an der Nadel”, <em>Welt</em>, August 2026. That piece is a signed opinion column arguing a position, in vigorous language, and is used here for its checkable figures rather than its framing; the generation comparison and the per-kilowatt-hour inference are made here from the Energy Institute’s <em>Statistical Review of World Energy</em> 2026, which gives German solar 75.9 TWh and wind 139.8 TWh in 2024. Rates for systems commissioned in 2024 (6.47 ct/kWh and 10.68 ct/kWh by segment) are the Bundesnetzagentur’s published tariffs. The €10 billion and the 17.4 ct figures are on different bases — net EEG payment above market revenue, and gross remuneration rate — so they should not be divided into one another; gross receipts on 75.9 TWh at 17.4 ct would be about €13 billion, not €10 billion.<a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn19"><p>April 2026: 123 of 720 hours cleared below zero on the German day-ahead market, 105 of them (85%) between 10:00 and 16:00 CEST; mean clearing price across the negative hours −€36.0/MWh; deepest single hour −€413.8/MWh. German negative-price hours in the first half of 2026 have been reported at 299 against 389 in the same period of 2025 — down year on year, not a trend within 2026. Note that these German figures run opposite to the Europe-wide count, which roughly doubled in the first quarter of 2026: the two are different geographies and should not be read as one series. See <a href="https://www.euronews.com/2026/07/29/wind-and-solar-overtake-fossil-fuels-in-germany-but-negative-electricity-prices-still-rife" class="uri">https://www.euronews.com/2026/07/29/wind-and-solar-overtake-fossil-fuels-in-germany-but-negative-electricity-prices-still-rife</a> for the German half-year figures and <a href="https://www.pv-magazine.com/2026/05/08/europes-negative-electricity-price-hours-double-in-q1-amid-renewables-surpluses-market-imbalances/" class="uri">https://www.pv-magazine.com/2026/05/08/europes-negative-electricity-price-hours-double-in-q1-amid-renewables-surpluses-market-imbalances/</a> for the European Q1 count. The April 2026 hourly detail predates both and should be checked against the exchange’s own published data before being relied on.<a href="#fnref19" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn20"><p>Under § 51 EEG the payment lapses when the day-ahead price is negative for a run of consecutive hours, with both the run length and the size floor depending on when the plant was commissioned. Plants of 500 kW and above commissioned from 2016 under the EEG 2014/2017 faced a six-hour trigger with no compensation. Under the EEG 2023, for plants of 400 kW and above, the threshold is four hours for the 2023 vintage, three for 2024 and 2025, two for 2026 and one from 2027. The <em>Gesetz zur Änderung des EEG 2023</em> known as the Solarspitzengesetz, in force 25 February 2025, replaces the run with the <strong>first negative quarter-hour</strong> and removes the size floor: systems of 100 kWp and above immediately, and all systems from 2 kWp once a smart meter is fitted. Compensation for lost hours runs under § 51a, which extends the remuneration period — but it does not reach the oldest cohorts, and the 2025 reform replaced the flat hour-for-hour extension with a time-contingent model weighting photovoltaic losses at 0.5 times the negative quarter-hours actually incurred. Installations on the original 2000s guarantees are below every size floor these rules have used and are not reached by any of them.<a href="#fnref20" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn21"><p>The renewable share of German gross electricity consumption rose from 6.3% in 2000 to 55.1% in 2025; renewables reached 23.8% of gross final energy consumption in 2025. For primary energy, AG Energiebilanzen’s estimate for 2025 puts the fossil share of primary energy at <strong>76.4%</strong> and renewables at 20.6%; the largest components are mineral oil at 35.7% and natural gas at 26.9%, with hard coal and lignite making up the remainder. The 76.4% is AGEB’s published total and is not re-derived here from the rounded components. Sources: Umweltbundesamt, “Renewable energies in figures”, for the electricity shares; AG Energiebilanzen’s 2025 annual estimate for the primary-energy shares. The distinction matters because primary energy includes transport fuels and heating fuels that the EEG does not address.<a href="#fnref21" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn22"><p>Destatis, production index for energy-intensive branches, 2025.<a href="#fnref22" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn23"><p>Levelised costs are from <em>Electricity Generation Costs 2025</em>, Department for Energy Security and Net Zero: central capex estimates for projects commissioning in 2035, in 2024 real prices — large-scale solar 44 (range 36–50), onshore wind 41 (33–55), fixed offshore wind 59 (50–72), floating offshore wind 91 (65–121), gas CCGT 45 (38–53) and gas with CCUS 101 (85–117), the two gas figures at a 30% load factor. Capture prices are for 2025 from this edition’s data-refresh script over Elexon settlement data. Three cautions. The two sides are not on the same footing: a 2035 commissioning cost in 2024 money against prices realised in 2025 by plant already built, so this is an order-of-magnitude comparison rather than an appraisal. The capture figure for wind combines onshore and offshore, so fixed offshore is measured against a blended price. And DESNZ notes that levelised cost omits system effects entirely — transmission, balancing and the value of being dispatchable — which is precisely what separates the gas column from the wind column and is the subject of this chapter.<a href="#fnref23" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn24"><p>Department for Energy Security and Net Zero, <em>Quarterly Energy Prices</em>, international industrial electricity price comparisons: of 28 IEA countries reporting for 2024, the UK had the highest industrial electricity prices including taxes and levies, with large users at about 25.33p/kWh against an EU-14 median of 11.25p/kWh. The 2024 price is compared here with the 2025 GB wholesale average, so the ratio is indicative rather than exact; and some energy-intensive users receive partial exemption from policy levies, so the figure for an individual plant may be lower. Sweden makes an instructive contrast: qualifying manufacturers there pay an electricity tax of 0.6 öre/kWh against a full rate of 43.9, a relief now under audit by Riksrevisionen.<a href="#fnref24" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn25"><p>Ember, <em>Electric Asia: How Asia is leading the electric age</em>, 11 June 2026. The figures, and the cautions that go with them — that Ember advocates for electrification, that its “Asia” excludes Russia, that the “share of Asia” percentages have an unstated denominator, and that the resource multiple is a technical potential rather than a forecast — are set out in full in the corresponding note to chapter N.<a href="#fnref25" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn26"><p>The elmix cannibalization model, https://oluies.github.io/elmix/modell/system.html .<a href="#fnref26" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/chap28.html" class="pagination-link" aria-label="28 Putting costs in perspective">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">28 Putting costs in perspective</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/chap29.html" class="pagination-link" aria-label="29 What to do now">
        <span class="nav-page-text"><span class="chapter-title">29 What to do now</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>