<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>25 Living on other countries’ renewables? – Sustainable Energy — Without the Hot Air</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/chap26.html" rel="next">
<link href="../chapters/chap24.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1b15cd7dfe5d645daabccee077c4b062.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chap19.html">Part II · Making a difference</a></li><li class="breadcrumb-item"><a href="../chapters/chap25.html"><span class="chapter-title">25 Living on other countries’ renewables?</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Sustainable Energy — Without the Hot Air</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About this edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I · Numbers, not adjectives</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap01.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1 Motivations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap02.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2 The balance sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap03.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3 Cars</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap04.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4 Wind</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap05.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5 Planes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap06.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6 Solar</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap07.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7 Heating and cooling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap08.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8 Hydroelectricity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap09.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">9 Light</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap10.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10 Offshore wind</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap11.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11 Gadgets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap12.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12 Wave</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap13.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13 Food and farming</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap14.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14 Tide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap15.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15 Stuff</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap16.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">16 Geothermal</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap17.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17 Public services</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap18.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18 Can we live on renewables?</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II · Making a difference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap19.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19 Every BIG helps</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap20.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20 Better transport</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap21.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">21 Smarter heating</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap22.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">22 Efficient electricity use</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap23.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">23 Sustainable fossil fuels?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap24.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">24 Nuclear?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap25.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">25 Living on other countries’ renewables?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap26.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">26 Fluctuations and storage</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap27.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">27 Five energy plans for Britain</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap28.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">28 Putting costs in perspective</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap-value-of-renewables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The value of renewable energy as it scales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap29.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">29 What to do now</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap30.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">30 Energy plans for Europe, America, and the World</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap31.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">31 The last thing we should talk about</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap32.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">32 Saying yes</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III · Technical chapters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapA.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">A Cars II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapB.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">B Wind II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapC.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">C Planes II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapD.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">D Solar II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapE.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">E Heating II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapF.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">F Waves II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapG.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">G Tide II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapH.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">H Stuff II</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV · Useful data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapI.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">I Quick reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapJ.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">J Populations and areas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapK.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">K UK energy history</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/charts.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Charts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/bibliography.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bibliography</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#a-technology-that-adds-up" id="toc-a-technology-that-adds-up" class="nav-link active" data-scroll-target="#a-technology-that-adds-up">A technology that adds up</a>
  <ul class="collapse">
  <li><a href="#the-desertec-plan" id="toc-the-desertec-plan" class="nav-link" data-scroll-target="#the-desertec-plan">The DESERTEC plan</a></li>
  <li><a href="#concentrating-photovoltaics" id="toc-concentrating-photovoltaics" class="nav-link" data-scroll-target="#concentrating-photovoltaics">Concentrating photovoltaics</a></li>
  </ul></li>
  <li><a href="#queries" id="toc-queries" class="nav-link" data-scroll-target="#queries">Queries</a></li>
  <li><a href="#the-reverse-case-and-the-politics-of-it" id="toc-the-reverse-case-and-the-politics-of-it" class="nav-link" data-scroll-target="#the-reverse-case-and-the-politics-of-it">The reverse case, and the politics of it</a></li>
  <li><a href="#notes-and-further-reading" id="toc-notes-and-further-reading" class="nav-link" data-scroll-target="#notes-and-further-reading">Notes and further reading</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chap19.html">Part II · Making a difference</a></li><li class="breadcrumb-item"><a href="../chapters/chap25.html"><span class="chapter-title">25 Living on other countries’ renewables?</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">25 Living on other countries’ renewables?</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p><em>Whether the Mediterranean becomes an area of cooperation or confrontation in the 21st century will be of strategic importance to our common security.</em></p>
<p>Joschka Fischer, German Foreign Minister, February 2004</p>
</blockquote>
<p>We’ve found that it’s hard to get off fossil fuels by living on our own renewables. Nuclear has its problems too. So what else can we do? Well, how about living on someone else’s renewables? (Not that we have any entitlement to someone else’s renewables, of course, but perhaps they might be interested in selling them to us.)</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Technology</th>
<th>Power per unit land or water area</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Wind</td>
<td>2 W/m<sup>2</sup></td>
</tr>
<tr class="even">
<td>Offshore wind</td>
<td>3 W/m<sup>2</sup></td>
</tr>
<tr class="odd">
<td>Tidal pools</td>
<td>3 W/m<sup>2</sup></td>
</tr>
<tr class="even">
<td>Tidal stream</td>
<td>6 W/m<sup>2</sup></td>
</tr>
<tr class="odd">
<td>Solar PV panels</td>
<td>5–20 W/m<sup>2</sup></td>
</tr>
<tr class="even">
<td>Plants</td>
<td>0.5 W/m<sup>2</sup></td>
</tr>
<tr class="odd">
<td>Rain-water (highlands)</td>
<td>0.24 W/m<sup>2</sup></td>
</tr>
<tr class="even">
<td>Hydroelectric facility</td>
<td>11 W/m<sup>2</sup></td>
</tr>
<tr class="odd">
<td>Solar chimney</td>
<td>0.1 W/m<sup>2</sup></td>
</tr>
<tr class="even">
<td><strong>Concentrating solar power (desert)</strong></td>
<td><strong>15 W/m<sup>2</sup></strong></td>
</tr>
</tbody>
</table>
<p><span class="figurenumber">Table 25.1</span>. Renewable facilities have to be country-sized because all renewables are so diffuse.</p>
<p>Most of the resources for living sustainably are related to land area: if you want to use solar panels, you need land to put them on; if you want to grow crops, you need land again. Jared Diamond, in his book Collapse, observes that, while many factors contribute to the collapse of civilizations, a common feature of all collapses is that the human population density became too great.</p>
<p>Places like Britain and Europe are in a pickle because they have large population densities, and all the available renewables are diffuse – they have small power density (table 25.1). When looking for help, we should look to countries that have three things: a) low population density; b) large area; and c) a renewable power supply with high power density.</p>
<table class="table">
<thead>
<tr class="header">
<th>
Region
</th>
<th>
Population
</th>
<th>
Area (km<sup>2</sup>)
</th>
<th>
Density (persons<br> per km<sup>2</sup>)
</th>
<th>
Area per<br> person (m<sup>2</sup>)
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>
Libya
</td>
<td>
5 760 000
</td>
<td>
1 750 000
</td>
<td>
3
</td>
<td>
305 000
</td>
</tr>
<tr class="even">
<td>
Kazakhstan
</td>
<td>
15 100 000
</td>
<td>
2 710 000
</td>
<td>
6
</td>
<td>
178 000
</td>
</tr>
<tr class="odd">
<td>
Saudi Arabia
</td>
<td>
26 400 000
</td>
<td>
1 960 000
</td>
<td>
13
</td>
<td>
74 200
</td>
</tr>
<tr class="even">
<td>
Algeria
</td>
<td>
32 500 000
</td>
<td>
2 380 000
</td>
<td>
14
</td>
<td>
73 200
</td>
</tr>
<tr class="odd">
<td>
Sudan
</td>
<td>
40 100 000
</td>
<td>
2 500 000
</td>
<td>
16
</td>
<td>
62 300
</td>
</tr>
<tr class="even">
<td>
World
</td>
<td>
6 440 000 000
</td>
<td>
148 000 000
</td>
<td>
43
</td>
<td>
23 100
</td>
</tr>
<tr class="odd">
<td>
Scotland
</td>
<td>
5 050 000
</td>
<td>
78 700
</td>
<td>
64
</td>
<td>
15 500
</td>
</tr>
<tr class="even">
<td>
European Union
</td>
<td>
496 000 000
</td>
<td>
4 330 000
</td>
<td>
115
</td>
<td>
8 720
</td>
</tr>
<tr class="odd">
<td>
Wales
</td>
<td>
2 910 000
</td>
<td>
20 700
</td>
<td>
140
</td>
<td>
7 110
</td>
</tr>
<tr class="even">
<td>
United Kingdom
</td>
<td>
59 500 000
</td>
<td>
244 000
</td>
<td>
243
</td>
<td>
4 110
</td>
</tr>
<tr class="odd">
<td>
England
</td>
<td>
49 600 000
</td>
<td>
130 000
</td>
<td>
380
</td>
<td>
2 630
</td>
</tr>
</tbody>
</table>
<p><span class="figurenumber">Table 25.2</span>. Some regions, ordered from small to large population density. See <a href="../Text/chapJ.xhtml">chapter J</a> for more population densities.</p>
<p><img src="img/without-hot-air/figure205.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 25.3</span>. Stirling dish engine. These beautiful concentrators deliver a power per unit land area of <span class="green">14 W/m<sup>2</sup></span>. Photo courtesy of Stirling Energy Systems. <a href="http://www.stirlingenergy.com"><span class="websitetitle">www.stirlingenergy.com</span></a></p>
<blockquote class="blockquote">
<p><em>(Figure omitted from this edition: third-party rights.)</em></p>
</blockquote>
<p><span class="figurenumber">Figure 25.4</span>. Andasol – a “100MW” solar power station under construction in Spain. Excess thermal energy produced during the day will be stored in liquid salt tanks for up to seven hours, allowing a continuous and stable supply of electric power to the grid. The power station is predicted to produce 350 GWh per year (40 MW). The parabolic troughs occupy 400 hectares, so the power per unit land area will be <span class="green">10 W/m<sup>2</sup></span>. Upper photo: ABB. Lower photo: IEA SolarPACES.</p>
<p>Table 25.2 highlights some countries that fit the bill. Libya’s population density, for example, is 70 times smaller than Britain’s, and its area is 7 times bigger. Other large, area-rich, countries are Kazakhstan, Saudi Arabia, Algeria, and Sudan.</p>
<p>In all these countries, I think the most promising renewable is <span id="solar">solar</span> power, <em>concentrating solar power</em> in particular, which uses mirrors or lenses to focus sunlight. Concentrating solar power stations come in several flavours, arranging their moving mirrors in various geometries, and putting various power conversion technologies at the focus – Stirling engines, pressurized water, or molten salt, for example – but they all deliver fairly similar average powers per unit area, in the ballpark of <span class="green">15 W/m<sup>2</sup></span>.</p>
<section id="a-technology-that-adds-up" class="level2">
<h2 class="anchored" data-anchor-id="a-technology-that-adds-up">A technology that adds up</h2>
<p>“All the world’s power could be provided by a square 100 km by 100 km in the Sahara.” Is this true? Concentrating solar power in deserts delivers an average power per unit land area of roughly <span class="green">15 W/m<sup>2</sup></span>. <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> So, allowing no space for anything else in such a square, the power delivered would be 150 GW. This is <em>not</em> the same as current world power consumption. It’s not even near current world <em>electricity</em> consumption, which is 2000 GW. World power consumption today is 15 000 GW. So the correct statement about power from the Sahara is that today’s consumption could be provided by a <em>1000 km by 1000 km</em> square in the desert, completely filled with concentrating solar power. That’s four times the area of the UK. And if we are interested in living in an equitable world, we should presumably aim to supply more than <em>today’s</em> consumption. To supply every person in the world with an average European’s power consumption (125 kWh/d), the area required would be <em>two</em> 1000 km by 1000 km squares in the desert.</p>
<p>Fortunately, the Sahara is not the only desert, so maybe it’s more relevant to chop the world into smaller regions, and ask what area is needed in each region’s local desert. So, focusing on Europe, “what area is required in the North Sahara to supply <em>everyone in Europe and North Africa</em> with an average European’s power consumption? Taking the population of Europe and North Africa to be 1 billion, the area required drops to 340 000 km<sup>2</sup>, which corresponds to a square <strong>600 km by 600 km</strong>. This area is equal to one Germany, to 1.4 United Kingdoms, or to <strong>16 Waleses</strong>.</p>
<p>The UK’s share of this 16-Wales area would be one Wales: a 145 km by 145 km square in the Sahara would provide all the UK’s current primary energy consumption. These squares are shown in figure 25.5. Notice that while the yellow square may look “little” compared with Africa, it does have the same area as Germany.</p>
<p><img src="img/without-hot-air/figure427.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 25.5</span>. The celebrated little square. This map shows a square of size 600 km by 600 km in Africa, and another in Saudi Arabia, Jordan, and Iraq. Concentrating solar power facilities completely filling one such square would provide enough power to give 1 billion people the average European’s consumption of 125 kWh/d.&nbsp;The area of one square is the same as the area of Germany, and 16 times the area of Wales. Within each big square is a smaller 145 km by 145 km square showing the area required in the Sahara – one Wales – to supply all British power consumption.</p>
<section id="the-desertec-plan" class="level3">
<h3 class="anchored" data-anchor-id="the-desertec-plan">The DESERTEC plan</h3>
<p>An organization called DESERTEC [<a href="http://www.desertec.org/"><span class="websitetitle">www.desertec.org</span></a>] is promoting a plan to use concentrating solar power in sunny Mediterranean countries, and high-voltage direct-current (HVDC) transmission lines (figure 25.7) to deliver the power to cloudier northern parts. HVDC technology has been in use since 1954 to transmit power both through overhead lines and through submarine cables (such as the interconnector between France and England). It is already used to transmit electricity over 1000-km distances in South Africa, China, America, Canada, Brazil, and Congo. <a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> A typical 500 kV line can transmit a power of 2 GW. A pair of HVDC lines in Brazil transmits 6.3 GW.</p>
<p>HVDC is preferred over traditional high-voltage AC lines because less physical hardware is needed, less land area is needed, and the power losses of HVDC are smaller. The power losses on a 3500 km-long HVDC line, including conversion from AC to DC and back, would be about 15%. <a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> A further advantage of HVDC systems is that they help stabilize the electricity networks to which they are connected.</p>
<p>In the DESERTEC plans, the prime areas to exploit are coastal areas, because concentrating solar power stations that are near to the sea can deliver desalinated water as a by-product – valuable for human use, and for agriculture.</p>
<p>Table 25.6 shows DESERTEC’s estimates of the potential power that could be produced in countries in Europe and North Africa. The “economic potential” adds up to more than enough to supply 125 kWh per day to 1 billion people. The total “coastal potential” is enough to supply 16 kWh per day per person to 1 billion people.</p>
<table class="table">
<thead>
<tr class="header">
<th>
Country
</th>
<th>
Economic potential<br> (TWh/y)
</th>
<th>
Coastal potential<br> (TWh/y)
</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>
Algeria
</td>
<td>
169 000
</td>
<td>
60
</td>
</tr>
<tr class="even">
<td>
Libya
</td>
<td>
140 000
</td>
<td>
500
</td>
</tr>
<tr class="odd">
<td>
Saudi Arabia
</td>
<td>
125 000
</td>
<td>
2 000
</td>
</tr>
<tr class="even">
<td>
Egypt
</td>
<td>
74 000
</td>
<td>
500
</td>
</tr>
<tr class="odd">
<td>
Iraq
</td>
<td>
29 000
</td>
<td>
60
</td>
</tr>
<tr class="even">
<td>
Morocco
</td>
<td>
20 000
</td>
<td>
300
</td>
</tr>
<tr class="odd">
<td>
Oman
</td>
<td>
19 000
</td>
<td>
500
</td>
</tr>
<tr class="even">
<td>
Syria
</td>
<td>
10 000
</td>
<td>
0
</td>
</tr>
<tr class="odd">
<td>
Tunisia
</td>
<td>
9 200
</td>
<td>
350
</td>
</tr>
<tr class="even">
<td>
Jordan
</td>
<td>
6 400
</td>
<td>
0
</td>
</tr>
<tr class="odd">
<td>
Yemen
</td>
<td>
5 100
</td>
<td>
390
</td>
</tr>
<tr class="even">
<td>
Israel
</td>
<td>
3 100
</td>
<td>
1
</td>
</tr>
<tr class="odd">
<td>
UAE
</td>
<td>
2 000
</td>
<td>
540
</td>
</tr>
<tr class="even">
<td>
Kuwait
</td>
<td>
1 500
</td>
<td>
130
</td>
</tr>
<tr class="odd">
<td>
Spain
</td>
<td>
1 300
</td>
<td>
70
</td>
</tr>
<tr class="even">
<td>
Qatar
</td>
<td>
800
</td>
<td>
320
</td>
</tr>
<tr class="odd">
<td>
Portugal
</td>
<td>
140
</td>
<td>
7
</td>
</tr>
<tr class="even">
<td>
Turkey
</td>
<td>
130
</td>
<td>
12
</td>
</tr>
<tr class="odd">
<td>
Total
</td>
<td>
620 000<br> (70 000 GW)
</td>
<td>
6 000<br> (650 GW)
</td>
</tr>
</tbody>
</table>
<p><span class="figurenumber">Table 25.6</span>. Solar power potential in countries around and near to Europe. The “economic potential” is the power that could be generated in suitable places where the direct normal irradiance is more than 2000 kWh/m<sup>2</sup>/y. The “coastal potential” is the power that could be generated within 20 m (vertical) of sea level; such power is especially promising because of the potential combination with desalination. For comparison, the total power required to give 125 kWh per day to 1 billion people is 46 000 TWh/y (5 200 GW). 6000 TWh/y (650 GW) is 16 kWh per day per person for 1 billion people.</p>
<blockquote class="blockquote">
<p><em>(Figure omitted from this edition: third-party rights.)</em></p>
</blockquote>
<p><span class="figurenumber">Figure 25.7</span>. Laying a high-voltage DC link between Finland and Estonia. A pair of these cables transmit a power of 350 MW. Photo: ABB.</p>
<p>Let’s try to convey on a map what a realistic plan could look like. Imagine making solar facilities each having an area of 1500 km<sup>2</sup> – that’s roughly the size of London. (Greater London has an area of 1580 km<sup>2</sup>; the M25 orbital motorway around London encloses an area of 2300 km<sup>2</sup>.) Let’s call each facility a <em>blob</em>. Imagine that in each of these blobs, half the area is devoted to concentrating power stations with an average power density of 15 W/m<sup>2</sup>, leaving space around for agriculture, buildings, railways, roads, pipelines, and cables. Allowing for 10% transmission loss between the blob and the consumer, each of these blobs generates an average power of 10 GW. Figure 25.8 shows some blobs to scale on a map. To give a sense of the scale of these blobs I’ve dropped a few in Britain too. <em>Four</em> of these blobs would have an output roughly equal to Britain’s total electricity consumption (16 kWh/d per person for 60 million people). <em>Sixty-five</em> blobs would provide all one billion people in Europe and North Africa with 16 kWh/d per person. Figure 25.8 shows 68 blobs in the desert.</p>
<p><img src="img/without-hot-air/figure207.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 25.8</span>. Each circular blob represents an area of 1500 km<sup>2</sup>, which, if one-half-filled with solar power facilities, would generate 10 GW on average. 65 such blobs would provide 1 billion people with 16 kWh/d per person.</p>
</section>
<section id="concentrating-photovoltaics" class="level3">
<h3 class="anchored" data-anchor-id="concentrating-photovoltaics">Concentrating photovoltaics</h3>
<blockquote class="blockquote">
<p><em>(Figure omitted from this edition: third-party rights.)</em></p>
</blockquote>
<p><span class="figurenumber">Figure 25.9</span>. A 25 kW (peak) concentrator photovoltaic collector produced by Californian company Amonix. Its 225 m<sup>2</sup> aperture contains 5760 Fresnel lenses with optical concentration ×260, each of which illuminates a 25%-efficient silicon cell. One such collector, in an appropriate desert location, generates 138 kWh per day – enough to cover the energy consumption of half an American. Note the human providing a scale. Photo by David Faiman.</p>
<p>An alternative to concentrating thermal solar power in deserts is large-scale concentrating photovoltaic systems. To make these, we plop a high-quality electricity-producing solar cell at the focus of cheap lenses or mirrors. Faiman et al.&nbsp;(2007) say that “solar, in its concentrator photovoltaics variety, can be completely cost-competitive with fossil fuel [in desert states such as California, Arizona, New Mexico, and Texas] without the need for any kind of subsidy.”</p>
<p>According to manufacturers Amonix, <a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> this form of concentrating solar power would have an average power per unit land area of <span class="green">18 W/m<sup>2</sup></span>.</p>
<p>Another way to get a feel for required hardware is to personalize. One of the “25 kW” (peak) collectors shown in figure 25.9 generates on average about 138 kWh per day; the American lifestyle currently uses 250 kWh per day per person. So to get the USA off fossil fuels using solar power, we need roughly two of these 15 m×15 m collectors per person.</p>
</section>
</section>
<section id="queries" class="level2">
<h2 class="anchored" data-anchor-id="queries">Queries</h2>
<section id="im-confused-in-chapter-6-you-said-that-the-best-photovoltaic-panels-deliver-20-wm2-on-average-in-a-place-with-british-sunniness.-presumably-in-the-desert-the-same-panels-would-deliver-40-wm2.-so-how-come-the-concentrating-solar-power-stations-deliver-only-1520-wm2-surely-concentrating-power-should-be-even-better-than-plain-flat-panels" class="level4">
<h4 class="anchored" data-anchor-id="im-confused-in-chapter-6-you-said-that-the-best-photovoltaic-panels-deliver-20-wm2-on-average-in-a-place-with-british-sunniness.-presumably-in-the-desert-the-same-panels-would-deliver-40-wm2.-so-how-come-the-concentrating-solar-power-stations-deliver-only-1520-wm2-surely-concentrating-power-should-be-even-better-than-plain-flat-panels">I’m confused! In Chapter 6, you said that the best photovoltaic panels deliver 20 W/m<sup>2</sup> on average, in a place with British sunniness. Presumably in the desert the same panels would deliver 40 W/m<sup>2</sup>. So how come the concentrating solar power stations deliver only 15–20 W/m<sup>2</sup>? Surely concentrating power should be even better than plain flat panels?</h4>
<p>Good question. The short answer is no. Concentrating solar power does not achieve a better power per unit land area than flat panels. The concentrating contraption has to track the sun, otherwise the sunlight won’t be focused right; once you start packing land with sun-tracking contraptions, you have to leave gaps between them; lots of sunlight falls through the gaps and is lost. The reason that people nevertheless make concentrating solar power systems is that, today, flat photovoltaic panels are very expensive, and concentrating systems are cheaper. The concentrating people’s goal is not to make systems with big power per unit land area. Land area is cheap (they assume). The goal is to deliver big power per dollar.</p>
</section>
<section id="but-if-flat-panels-have-bigger-power-density-why-dont-you-describe-covering-the-sahara-desert-with-them" class="level4">
<h4 class="anchored" data-anchor-id="but-if-flat-panels-have-bigger-power-density-why-dont-you-describe-covering-the-sahara-desert-with-them">But if flat panels have bigger power density, why don’t you describe covering the Sahara desert with them?</h4>
<p>Because I am trying to discuss practical options for large-scale sustainable power production for Europe and North Africa by 2050. My guess is that by 2050, mirrors will still be cheaper than photovoltaic panels, so concentrating solar power is the technology on which we should focus.</p>
</section>
<section id="what-about-solar-chimneys" class="level4">
<h4 class="anchored" data-anchor-id="what-about-solar-chimneys">What about solar chimneys?</h4>
<p><img src="img/without-hot-air/figure210.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 25.10</span>. The Manzanares prototype solar chimney. Photos from <a href="http://solarmillennium.de"><span class="websitetitle">solarmillennium.de</span></a>.</p>
<p>A solar chimney or solar updraft tower uses solar power in a very simple way. <a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> A huge chimney is built at the centre of an area covered by a transparent roof made of glass or plastic; because hot air rises, hot air created in this greenhouse-like heat-collector whooshes up the chimney, drawing in cooler air from the perimeter of the heat-collector. Power is extracted from the air-flow by turbines at the base of the chimney. Solar chimneys are fairly simple to build, but they don’t deliver a very impressive power per unit area. A pilot plant in Manzanares, Spain operated for seven years between 1982 and 1989. The chimney had a height of 195 m and a diameter of 10 m; the collector had a diameter of 240 m, and its roof had 6000 m<sup>2</sup> of glass and 40 000 m<sup>2</sup> of transparent plastic. It generated 44 MWh per year, which corresponds to a power per unit area of <span class="green">0.1 W/m<sup>2</sup></span>. Theoretically, the bigger the collector and the taller the chimney, the bigger the power density of a solar chimney becomes. The engineers behind Manzanares reckon that, at a site with a solar radiation of 2300 kWh/m<sup>2</sup> per year (262 W/m<sup>2</sup>), a 1000 m-high tower surrounded by a 7 km-diameter collector could generate 680 GWh per year, an average power of 78 MW. That’s a power per unit area of about <span class="green">1.6 W/m<sup>2</sup></span>, which is similar to the power per unit area of windfarms in Britain, and one tenth of the power per unit area I said concentrating solar power stations would deliver. It’s claimed that solar chimneys could generate electricity at a price similar to that of conventional power stations. I suggest that countries that have enough land and sunshine to spare should host a big bake-off contest between solar chimneys and concentrating solar power, to be funded by oil-producing and oil-consuming countries.</p>
</section>
<section id="what-about-getting-power-from-iceland-where-geothermal-power-and-hydroelectricity-are-so-plentiful" class="level4">
<h4 class="anchored" data-anchor-id="what-about-getting-power-from-iceland-where-geothermal-power-and-hydroelectricity-are-so-plentiful">What about getting power from Iceland, where geothermal power and hydroelectricity are so plentiful?</h4>
<blockquote class="blockquote">
<p><em>(Figure omitted from this edition: third-party rights.)</em></p>
</blockquote>
<p><span class="figurenumber">Figure 25.11</span>. More geothermal power in Iceland. Photo by Rosie Ward.</p>
<p>Indeed, Iceland already effectively exports energy by powering industries that make energy-intensive products. Iceland produces nearly one ton of aluminium per citizen per year, for example! So from Iceland’s point of view, there are great profits to be made. But can Iceland save Europe? I would be surprised if Iceland’s power production could be scaled up enough to make sizeable electricity exports even to Britain alone. As a benchmark, let’s compare with the England–France Interconnector, which can deliver up to 2 GW across the English Channel. That maximum power is equivalent to 0.8 kWh per day per person in the UK, roughly 5% of British average electricity consumption. Iceland’s average geothermal electricity generation is just 0.3 GW, which is less than 1% of Britain’s average electricity consumption. Iceland’s average electricity production is 1.1 GW. <a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> So to create a link sending power equal to the capacity of the French interconnector, Iceland would have to <em>triple</em> its electricity production. To provide us with 4 kWh per day per person (roughly what Britain gets from its own nuclear power stations), Iceland’s electricity production would have to increase <em>ten-fold</em>. It is probably a good idea to build interconnectors to Iceland, but don’t expect them to deliver more than a small contribution.</p>
</section>
</section>
<section id="the-reverse-case-and-the-politics-of-it" class="level2">
<h2 class="anchored" data-anchor-id="the-reverse-case-and-the-politics-of-it">The reverse case, and the politics of it</h2>
<p><em>A note added in the 2026 revision.</em> MacKay frames this chapter as Britain buying other countries’ renewables. The 2020s produced a live example running the other way. Germany closed its last three nuclear reactors in April 2023 and, for the first time in many years, became a net electricity importer, drawing on hydro- and wind-rich Scandinavia.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> Because the Nordic and continental markets are coupled by interconnectors, German demand now reaches Swedish bills, and southern Sweden, wired directly to Germany, saw its prices rise. Swedish ministers publicly blamed Germany’s nuclear exit for higher prices at home.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> The counter-argument is that the feared German price spike never arrived: a year on, Germany had record renewable output and falling wholesale prices.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> So the dispute is less about a supply crisis than about who bears the cost of a coupled market, which is the question MacKay’s cheerful “living on someone else’s renewables” leaves open. The same coupling sits under the cannibalization model on the companion site.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a></p>
<p>The trade figures show the turn plainly, and also show that it did not begin in 2023. Germany ran an export surplus for two decades, peaking at 52 TWh in 2017 — roughly a sixth of everything Britain generates in a year, sold across the border. That surplus then shrank year by year as coal and lignite plants closed, and 2023 was simply the year it crossed zero. Net imports came to 26 TWh in 2024 and 20 TWh in 2025, about 6% of German supply: small in itself, but it is the sign of the number, not its size, that the politics fastened on.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/without-hot-air/fig-de-net-trade.svg" class="img-fluid figure-img"></p>
<figcaption>Germany’s net electricity trade, 1990 to 2025, in TWh per year. Germany is a net exporter through the 2000s and 2010s, with a peak surplus of 52 TWh in 2017; the surplus shrinks after that and turns to net imports of 9 TWh in 2023, the year the last reactors closed, then 26 TWh in 2024 and 20 TWh in 2025.</figcaption>
</figure>
</div>
<p>There is a sharper case than the wholesale market, and it is a cable that was never built. The Hansa PowerBridge would have been a second link between Sweden and Germany: 700 MW, about 300 km, some 600 million euros, shared between the two grid operators and due around 2035. Sweden rejected it in June 2024, because it would have connected Germany to SE4, the southern Swedish bidding zone where prices are already the highest in the country. In 2024 the SE4 average was 50 EUR/MWh against 25 in the north, and 78 in Germany — and a cable pulls the low price up towards the high one.</p>
<p>An open-access study in <em>Energy Policy</em> modelled exactly this and found the Swedish objection to be well founded, not merely political.<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a> Building the link raises total welfare in both countries, by about 69 million euros a year in Sweden and 77 million in Germany in 2035. But inside Sweden the gain is unevenly placed: Swedish producers gain roughly 176 million while Swedish consumers lose about 106 million, and German consumers gain 455 million. The country is better off and the people paying the bills are worse off. That is the whole difficulty of MacKay’s chapter stated in one line: the arithmetic of “living on someone else’s renewables” can add up nationally and still fail the household, and no amount of insisting on the total will settle it.</p>
<p>The same study is more useful for what it does next, which is to ask what would fix it. Splitting the interconnector’s costs and revenues unevenly in Sweden’s favour is not enough on its own. Handing Swedish consumers the extra profits that the state-owned utility Vattenfall would earn is not enough on its own either. Doing both makes the project Pareto-improving, meaning nobody ends up worse off. So does something else entirely: splitting Germany’s single bidding zone in two, which shrinks the north-German-to-southern-Swedish price gap and with it the Swedish price rise, and then no transfers are needed at all. The obstacle to living on a neighbour’s renewables, in other words, is not the physics or the cost of the cable. It is that the winnings land on one side of the meter and the losses on the other, and Europe has not built the plumbing to move them back.</p>
</section>
<section id="notes-and-further-reading" class="level2">
<h2 class="anchored" data-anchor-id="notes-and-further-reading">Notes and further reading</h2>
<p><img src="img/without-hot-air/figure212.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 25.12</span>. Two engineers assembling an eSolar <a href="http://esolar.com"><span class="websitetitle">esolar.com</span></a> concentrating power station using heliostats (mirrors that rotate and tip to follow the sun). esolar.com make medium-scale power stations: a 33 MW (peak) power unit on a 64 hectare site. That’s 51 W/m<sup>2</sup> peak, so I’d guess that in a typical desert location they would deliver about one quarter of that: <span class="green">13 W/m<sup>2</sup></span>. <a href="http://esolar.com"><span class="websitetitle">esolar.com</span></a></p>
<blockquote class="blockquote">
<p><em>(Figure omitted from this edition: third-party rights.)</em></p>
</blockquote>
<p><span class="figurenumber">Figure 25.13</span>. A high-voltage DC power system in China. Photo: ABB.</p>
<p>Further reading: European Commission (2007), German Aerospace Center (DLR) Institute of Technical Thermodynamics Section Systems Analysis and Technology Assessment (2006), <a href="http://www.solarmillennium.de/"><span class="websitetitle">www.solarmillennium.de</span></a>.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p><em>Concentrating solar power in deserts delivers an average power per unit area of roughly 15 W/m<sup>2</sup></em>. My sources for this number are two companies making concentrating solar power for deserts. <a href="http://www.stirlingenergy.com"><span class="websitetitle">www.stirlingenergy.com</span></a> says one of its dishes with a 25 kW Stirling engine at its focus can generate 60 000 kWh/y in a favourable desert location. They could be packed at a concentration of one dish per 500 m<sup>2</sup>. That’s an average power of <span class="green">14 W/m<sup>2</sup></span>. They say that solar dish Stirling makes the best use of land area, in terms of energy delivered. <a href="http://www.ausra.com/"><span class="websitetitle">www.ausra.com</span></a> uses flat mirrors to heat water to 285 °C and drive a steam turbine. The heated, pressurized water can be stored in deep metal-lined caverns to allow power generation at night. Describing a “240 MW(e)” plant proposed for Australia (Mills and LiÈvre, 2004), the designers claim that 3.5 km<sup>2</sup> of mirrors would deliver 1.2 TWh(e); that’s 38 W/m<sup>2</sup> of mirror. To find the power per unit land area, we need to allow for the gaps between the mirrors. Ausra say they need a 153 km by 153 km square in the desert to supply all US electric power (Mills and Morgan, 2008). Total US electricity is 3600 TWh/y, so they are claiming a power per unit land area of <span class="green">18 W/m<sup>2</sup></span>. This technology goes by the name <em>compact linear fresnel reflector</em> (Mills and Morrison, 2000; Mills et al., 2004; Mills and Morgan, 2008). Incidentally, rather than “concentrating solar power,” the company Ausra prefers to use the term <em>solar thermal electricity</em> (STE); they emphasize the benefits of thermal storage, in contrast to concentrating photovoltaics, which don’t come with a natural storage option. Trieb and Knies (2004), who are strong proponents of concentrating solar power, project that the alternative concentrating solar power technologies would have powers per unit land area in the following ranges: parabolic troughs, <span class="green">14–19 W/m<sup>2</sup></span>; linear fresnel collector, <span class="green">19–28 W/m<sup>2</sup></span>; tower with heliostats, <span class="green">9–14 W/m<sup>2</sup></span>; stirling dish, <span class="green">9–14 W/m<sup>2</sup></span>. There are three European demonstration plants for concentrating solar power. Andasol – using parabolic troughs; Solúcar PS10, a tower near Seville; and Solartres, a tower using molten salt for heat storage. The Andasol parabolictrough system shown in figure 25.4 is predicted to deliver 10 W/m<sup>2</sup>. Solúcar’s “11 MW” solar tower has 624 mirrors, each 121 m<sup>2</sup>. The mirrors concentrate sunlight to a radiation density of up to 650 kW/m<sup>2</sup>. The receiver receives a peak power of 55 MW. The power station can store 20 MWh of thermal energy, allowing it to keep going during 50 minutes of cloudiness. It was expected to generate 24.2 GWh of electricity per year, and it occupies 55 hectares. That’s an average power per unit land area of <span class="green">5 W/m<sup>2</sup></span>. (Source: Abengoa Annual Report 2003.) Solartres will occupy 142 hectares and is expected to produce 96.4 GWh per year; that’s a power density of <span class="green">8 W/m<sup>2</sup></span>. Andasol and Solartres will both use some natural gas in normal operation.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><em>HVDC is already used to transmit electricity over 1000-km distances in South Africa, China, America, Canada, Brazil, and Congo.</em> Sources: Asplund (2004), Bahrman and Johnson (2007). Further reading on HVDC: Carlsson (2002).<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><em>Losses on a 3500 km-long HVDC line, including conversion from AC to DC and back,would be about 15%.</em> Sources: Trieb and Knies (2004); van Voorthuysen (2008).<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><em>According to Amonix, concentrating photovoltaics would have an average power per unit land area of 18 W/m<sup>2</sup>.</em> The assumptions of <a href="http://www.amonix.com/"><span class="websitetitle">www.amonix.com</span></a> are: the lens transmits 85% of the light; 32% cell efficiency; 25% collector efficiency; and 10% further loss due to shading. Aperture/land ratio of 1/3. Normal direct irradiance: 2222 kWh/m<sup>2</sup>/year. They expect each kW of peak capacity to deliver 2000 kWh/y (an average of 0.23 kW). A plant of 1 GW peak capacity would occupy 12 km<sup>2</sup> of land and deliver 2000 GWh per year. That’s 18 W/m<sup>2</sup>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p><em>Solar chimneys.</em> Sources: Schlaich J (2001); Schlaich et al.&nbsp;(2005); Dennis (2006), <a href="http://www.enviromission.com.au/"><span class="websitetitle">www.enviromission.com.au</span></a>, <a href="http://www.solarairpower.com/"><span class="websitetitle">www.solarairpower.com</span></a>.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p><em>Iceland’s average geothermal electricity generation is just 0.3 GW. Iceland’s average electricity production is 1.1 GW.</em> These are the statistics for 2006: 7.3 TWh of hydroelectricity and 2.6 TWh of geothermal electricity, with capacities of 1.16 GW and 0.42 GW, respectively. Source: Orkustofnun National Energy Authority [<a href="http://www.os.is/page/energystatistics"><span class="websitetitle">www.os.is/page/energystatistics</span></a>].<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>The electricity-import shift after the April 2023 nuclear exit: Clean Energy Wire, “Q&amp;A – Germany’s nuclear exit: one year after”; on wider import dependence, Clean Energy Wire, “Germany and the EU remain heavily dependent on imported fossil fuels”.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Sweden’s criticism of German energy policy as prices rose: France 24, “Sweden sees red over Germany’s energy policy”, December 2024.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Fraunhofer ISE, “One year since Germany’s nuclear exit”, 2024; see also the German economy ministry’s earlier “get away from gas”, energiewende.bundeswirtschaftsministerium.de.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>The cannibalization model and its references: <a href="https://oluies.github.io/elmix/modell/referenser.html" class="uri">https://oluies.github.io/elmix/modell/referenser.html</a> .<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>Net electricity imports (imports minus exports), Ember via Our World in Data, <a href="https://ourworldindata.org/grapher/net-electricity-imports" class="uri">https://ourworldindata.org/grapher/net-electricity-imports</a> . The share of supply uses German generation of 431.7 TWh in 2024, from the Bundesnetzagentur’s 2024 electricity market data. UK generation for the 2017 comparison is about 290 TWh a year, from the same Our World in Data electricity dataset used elsewhere in this edition. Accounting bases differ: the Bundesnetzagentur’s commercial trade figures for 2023 are 54.1 TWh imported against 42.4 TWh exported, a net 11.7 TWh, where the Ember series plotted here gives 9.2 TWh. The sign and the shape of the turn are the same either way.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>Polina Emelianova, Pia Hoffmann-Willers and Oliver Ruhnau, “Redistribution through cross-border electricity trade: How to achieve Pareto improvement for consumers?”, <em>Energy Policy</em> 218 (2026) 115522, <a href="https://doi.org/10.1016/j.enpol.2026.115522" class="uri">https://doi.org/10.1016/j.enpol.2026.115522</a> , open access under CC BY. The welfare and surplus figures are their 2035 baseline case; the 2024 zonal prices in the paragraph above are theirs too, from ENTSO-E. The paper notes that the Swedish government signalled in early 2026 that it might reopen the project, conditional on Germany improving its price signals and adding baseload, so its fate is unsettled. Two other projects were stopped the same way: NorthConnect between Norway and the UK, cancelled in March 2023, and Eleclink 2 between Britain and France, paused by both regulators.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/chap24.html" class="pagination-link" aria-label="24 Nuclear?">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">24 Nuclear?</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/chap26.html" class="pagination-link" aria-label="26 Fluctuations and storage">
        <span class="nav-page-text"><span class="chapter-title">26 Fluctuations and storage</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>