<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9 Light – Sustainable Energy — Without the Hot Air</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/chap10.html" rel="next">
<link href="../chapters/chap08.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-1b15cd7dfe5d645daabccee077c4b062.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Pageview counting, same GoatCounter account as the elmix site. No cookies,
     no cross-site identifiers, nothing that needs a consent banner. -->
<script data-goatcounter="https://oluies.goatcounter.com/count" async="" src="//gc.zgo.at/count.js"></script>


</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chap01.html">Part I · Numbers, not adjectives</a></li><li class="breadcrumb-item"><a href="../chapters/chap09.html"><span class="chapter-title">9 Light</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Sustainable Energy — Without the Hot Air</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About this edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/preface.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I · Numbers, not adjectives</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap01.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">1 Motivations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap02.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">2 The balance sheet</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap03.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">3 Cars</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap04.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">4 Wind</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap05.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">5 Planes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap06.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">6 Solar</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap07.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">7 Heating and cooling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap08.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">8 Hydroelectricity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap09.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">9 Light</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap10.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">10 Offshore wind</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap11.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11 Gadgets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap11a.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">11a The machines behind the screen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap12.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">12 Wave</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap13.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">13 Food and farming</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap14.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">14 Tide</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap15.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">15 Stuff</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap16.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">16 Geothermal</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap17.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">17 Public services</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap18.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">18 Can we live on renewables?</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II · Making a difference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap19.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">19 Every BIG helps</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap20.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">20 Better transport</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap21.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">21 Smarter heating</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap22.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">22 Efficient electricity use</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap23.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">23 Sustainable fossil fuels?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap24.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">24 Nuclear?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap25.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">25 Living on other countries’ renewables?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap26.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">26 Fluctuations and storage</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap27.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">27 Five energy plans for Britain</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap28.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">28 Putting costs in perspective</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap-value-of-renewables.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">28a The value of renewable energy as it scales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap29.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">29 What to do now</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap30.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">30 Energy plans for Europe, America, and the World</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap31.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">31 The last thing we should talk about</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chap32.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">32 Saying yes</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III · Technical chapters</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapA.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">A Cars II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapB.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">B Wind II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapC.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">C Planes II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapD.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">D Solar II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapE.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">E Heating II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapF.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">F Waves II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapG.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">G Tide II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapH.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">H Stuff II</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV · Useful data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapI.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">I Quick reference</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapJ.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">J Populations and areas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapK.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">K UK energy history</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapL.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">L The world in 2025</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapM.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">M Energy return on investment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/chapN.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">N Peak oil, peak gas, peak uranium</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/charts.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Charts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/bibliography.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bibliography</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/author.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The author</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/acknowledgments.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Acknowledgments</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#lighting-home-and-work" id="toc-lighting-home-and-work" class="nav-link active" data-scroll-target="#lighting-home-and-work">Lighting home and work</a></li>
  <li><a href="#street-lights-and-traffic-lights" id="toc-street-lights-and-traffic-lights" class="nav-link" data-scroll-target="#street-lights-and-traffic-lights">Street-lights and traffic lights</a></li>
  <li><a href="#lights-on-the-traffic" id="toc-lights-on-the-traffic" class="nav-link" data-scroll-target="#lights-on-the-traffic">Lights on the traffic</a></li>
  <li><a href="#the-economics-of-low-energy-bulbs" id="toc-the-economics-of-low-energy-bulbs" class="nav-link" data-scroll-target="#the-economics-of-low-energy-bulbs">The economics of low-energy bulbs</a>
  <ul class="collapse">
  <li><a href="#mythconceptions" id="toc-mythconceptions" class="nav-link" data-scroll-target="#mythconceptions">Mythconceptions</a></li>
  </ul></li>
  <li><a href="#the-prediction-that-came-true" id="toc-the-prediction-that-came-true" class="nav-link" data-scroll-target="#the-prediction-that-came-true">The prediction that came true</a>
  <ul class="collapse">
  <li><a href="#what-happened-to-table-9.5" id="toc-what-happened-to-table-9.5" class="nav-link" data-scroll-target="#what-happened-to-table-9.5">What happened to table 9.5</a></li>
  <li><a href="#what-it-did-to-this-chapters-number" id="toc-what-it-did-to-this-chapters-number" class="nav-link" data-scroll-target="#what-it-did-to-this-chapters-number">What it did to this chapter’s number</a></li>
  <li><a href="#two-cautions" id="toc-two-cautions" class="nav-link" data-scroll-target="#two-cautions">Two cautions</a></li>
  <li><a href="#jevons-where-the-record-is-longest" id="toc-jevons-where-the-record-is-longest" class="nav-link" data-scroll-target="#jevons-where-the-record-is-longest">Jevons, where the record is longest</a></li>
  <li><a href="#the-street-lights-are-half-done" id="toc-the-street-lights-are-half-done" class="nav-link" data-scroll-target="#the-street-lights-are-half-done">The street lights are half done</a></li>
  <li><a href="#why-this-one-worked" id="toc-why-this-one-worked" class="nav-link" data-scroll-target="#why-this-one-worked">Why this one worked</a></li>
  </ul></li>
  <li><a href="#notes-and-further-reading" id="toc-notes-and-further-reading" class="nav-link" data-scroll-target="#notes-and-further-reading">Notes and further reading</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/chap01.html">Part I · Numbers, not adjectives</a></li><li class="breadcrumb-item"><a href="../chapters/chap09.html"><span class="chapter-title">9 Light</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">9 Light</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><img src="img/without-hot-air/figure67.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 9.1</span>. Lighting – 4 kWh per day per person.</p>
<section id="lighting-home-and-work" class="level2">
<h2 class="anchored" data-anchor-id="lighting-home-and-work">Lighting home and work</h2>
<p>The brightest domestic lightbulbs use 250 W, and bedside lamps use 40 W. In an old-fashioned incandescent bulb, most of this power gets turned into heat, rather than light. A fluorescent tube can produce an equal amount of light using one quarter of the power of an incandescent bulb.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Device</th>
<th>Power</th>
<th>Time per day</th>
<th>Energy per day per home</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10 incandescent lights</td>
<td>1 kW</td>
<td>5 h</td>
<td>5 kWh</td>
</tr>
<tr class="even">
<td>10 low-energy lights</td>
<td>0.1 kW</td>
<td>5 h</td>
<td>0.5 kWh</td>
</tr>
</tbody>
</table>
<p><span class="figurenumber">Table 9.2</span>. Electric consumption for domestic lighting. A plausible total is 5.5 kWh per home per day; and a similar figure at work; perhaps 4 kWh per day per person.</p>
<p>How much power does a moderately affluent person use for lighting? My rough estimate, based on table 9.2, is that a typical two-person home with a mix of low-energy and high-energy bulbs uses about 5.5 kWh per day, or 2.7 kWh per day per person. I assume that each person also has a workplace where they share similar illumination with their colleagues; guessing that the workplace uses 1.3 kWh/d per person, we get a round figure of 4 kWh/d per person.</p>
</section>
<section id="street-lights-and-traffic-lights" class="level2">
<h2 class="anchored" data-anchor-id="street-lights-and-traffic-lights">Street-lights and traffic lights</h2>
<p>Do we need to include public lighting too, to get an accurate estimate, or do home and work dominate the lighting budget? Street-lights in fact use about 0.1 kWh per day per person, <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> and traffic lights only 0.005 kWh/d per person <a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> – both negligible, compared with our home and workplace lighting. What about other forms of public lighting – illuminated signs and bollards, for example? There are fewer of them than street-lights; <a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> and street-lights already came in well under our radar, so we don’t need to modify our overall estimate of 4 kWh/d per person.</p>
</section>
<section id="lights-on-the-traffic" class="level2">
<h2 class="anchored" data-anchor-id="lights-on-the-traffic">Lights on the traffic</h2>
<p><img src="img/without-hot-air/figure68.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 9.3</span>. Total cumulative cost of using a traditional incandescent 100 W bulb for 3 hours per day, compared with replacing it <em>now</em> with an Osram Dulux Longlife Energy Saver (pictured). Assumptions: electricity costs 10p per kWh; replacement traditional bulbs cost 45p each; energy-saving bulbs cost £9. (I know you can find them cheaper than this, but this graph shows that even at £9, they’re much more economical.)</p>
<p>In some countries, drivers must switch their lights on whenever their car is moving. How does the extra power required by that policy compare with the power already being used to trundle the car around? Let’s say the car has four incandescent lights totalling 100 W. The electricity for those bulbs is supplied by a 25%-efficient engine powering a 55%-efficient generator, <a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> so the power required is 730 W. For comparison, a typical car going at an average speed of 50 km/h and consuming one litre per 12 km <span id="page58">has</span> an average power consumption of <span class="red">42 000W</span>. So having the lights on while driving requires 2% extra power.</p>
<p>What about the future’s electric cars? The power consumption of a typical electric car is about 5000 W. So popping on an extra 100 W would increase its consumption by 2%. Power consumption would be smaller if we switched all car lights to light-emitting diodes, but if we pay any more attention to this topic, we will be coming down with a severe case of every-little-helps-ism.</p>
</section>
<section id="the-economics-of-low-energy-bulbs" class="level2">
<h2 class="anchored" data-anchor-id="the-economics-of-low-energy-bulbs">The economics of low-energy bulbs</h2>
<p>Generally I avoid discussing economics, but I’d like to make an exception for lightbulbs. Osram’s 20 W low-energy bulb claims the same light output as a 100 W incandescent bulb. Moreover, its lifetime is said to be 15 000 hours (or “12 years,” at 3 hours per day). In contrast a typical incandescent bulb might last 1000 hours. So during a 12-year period, you have this choice (figure 9.3): buy 15 incandescent bulbs and 1500 kWh of electricity (which costs roughly £150); or buy one low-energy bulb and 300 kWh of electricity (which costs roughly £30).</p>
<section id="should-i-wait-until-the-old-bulb-dies-before-replacing-it" class="level4">
<h4 class="anchored" data-anchor-id="should-i-wait-until-the-old-bulb-dies-before-replacing-it">Should I wait until the old bulb dies before replacing it?</h4>
<p>It feels like a waste, doesn’t it? Someone put resources into making the old incandescent lightbulb; shouldn’t we cash in that original investment by using the bulb until it’s worn out? But the economic answer is clear: <em>continuing to use an old lightbulb is throwing good money after bad</em>. If you can find a satisfactory low-energy replacement, replace the old bulb now.</p>
</section>
<section id="what-about-the-mercury-in-compact-fluorescent-lights-are-led-bulbs-better-than-fluorescents" class="level4">
<h4 class="anchored" data-anchor-id="what-about-the-mercury-in-compact-fluorescent-lights-are-led-bulbs-better-than-fluorescents">What about the mercury in compact fluorescent lights? Are LED bulbs better than fluorescents?</h4>
<p><img src="img/without-hot-air/figure69.gif" class="img-fluid"></p>
<p><span class="figurenumber">Figure 9.4</span>. Philips 11 W alongside Omicron 1.3 W LED bulb.</p>
<p>Researchers say that LED (light-emitting diode) bulbs will soon be even more energy-efficient than compact fluorescent lights. The efficiency of a light is measured in <em>lumens per watt</em>. I checked the numbers on my latest purchases: the Philips Genie 11 W compact fluorescent bulb (figure 9.4) has a brightness of 600 lumens, which is an efficiency of <strong>55 lumens per watt</strong>; regular incandescent bulbs deliver <strong>10 lumens per watt</strong>; the Omicron 1.3 W lamp, which has 20 white LEDs hiding inside it, has a brightness of 46 lumens, which is an efficiency of <strong>35 lumens per watt</strong>. So this LED bulb is almost as efficient as the fluorescent bulb. The LED industry still has a little catching up to do. In its favour, the LED bulb has a life of 50 000 hours, eight times the life of the fluorescent bulb. As I write, I see that <a href="http://www.cree.com"><span class="websitetitle">www.cree.com</span></a> is selling LEDs with a power of <strong>100 lumens per watt</strong>. It’s projected that in the future, white LEDs will have an efficiency of over 150 lumens per watt [<a href="http://tinyurl.com/ynjzej"><span class="websitetitle">ynjzej</span></a>]. I expect that within another couple of years, the best advice, from the point of view of both energy efficiency and avoiding mercury pollution, will be to use LED bulbs.</p>
</section>
<section id="mythconceptions" class="level3">
<h3 class="anchored" data-anchor-id="mythconceptions">Mythconceptions</h3>
<section id="there-is-no-point-in-my-switching-to-energy-saving-lights.-thewasted-energy-they-put-out-heats-my-home-so-its-not-wasted." class="level4">
<h4 class="anchored" data-anchor-id="there-is-no-point-in-my-switching-to-energy-saving-lights.-thewasted-energy-they-put-out-heats-my-home-so-its-not-wasted.">“There is no point in my switching to energy-saving lights. The”wasted” energy they put out heats my home, so it’s not wasted.”</h4>
<p>This myth is addressed in Chapter 11.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Bulb type</th>
<th>efficiency (lumens/W)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>incandescent</td>
<td>10</td>
</tr>
<tr class="even">
<td>halogen</td>
<td>16-24</td>
</tr>
<tr class="odd">
<td>white LED</td>
<td>35</td>
</tr>
<tr class="even">
<td>compact fluorescent</td>
<td>55</td>
</tr>
<tr class="odd">
<td>large fluorescent</td>
<td>94</td>
</tr>
<tr class="even">
<td>sodium street light</td>
<td>150</td>
</tr>
</tbody>
</table>
<p><span class="figurenumber">Table 9.5</span>. Lighting efficiencies of commercially-available bulbs. In the future, white LEDs are expected to deliver 150 lumens per watt.</p>
</section>
</section>
</section>
<section id="the-prediction-that-came-true" class="level2">
<h2 class="anchored" data-anchor-id="the-prediction-that-came-true">The prediction that came true</h2>
<p><em>A section added in the 2026 revision.</em> This chapter ends with a forecast, and it is one of the few in the book that can now simply be marked correct:</p>
<blockquote class="blockquote">
<p><em>I expect that within another couple of years, the best advice, from the point of view of both energy efficiency and avoiding mercury pollution, will be to use LED bulbs.</em></p>
</blockquote>
<p>It happened, faster and more completely than the chapter’s cautious tone suggests. MacKay’s own LED sample managed <strong>35 lumens per watt</strong> and he judged that “the LED industry still has a little catching up to do”. Table 9.5 records the expectation that white LEDs would eventually reach 150 lm/W.</p>
<section id="what-happened-to-table-9.5" class="level3">
<h3 class="anchored" data-anchor-id="what-happened-to-table-9.5">What happened to table 9.5</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Bulb type</th>
<th>MacKay, 2008</th>
<th>2026</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>incandescent</td>
<td>10 lm/W</td>
<td>withdrawn from sale</td>
</tr>
<tr class="even">
<td>halogen</td>
<td>16–24 lm/W</td>
<td>withdrawn from sale</td>
</tr>
<tr class="odd">
<td>white LED</td>
<td><strong>35 lm/W</strong></td>
<td><strong>180–210 lm/W</strong> in the best commercial lamps</td>
</tr>
<tr class="even">
<td>compact fluorescent</td>
<td>55 lm/W</td>
<td>withdrawn from sale</td>
</tr>
<tr class="odd">
<td>large fluorescent</td>
<td>94 lm/W</td>
<td>being withdrawn</td>
</tr>
<tr class="even">
<td>sodium street light</td>
<td>150 lm/W</td>
<td>superseded by LED</td>
</tr>
</tbody>
</table>
<p>Every technology in his table except the LED has now been legislated off the market, and the one he thought was behind overtook all of them. LED efficacy has improved by roughly <strong>6 to 8 lumens per watt every year since 2010</strong>; the best commercial lamps now test above <strong>200 lm/W</strong>, converting more than half their input power into light rather than heat.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<p>That is six times MacKay’s LED sample, nearly four times his compact fluorescent, and <strong>twenty times the incandescent bulb</strong> the chapter is written against. His 150 lm/W projection was not optimistic; it was passed.</p>
</section>
<section id="what-it-did-to-this-chapters-number" class="level3">
<h3 class="anchored" data-anchor-id="what-it-did-to-this-chapters-number">What it did to this chapter’s number</h3>
<p>MacKay estimated 4 kWh/d per person for lighting: 2.7 at home and 1.3 at work, from a household using <strong>5.5 kWh/d</strong> on lighting alone.</p>
<p>Put that beside the household of today. Average British domestic electricity consumption has fallen from <strong>4630 kWh a year in 2008 to 3264 in 2023</strong> — about 29% — which is <strong>8.9 kWh/d per household for everything</strong>: lighting, cooking, refrigeration, washing, televisions, computers and chargers together.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<p><strong>MacKay’s lighting estimate alone, 5.5 kWh/d, is nearly two-thirds of what a British household now uses in total.</strong> The change per fitting is a reduction of 80 to 90%, so on unchanged habits this chapter’s 4 kWh/d per person would now be something under 1.</p>
</section>
<section id="two-cautions" class="level3">
<h3 class="anchored" data-anchor-id="two-cautions">Two cautions</h3>
<p><strong>The number can no longer be checked properly.</strong> The government’s <em>Energy Consumption in the UK</em> series <strong>discontinued its Electrical Products tables in the 2025 edition</strong>, following concerns about the models underlying the appliance-level estimates. There is no longer an official British breakdown of household electricity by end use, so the figure that replaces MacKay’s 4 kWh/d has to be inferred rather than looked up. This edition has run into the same wall in chapter 8 over reservoir storage: the arithmetic in this book depends on statistics that are, in places, being withdrawn.</p>
<p><strong>And cheap light invites more light</strong> — which deserves more than a sentence, because lighting is the single best-documented case of the rebound effect anywhere in energy.</p>
</section>
<section id="jevons-where-the-record-is-longest" class="level3">
<h3 class="anchored" data-anchor-id="jevons-where-the-record-is-longest">Jevons, where the record is longest</h3>
<p>Fouquet and Pearson traced the price and use of light in Britain from 1300 to 2000. The real price of light fell roughly <strong>3000-fold between 1800 and 2000</strong>, and consumption rose to about <strong>40 000 times</strong> its 1800 level. Per-person consumption of light grew faster than per-person GDP. Across seven centuries, every improvement in lighting efficiency was met by buying more light rather than banking the saving.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<p>Working from that series, Tsao and Waide put the price and income elasticity of demand for light at close to <strong>unity</strong> — a 10% fall in price raises consumption by about 10% — and predicted on that basis that solid-state lighting would produce not merely rebound but <strong>backfire</strong>: total energy spent on lighting rising after the efficiency gain, exactly as Jevons argued for coal in 1865.</p>
<p><strong>Has it?</strong> Not in Britain, so far. Domestic electricity per household fell 29% between 2008 and 2023, and lighting is part of why. The reason is one Fouquet and Pearson identified themselves in later work: these elasticities depend on the stage of development. A poor country handed cheap light buys a great deal more of it. A rich country is already lighting everything it wants lit after dark, and further price falls buy diminishing amounts of extra illumination.</p>
<p>So the honest position is a split one: <strong>backfire in the historical record and probably still across much of the world; saturation in Britain.</strong> This chapter is about Britain, and here the gain has largely been kept.</p>
<p><strong>Decorative lighting is where that saturation argument is weakest</strong>, and it is the visible exception on any winter street. Festive displays run for weeks, permanent architectural and garden lighting, illuminated signage and the lighting of things nobody previously thought to light — this is demand that would not exist at incandescent running costs, and it has appeared precisely where saturation says growth should have stopped. It remains a small share of the total, but it is the clearest domestic sighting of Jevons at work, and it is worth noticing that it grew because the running cost approached zero rather than because anyone decided they needed more light.</p>
</section>
<section id="the-street-lights-are-half-done" class="level3">
<h3 class="anchored" data-anchor-id="the-street-lights-are-half-done">The street lights are half done</h3>
<p>MacKay put public lighting at 0.1 kWh/d per person and set it aside as negligible. It is being converted, and slowly enough to be worth recording.</p>
<p>England’s county councils have committed about <strong>£442 million</strong> to LED street lighting, and a freedom-of-information survey found only <strong>10 of 29 county schemes complete</strong>. Scotland has roughly <strong>900 000 street lights, of which about 35% have been converted</strong>. Full national conversion is projected around <strong>2035</strong> — a quarter of a century after this book was written.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
<p>Where it is finished the savings are large. Hertfordshire converted 117 361 lights for a 79% cut in street-lighting emissions and about £6.9 million a year; West Dunbartonshire cut its street-lighting electricity by 65%.</p>
<p>So MacKay’s 0.1 kWh/d per person is on its way to something nearer 0.03. The interesting part is why it is taking so long, and it is the mirror image of the bulb. A street light is not a drop-in replacement bought by a householder for four pounds. It is a municipal capital programme, twenty-nine of them, each with its own budget cycle, procurement and borrowing constraint. The technology was ready in about 2012. The institutions were not.</p>
</section>
<section id="why-this-one-worked" class="level3">
<h3 class="anchored" data-anchor-id="why-this-one-worked">Why this one worked</h3>
<p>It is worth asking why lighting was solved so completely when heating, in chapter 7, was not. The answer is not that the physics was easier — a heat pump beats a boiler by a wider margin than an LED beats an incandescent in primary-energy terms.</p>
<p>It is that a light bulb is a <strong>drop-in replacement</strong>. It costs a few pounds, screws into the fitting that is already there, needs no installer, no survey, no wet system, no cylinder, no planning, and no favourable ratio between two fuel prices. Nothing about the building has to change. Chapter 7’s machine has to overcome all of those at once.</p>
<p>The lesson is not about lamps. It is that the energy transitions that actually complete are the ones that fit into the socket that is already in the wall.</p>
</section>
</section>
<section id="notes-and-further-reading" class="level2">
<h2 class="anchored" data-anchor-id="notes-and-further-reading">Notes and further reading</h2>
<p>page no.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p><em>Street-lights use about 0.1 kWh per day per person…</em> There’s roughly one sodium street-light per 10 people; each light has a power of 100 W, switched on for 10 hours per day. That’s 0.1 kWh per day per person.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><em>… and traffic lights only 0.005 kWh/d per person</em>. Britain has 420 000 traffic and pedestrian signal light bulbs, consuming 100 million kWh of electricity per year. Shared between 60 million people, 100 million kWh per year is 0.005 kWh/d per person.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p><em>There are fewer signs and illuminated bollards than street-lights</em>. [<a href="http://www.highwayelectrical.org.uk/"><span class="websitetitle">www.highwayelectrical.org.uk</span></a>]. There are 7.7 million lighting units (street lighting, illuminated signs and bollards) in the UK. Of these, roughly 7 million are street-lights and 1 million are illuminated road signs. There are 210 000 traffic signals. According to DUKES 2005, the total power for public lighting is 2095 GWh/y, which is 0.1 kWh/d per person.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><em>55%-efficient generator</em> – source: <a href="http://en.wikipedia.org/wiki/Alternator"><span class="websitetitle">en.wikipedia.org/wiki/Alternator</span></a>. Generators in power stations are much more efficient at converting mechanical work to electricity.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Best commercial LED lamps tested above 200 lumens per watt, with 2025-model lamps commonly at 180 lm/W and the best measured at 210; the long-run improvement is about 6–8 lm/W per year since 2010, with fleet-average efficacy around 107 lm/W in 2020. Figures are for the lamp, not the luminaire, and manufacturers quote under laboratory conditions at rated drive current and 25°C; a lamp in a warm enclosed fitting will do worse. Note also that efficacy is traded against colour rendering, so the highest-efficacy products are not always the ones people want in a living room. The withdrawal dates differ by jurisdiction and product class — incandescent, then mains-voltage halogen, then compact fluorescent and now linear fluorescent tubes have been progressively removed from the EU and UK markets under ecodesign and hazardous-substances rules — and specific dates are not given here because they vary by lamp type and by country.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Household electricity consumption from the Department for Energy Security and Net Zero: an average of 4630 kWh per household in 2008 against 3264 kWh in 2023, a fall of about 29%, attributed to more efficient appliances, better lighting and tighter product standards. The per-fitting reduction of 80–90% from replacing incandescent and halogen lamps with LEDs is an industry figure rather than a metered one. The <em>Energy Consumption in the UK</em> Electrical Products tables, which previously gave the appliance-level split including lighting, were discontinued in the 2025 edition over concerns about the underlying models; the lighting figure quoted here for today is therefore an inference from the per-fitting saving and not an official statistic.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Roger Fouquet and Peter J. G. Pearson, “Seven Centuries of Energy Services: The Price and Use of Light in the United Kingdom (1300–2000)”, <em>The Energy Journal</em> 27(1), 2006, and their later “The Long Run Demand for Lighting: Elasticities and Rebound Effects in Different Phases of Economic Development”, 2012, which is the source for elasticities varying with development stage. The unit-elasticity estimate and the backfire prediction for solid-state lighting are from J. Y. Tsao and P. Waide (2010). Two cautions on the 40 000-fold figure: it is consumption of lighting <em>services</em> in lumen-hours, not energy, and it is reconstructed from price and income series over centuries, so it carries wide uncertainty at the early end. The claim that Britain has so far avoided backfire rests on aggregate household electricity rather than on metered lighting, which as noted above is no longer separately published.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>LED street-lighting conversion figures are from a freedom-of-information survey of English county councils reported in 2025 — about £442 million committed and 10 of 29 county schemes complete — together with Scottish Futures Trust figures of roughly 900 000 Scottish street lights and about 35% converted, and individual council announcements (Hertfordshire 117 361 lights, 79% emissions reduction, about £6.9 million a year; Staffordshire 47 955 lights in phase one; West Dunbartonshire 65% electricity reduction). These are self-reported council figures on differing baselines and are not a consistent national statistic; the 2035 completion date is a projection rather than a plan. Note also that England’s county councils are not the whole country — unitary authorities, London boroughs and Wales are not covered by that survey.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/chap08.html" class="pagination-link" aria-label="8 Hydroelectricity">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">8 Hydroelectricity</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/chap10.html" class="pagination-link" aria-label="10 Offshore wind">
        <span class="nav-page-text"><span class="chapter-title">10 Offshore wind</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>